export const SERVICES_PART2 = [
  {
    id: "maps",
    num: "04",
    title: { fr: "Google Maps Top 3", en: "Google Maps Top 3", vi: "Google Maps Top 3" },
    short: { fr: "Visibilité locale et positionnement carte.", en: "Local visibility and map ranking.", vi: "Hiển thị địa phương và xếp hạng bản đồ." },
    description: { fr: "Optimisation de votre fiche Google Business Profile et stratégie locale pour apparaître dans le Top 3 des recherches pertinentes.", en: "Optimisation of your Google Business Profile and local strategy to appear in the Top 3 of relevant searches.", vi: "Tối ưu Google Business Profile và chiến lược địa phương để xuất hiện Top 3." },
    fromEur: 990,
    fromPeriod: "year",
    highlights: [
      { fr: "Fiche Google optimisée", en: "Optimised Google profile", vi: "Hồ sơ Google tối ưu" },
      { fr: "Suivi de positionnement", en: "Ranking monitoring", vi: "Theo dõi thứ hạng" },
    ],
    plans: [
      {
        name: { fr: "Maps Top 3", en: "Maps Top 3", vi: "Maps Top 3" },
        eur: 990,
        period: "year",
        features: [
          { fr: "Audit local complet", en: "Full local audit", vi: "Kiểm toán địa phương" },
          { fr: "Optimisation fiche GBP", en: "GBP profile optimisation", vi: "Tối ưu hồ sơ GBP" },
          { fr: "Suivi mensuel", en: "Monthly monitoring", vi: "Theo dõi hàng tháng" },
        ],
      },
    ],
  },
  {
    id: "social",
    num: "05",
    title: { fr: "Social Media & Contenu", en: "Social Media & Content", vi: "Mạng xã hội & Nội dung" },
    short: { fr: "Stratégie, contenus et animation des réseaux.", en: "Strategy, content and community management.", vi: "Chiến lược, nội dung và quản lý cộng đồng." },
    description: { fr: "Calendrier éditorial, création de contenus et animation Instagram, Facebook, LinkedIn et TikTok.", en: "Editorial calendar, content creation and management of Instagram, Facebook, LinkedIn and TikTok.", vi: "Lịch biên tập, sáng tạo nội dung và quản lý Instagram, Facebook, LinkedIn, TikTok." },
    fromEur: 299,
    fromPeriod: "month",
    highlights: [
      { fr: "4 réseaux principaux", en: "4 main networks", vi: "4 mạng chính" },
      { fr: "Calendrier éditorial", en: "Editorial calendar", vi: "Lịch biên tập" },
    ],
    plans: [
      {
        name: { fr: "Présence Essentielle", en: "Essential Presence", vi: "Hiện diện Cơ bản" },
        eur: 299,
        period: "month",
        features: [
          { fr: "1 réseau social", en: "1 social network", vi: "1 mạng xã hội" },
          { fr: "8 publications / mois", en: "8 posts / month", vi: "8 bài đăng / tháng" },
          { fr: "Visuels + rédaction", en: "Visuals + copywriting", vi: "Hình ảnh + nội dung" },
          { fr: "Programmation des publications", en: "Post scheduling", vi: "Lên lịch đăng bài" },
          { fr: "Modération légère", en: "Light moderation", vi: "Kiểm duyệt cơ bản" },
        ],
      },
      {
        name: { fr: "Croissance Active", en: "Active Growth", vi: "Tăng trưởng Chủ động" },
        eur: 499,
        period: "month",
        popular: true,
        features: [
          { fr: "2 réseaux sociaux", en: "2 social networks", vi: "2 mạng xã hội" },
          { fr: "20 publications / mois", en: "20 posts / month", vi: "20 bài đăng / tháng" },
          { fr: "Visuels + copywriting", en: "Visuals + copywriting", vi: "Hình ảnh + copywriting" },
          { fr: "Stories / formats courts selon planning", en: "Stories / short formats according to schedule", vi: "Stories / định dạng ngắn theo lịch" },
          { fr: "Modération et réponses courantes", en: "Moderation and routine replies", vi: "Kiểm duyệt và trả lời thường xuyên" },
          { fr: "Reporting mensuel", en: "Monthly reporting", vi: "Báo cáo hàng tháng" },
        ],
      },
      {
        name: { fr: "Domination Sociale", en: "Social Domination", vi: "Phủ sóng Mạng xã hội" },
        eur: 699,
        period: "month",
        features: [
          { fr: "3 réseaux sociaux", en: "3 social networks", vi: "3 mạng xã hội" },
          { fr: "30 publications / mois", en: "30 posts / month", vi: "30 bài đăng / tháng" },
          { fr: "Création, rédaction et programmation", en: "Creation, copywriting and scheduling", vi: "Sáng tạo, viết và lên lịch" },
          { fr: "Stories / formats courts", en: "Stories / short formats", vi: "Stories / định dạng ngắn" },
          { fr: "Modération renforcée", en: "Enhanced moderation", vi: "Kiểm duyệt nâng cao" },
          { fr: "Veille + reporting mensuel", en: "Monitoring + monthly reporting", vi: "Theo dõi + báo cáo hàng tháng" },
        ],
      },
    ],
  {
    id: "maintenance",
    num: "06",
    title: { fr: "WebCare & Maintenance", en: "WebCare & Maintenance", vi: "WebCare & Bảo trì" },
    short: { fr: "Corrections, évolutions et suivi du site.", en: "Fixes, updates and site monitoring.", vi: "Sửa lỗi, cập nhật và giám sát site." },
    description: { fr: "Maintenance technique, mises à jour de sécurité et petites évolutions pour garder votre site fiable.", en: "Technical maintenance, security updates and small evolutions to keep your site reliable.", vi: "Bảo trì kỹ thuật, cập nhật bảo mật và điều chỉnh nhỏ." },
    fromEur: 29,
    fromPeriod: "month",
    highlights: [
      { fr: "Mises à jour sécurité", en: "Security updates", vi: "Cập nhật bảo mật" },
      { fr: "Support prioritaire", en: "Priority support", vi: "Hỗ trợ ưu tiên" },
    ],
    plans: [
      {
        name: { fr: "Essentiel", en: "Essential", vi: "Cơ bản" },
        eur: 29,
        period: "month",
        features: [
          { fr: "4 modifications / mois", en: "4 changes / month", vi: "4 chỉnh sửa / tháng" },
          { fr: "Corrections de contenu et visuels", en: "Content and visual fixes", vi: "Sửa nội dung và hình ảnh" },
          { fr: "Interventions techniques courantes", en: "Routine technical interventions", vi: "Can thiệp kỹ thuật thường xuyên" },
          { fr: "Suivi standard", en: "Standard support", vi: "Hỗ trợ tiêu chuẩn" },
        ],
      },
      {
        name: { fr: "Business", en: "Business", vi: "Business" },
        eur: 49,
        period: "month",
        popular: true,
        features: [
          { fr: "10 modifications / mois", en: "10 changes / month", vi: "10 chỉnh sửa / tháng" },
          { fr: "Corrections de contenu, visuels et sections", en: "Content, visual and section updates", vi: "Chỉnh sửa nội dung, hình ảnh và phần" },
          { fr: "Interventions techniques courantes", en: "Routine technical interventions", vi: "Can thiệp kỹ thuật thường xuyên" },
          { fr: "Priorité de traitement", en: "Priority handling", vi: "Ưu tiên xử lý" },
          { fr: "Conseils d'évolution courante", en: "Routine improvement advice", vi: "Tư vấn cải tiến thường xuyên" },
        ],
      },
      {
        name: { fr: "Unlimited", en: "Unlimited", vi: "Unlimited" },
        eur: 99,
        period: "month",
        features: [
          { fr: "Modifications courantes illimitées dans le périmètre du site", en: "Unlimited routine changes within the site scope", vi: "Chỉnh sửa thường xuyên không giới hạn trong phạm vi website" },
          { fr: "Corrections de contenu, visuels et sections", en: "Content, visual and section updates", vi: "Chỉnh sửa nội dung, hình ảnh và phần" },
          { fr: "Suivi technique prioritaire", en: "Priority technical support", vi: "Hỗ trợ kỹ thuật ưu tiên" },
          { fr: "Petites évolutions incluses", en: "Small improvements included", vi: "Bao gồm các cải tiến nhỏ" },
          { fr: "Refontes et développements spécifiques sur devis", en: "Redesigns and major development quoted separately", vi: "Thiết kế lại và phát triển lớn báo giá riêng" },
        ],
      },
    ],
  {
    id: "ecommerce",
    num: "07",
    title: { fr: "E-commerce & Réservation", en: "E-commerce & Booking", vi: "Thương mại điện tử & Đặt chỗ" },
    short: { fr: "Vendre, réserver et convertir en ligne.", en: "Sell, book and convert online.", vi: "Bán hàng, đặt chỗ và chuyển đổi trực tuyến." },
    description: { fr: "Une expérience e-commerce ou de réservation pensée pour le mobile, le paiement et la conversion.", en: "An e-commerce or booking experience designed for mobile, payments and conversion.", vi: "Trải nghiệm thương mại điện tử hoặc đặt chỗ được thiết kế cho mobile, thanh toán và chuyển đổi." },
    fromEur: 1490,
    fromPeriod: "once",
    highlights: [
      { fr: "Catalogue, panier et commande", en: "Catalogue, cart and checkout", vi: "Danh mục, giỏ hàng và thanh toán" },
      { fr: "Paiement sécurisé", en: "Secure payments", vi: "Thanh toán an toàn" },
      { fr: "Réservation selon besoin", en: "Booking when needed", vi: "Đặt chỗ theo nhu cầu" },
    ],
    plans: [
      {
        name: { fr: "E-commerce & Réservation", en: "E-commerce & Booking", vi: "Thương mại điện tử & Đặt chỗ" },
        eur: 1490,
        period: "once",
        popular: true,
        features: [
          { fr: "Catalogue produits ou services", en: "Product or service catalogue", vi: "Danh mục sản phẩm hoặc dịch vụ" },
          { fr: "Panier, commande et paiement sécurisé", en: "Cart, checkout and secure payment", vi: "Giỏ hàng, đặt hàng và thanh toán an toàn" },
          { fr: "Parcours mobile optimisé", en: "Mobile-optimised journey", vi: "Hành trình tối ưu cho mobile" },
          { fr: "Réservation selon le projet", en: "Booking flow when required", vi: "Luồng đặt chỗ theo dự án" },
          { fr: "SEO de base + analytics", en: "Basic SEO + analytics", vi: "SEO cơ bản + analytics" },
        ],
      },
    ],
  },
];
