export const SERVICES_PART2 = [
  {
    id: "maps",
    num: "04",
    title: { fr: "Google Maps Top 3", en: "Google Maps Top 3", vi: "Google Maps Top 3", ar: "Google Maps Top 3", ru: "Google Maps Top 3" },
    short: { fr: "Visibilité locale et positionnement carte.", en: "Local visibility and map ranking.", vi: "Hiển thị địa phương và xếp hạng bản đồ.", ar: "ظهور محلي وتحسين الحضور على الخرائط.", ru: "Локальная видимость и присутствие на карте." },
    description: { fr: "Optimisation de votre fiche Google Business Profile et stratégie locale avec un engagement clair : viser le Top 3 sur les requêtes et zones définies au diagnostic, avec une garantie « Top 3 ou remboursé » lorsque les critères, délais et conditions de la garantie sont réunis.", en: "Google Business Profile optimisation and local strategy with a clear commitment: target Top 3 visibility for the searches and areas defined at diagnosis, with a « Top 3 or money back » guarantee when the agreed criteria, timeframe and guarantee conditions are met.", vi: "Tối ưu Google Business Profile và chiến lược địa phương với cam kết rõ ràng: hướng tới Top 3 theo truy vấn và khu vực được xác định khi chẩn đoán, kèm bảo đảm « Top 3 hoặc hoàn tiền » khi đáp ứng các tiêu chí, thời hạn và điều kiện đã thỏa thuận." },
    fromEur: 990,
    fromPeriod: "year",
    highlights: [
      { fr: "Fiche Google optimisée", en: "Optimised Google profile", vi: "Hồ sơ Google tối ưu", ar: "ملف Google محسّن", ru: "Оптимизированный профиль Google" },
      { fr: "Suivi de positionnement", en: "Ranking monitoring", vi: "Theo dõi thứ hạng", ar: "متابعة الظهور والترتيب", ru: "Мониторинг позиций" },
      { fr: "Stratégie locale sur mesure", en: "Tailored local strategy", vi: "Chiến lược địa phương theo nhu cầu", ar: "استراتيجية محلية مخصصة", ru: "Индивидуальная локальная стратегия" },
    ],
    steps: [
      { num: "01", title: { fr: "Audit & benchmark", en: "Audit & benchmark", vi: "Kiểm toán & benchmark", ar: "التدقيق والمقارنة", ru: "Аудит и benchmark" }, desc: { fr: "Analyse de la fiche, des concurrents et des requêtes locales qui comptent.", en: "Analysis of the profile, competitors and relevant local searches.", vi: "Phân tích hồ sơ, đối thủ và các truy vấn địa phương quan trọng.", ar: "تحليل الملف والمنافسين وعمليات البحث المحلية المهمة.", ru: "Анализ профиля, конкурентов и целевых локальных запросов." } },
      { num: "02", title: { fr: "Optimisation GBP", en: "GBP optimisation", vi: "Tối ưu GBP", ar: "تحسين ملف GBP", ru: "Оптимизация GBP" }, desc: { fr: "Catégories, services, informations, contenus et signaux du profil sont retravaillés.", en: "Categories, services, information, content and profile signals are refined.", vi: "Danh mục, dịch vụ, thông tin, nội dung và tín hiệu hồ sơ được tối ưu.", ar: "إعادة ضبط الفئات والخدمات والمعلومات والمحتوى وإشارات الملف.", ru: "Категории, услуги, информация, контент и сигналы профиля дорабатываются." } },
      { num: "03", title: { fr: "Autorité locale", en: "Local authority", vi: "Uy tín địa phương", ar: "السلطة المحلية", ru: "Локальный авторитет" }, desc: { fr: "Cohérence locale, réputation et signaux externes renforcent la pertinence.", en: "Local consistency, reputation and external signals reinforce relevance.", vi: "Tính nhất quán địa phương, uy tín và tín hiệu bên ngoài củng cố mức độ liên quan.", ar: "الاتساق المحلي والسمعة والإشارات الخارجية تعزز الصلة.", ru: "Локальная согласованность, репутация и внешние сигналы усиливают релевантность." } },
      { num: "04", title: { fr: "Pilotage & reporting", en: "Monitoring & reporting", vi: "Theo dõi & báo cáo", ar: "المتابعة والتقارير", ru: "Мониторинг и отчётность" }, desc: { fr: "Suivi des requêtes, zones et signaux utiles avec reporting clair.", en: "Track relevant searches, areas and signals with clear reporting.", vi: "Theo dõi truy vấn, khu vực và tín hiệu với báo cáo rõ ràng.", ar: "متابعة الاستعلامات والمناطق والإشارات مع تقارير واضحة.", ru: "Отслеживание запросов, зон и сигналов с понятной отчётностью." } },
    ],
    metrics: [
      { metric: "990 €", label: { fr: "à partir de / an", en: "starting / year", vi: "từ / năm", ar: "ابتداءً من / سنة", ru: "от / год" }, desc: { fr: "Le tarif dépend du périmètre réel après audit.", en: "Pricing depends on the actual scope after audit.", vi: "Giá phụ thuộc phạm vi thực tế sau kiểm toán.", ar: "يعتمد السعر على النطاق الفعلي بعد التدقيق.", ru: "Цена зависит от фактического объёма после аудита." } },
      { metric: "Top 3", label: { fr: "objectif", en: "objective", vi: "mục tiêu", ar: "الهدف", ru: "цель" }, desc: { fr: "Travailler vers le Top 3 sur les requêtes retenues.", en: "Top 3 target on selected searches, backed by a refund guarantee when the agreed conditions are met.", vi: "Hướng tới Top 3 cho các truy vấn đã chọn, kèm bảo đảm hoàn tiền theo điều kiện đã thỏa thuận.", ar: "استهداف Top 3 للاستعلامات المحددة مع ضمان استرداد المبلغ عند استيفاء الشروط المتفق عليها.", ru: "Выход в Top 3 по выбранным запросам с гарантией возврата при соблюдении согласованных условий." } },
      { metric: "100%", label: { fr: "sur mesure", en: "tailored", vi: "tùy chỉnh", ar: "مخصص", ru: "индивидуально" }, desc: { fr: "Zone, concurrence et état initial déterminent le plan d'action.", en: "Area, competition and starting state shape the action plan.", vi: "Khu vực, cạnh tranh và trạng thái ban đầu xác định kế hoạch.", ar: "تحدد المنطقة والمنافسة والحالة الأولية خطة العمل.", ru: "Зона, конкуренция и исходное состояние определяют план действий." } },
    ],
    serviceFaqs: [
      { q: { fr: "Le Top 3 est-il garanti ?", en: "Is Top 3 guaranteed?", vi: "Top 3 có được đảm bảo không?", ar: "هل Top 3 مضمون؟", ru: "Гарантируется ли Top 3?" }, a: { fr: "Oui, dans le cadre de la garantie. Nous définissons au diagnostic les requêtes, zones, critères d’éligibilité et délai cible. Si les conditions de la garantie sont respectées sans atteindre le Top 3 prévu, le montant éligible est remboursé selon les conditions contractuelles.", en: "Yes, within the guarantee framework. At diagnosis we define the target searches, areas, eligibility criteria and target timeframe. If the guarantee conditions are met without reaching the agreed Top 3, the eligible amount is refunded under the contractual terms.", vi: "Có, trong phạm vi bảo đảm. Khi chẩn đoán, chúng tôi xác định truy vấn, khu vực, tiêu chí đủ điều kiện và thời hạn mục tiêu. Nếu đáp ứng điều kiện bảo đảm mà vẫn không đạt Top 3 đã thỏa thuận, khoản tiền đủ điều kiện sẽ được hoàn theo điều khoản hợp đồng.", ar: "نعم، ضمن إطار الضمان. نحدد عند التشخيص الاستعلامات والمناطق ومعايير الأهلية والمدة المستهدفة. إذا استوفيت شروط الضمان دون الوصول إلى Top 3 المتفق عليه، يتم رد المبلغ المؤهل وفق الشروط التعاقدية.", ru: "Да, в рамках гарантии. На этапе диагностики мы определяем запросы, зоны, критерии участия и целевой срок. Если условия гарантии соблюдены, но согласованный Top 3 не достигнут, соответствующая сумма возвращается по условиям договора." } },
      { q: { fr: "Pourquoi commencer à 990 € / an ?", en: "Why start at €990 / year?", vi: "Vì sao từ 990 € / năm?", ar: "لماذا يبدأ السعر من 990 € سنويًا؟", ru: "Почему от 990 € в год?" }, a: { fr: "Parce que le service inclut audit, optimisation et suivi. Les environnements concurrentiels peuvent nécessiter un périmètre supérieur.", en: "Because the service includes audit, optimisation and monitoring. Competitive markets may require a broader scope.", vi: "Vì dịch vụ bao gồm kiểm toán, tối ưu và theo dõi. Thị trường cạnh tranh có thể cần phạm vi rộng hơn.", ar: "لأن الخدمة تشمل التدقيق والتحسين والمتابعة. الأسواق شديدة التنافس قد تتطلب نطاقًا أوسع.", ru: "Потому что услуга включает аудит, оптимизацию и мониторинг. В конкурентных рынках объём может быть больше." } },
    ],

    plans: [
      {
        name: { fr: "Maps Top 3", en: "Maps Top 3", vi: "Maps Top 3" },
        eur: 990,
        period: "year",
        features: [
          { fr: "Audit sémantique & concurrentiel géolocalisé", en: "Geolocated semantic & competitive audit", vi: "Kiểm toán ngữ nghĩa & đối thủ cạnh tranh theo vị trí" },
          { fr: "Optimisation intégrale de la fiche Google Business Profile", en: "Comprehensive Google Business Profile optimization", vi: "Tối ưu hóa toàn diện hồ sơ Google Business" },
          { fr: "Engagement contractuel « Top 3 ou Remboursé »", en: "Contractual commitment « Top 3 or Refunded »", vi: "Cam kết hợp đồng « Top 3 hoặc Hoàn tiền »" },
          { fr: "Stratégie de collecte d'avis clients 5 étoiles", en: "5-star customer reviews collection strategy", vi: "Chiến lược thu thập đánh giá 5 sao từ khách hàng" },
          { fr: "Netlinking local & citations NAP (Nom, Adresse, Tél)", en: "Local netlinking & NAP citations", vi: "Xây dựng liên kết địa phương & đồng bộ NAP" },
          { fr: "Rapports mensuels de visibilité & d'appels générés", en: "Monthly visibility & generated calls reports", vi: "Báo cáo hiển thị hàng tháng & lượng cuộc gọi phát sinh" },
        ],
      },
    ],
  },
  {
    id: "social",
    num: "05",
    title: { fr: "Social Media", en: "Social Media", vi: "Mạng xã hội", ar: "وسائل التواصل الاجتماعي", ru: "Социальные сети" },
    short: { fr: "Stratégie, création et animation des réseaux.", en: "Strategy, creation and community management.", vi: "Chiến lược, sáng tạo và quản lý mạng xã hội.", ar: "استراتيجية وإنشاء وإدارة الشبكات الاجتماعية.", ru: "Стратегия, создание и ведение социальных сетей." },
    description: { fr: "Calendrier éditorial, direction artistique, création de contenus percutants et animation Instagram, TikTok, LinkedIn & Facebook.", en: "Editorial calendar, content creation and management of Instagram, Facebook, LinkedIn and TikTok.", vi: "Lịch biên tập, sáng tạo nội dung và quản lý Instagram, Facebook, LinkedIn, TikTok." },
    fromEur: 299,
    fromPeriod: "month",
    highlights: [
      { fr: "Instagram, TikTok, LinkedIn & Facebook", en: "Instagram, TikTok, LinkedIn & Facebook", vi: "Instagram, TikTok, LinkedIn & Facebook", ar: "Instagram و TikTok و LinkedIn و Facebook", ru: "Instagram, TikTok, LinkedIn и Facebook" },
      { fr: "Calendrier éditorial sur-mesure", en: "Bespoke editorial calendar", vi: "Lịch biên tập cá nhân hóa", ar: "تقويم تحريري مخصص", ru: "Индивидуальный контент-план" },
      { fr: "Production visuelle & montage dynamique", en: "Visual production & dynamic video editing", vi: "Sản xuất hình ảnh & dựng video cuốn hút", ar: "إنتاج بصري ومونتاج فيديو احترافي", ru: "Визуальный продакшн и динамичный монтаж" },
    ],
    plans: [
      {
        name: { fr: "Présence Essentielle", en: "Essential Presence", vi: "Hiện diện Cơ bản" },
        eur: 299,
        period: "month",
        features: [
          { fr: "1 réseau social au choix (Instagram ou LinkedIn ou TikTok)", en: "1 social network of choice (Instagram, LinkedIn or TikTok)", vi: "1 mạng xã hội tùy chọn (Instagram, LinkedIn hoặc TikTok)" },
          { fr: "8 publications soignées / mois (visuels HD + rédaction)", en: "8 curated posts / month (HD visuals + copywriting)", vi: "8 bài đăng chất lượng cao / tháng (hình ảnh HD + nội dung)" },
          { fr: "Direction artistique & charte graphique de feed", en: "Art direction & cohesive feed styling", vi: "Định hướng nghệ thuật & phong cách feed đồng bộ" },
          { fr: "Programmation automatique aux heures de pointe", en: "Automated peak-hours scheduling", vi: "Lên lịch đăng bài tự động vào khung giờ vàng" },
          { fr: "Modération et réponses aux commentaires clés", en: "Moderation and key comments replies", vi: "Kiểm duyệt và phản hồi các bình luận chính" },
        ],
      },
      {
        name: { fr: "Croissance Active", en: "Active Growth", vi: "Tăng trưởng Chủ động" },
        eur: 499,
        period: "month",
        popular: true,
        features: [
          { fr: "2 réseaux sociaux (ex. Instagram + TikTok ou LinkedIn)", en: "2 social networks (e.g. Instagram + TikTok or LinkedIn)", vi: "2 mạng xã hội (VD: Instagram + TikTok hoặc LinkedIn)" },
          { fr: "20 publications / mois (carrousels, photos & reels)", en: "20 posts / month (carousels, photos & reels)", vi: "20 bài đăng / tháng (carousel, ảnh & reels)" },
          { fr: "Montage de formats courts (Reels / TikTok / Shorts)", en: "Short-form video editing (Reels / TikTok / Shorts)", vi: "Dựng video ngắn (Reels / TikTok / Shorts)" },
          { fr: "Stories interactives régulières (sondages, actus, coulisses)", en: "Regular interactive stories (polls, news, behind the scenes)", vi: "Stories tương tác thường xuyên (thăm dò, tin tức, hậu trường)" },
          { fr: "Modération active & animation de communauté", en: "Active community moderation & engagement", vi: "Kiểm duyệt chủ động & tương tác cộng đồng liên tục" },
          { fr: "Rapport d'analyse mensuel & recommandations stratégiques", en: "Monthly performance report & strategic insights", vi: "Báo cáo hiệu suất hàng tháng & đề xuất chiến lược" },
        ],
      },
      {
        name: { fr: "Domination Sociale", en: "Social Domination", vi: "Phủ sóng Mạng xã hội" },
        eur: 699,
        period: "month",
        features: [
          { fr: "3 réseaux sociaux complets (Instagram + TikTok + LinkedIn/FB)", en: "3 full social networks (Instagram + TikTok + LinkedIn/FB)", vi: "3 mạng xã hội toàn diện (Instagram + TikTok + LinkedIn/FB)" },
          { fr: "30 publications premium / mois (rythme quotidien)", en: "30 premium posts / month (daily cadence)", vi: "30 bài đăng cao cấp / tháng (mỗi ngày 1 bài)" },
          { fr: "Création, scriptwriting & montage Reels cinéma 4K", en: "Creation, scriptwriting & 4K cinematic Reels editing", vi: "Biên kịch, sáng tạo & dựng Reels chuẩn điện ảnh 4K" },
          { fr: "Stories quotidiennes & temps forts événementiels", en: "Daily stories & event highlights coverage", vi: "Stories hàng ngày & đưa tin sự kiện nổi bật" },
          { fr: "Modération et engagement proactifs 6j/7", en: "Proactive moderation & engagement 6 days a week", vi: "Kiểm duyệt & tương tác chủ động 6 ngày/tuần" },
          { fr: "Veille concurrentielle & reporting analytique approfondi", en: "Competitive benchmark & comprehensive analytical report", vi: "Theo dõi đối thủ & báo cáo phân tích chuyên sâu" },
        ],
      },
    ],
    steps: [
      { num: "01", title: { fr: "Positionnement", en: "Positioning", vi: "Định vị", ar: "التموضع", ru: "Позиционирование" }, desc: { fr: "Objectifs, audiences, ton, piliers éditoriaux et direction visuelle.", en: "Goals, audiences, tone, content pillars and visual direction.", vi: "Mục tiêu, đối tượng, giọng điệu, trụ cột nội dung và hướng hình ảnh.", ar: "الأهداف والجمهور والنبرة ومحاور المحتوى والتوجه البصري.", ru: "Цели, аудитории, тон, контентные направления и визуальная подача." } },
      { num: "02", title: { fr: "Production", en: "Production", vi: "Sản xuất", ar: "الإنتاج", ru: "Производство" }, desc: { fr: "Création des publications, carrousels, stories et formats courts selon la formule.", en: "Creation of posts, carousels, stories and short formats according to the plan.", vi: "Tạo bài đăng, carousel, story và nội dung ngắn theo gói.", ar: "إنتاج المنشورات والكاروُسيل والقصص والمقاطع القصيرة حسب الباقة.", ru: "Создание постов, каруселей, stories и коротких форматов по пакету." } },
      { num: "03", title: { fr: "Animation", en: "Community management", vi: "Quản lý cộng đồng", ar: "إدارة المجتمع", ru: "Комьюнити-менеджмент" }, desc: { fr: "Modération et réponses selon le niveau de délégation choisi.", en: "Moderation and replies according to the selected delegation level.", vi: "Kiểm duyệt và phản hồi theo mức độ ủy quyền.", ar: "إدارة التعليقات والردود وفق مستوى التفويض المختار.", ru: "Модерация и ответы в соответствии с выбранным уровнем делегирования." } },
      { num: "04", title: { fr: "Pilotage", en: "Reporting", vi: "Báo cáo", ar: "التقارير", ru: "Отчётность" }, desc: { fr: "Lecture des signaux, recommandations et ajustements éditoriaux.", en: "Review signals, recommendations and editorial adjustments.", vi: "Phân tích tín hiệu, đề xuất và điều chỉnh nội dung.", ar: "قراءة المؤشرات والتوصيات والتعديلات التحريرية.", ru: "Анализ сигналов, рекомендации и редакционные корректировки." } },
    ],
    serviceFaqs: [
      { q: { fr: "Que comprend chaque niveau ?", en: "What does each level include?", vi: "Mỗi cấp độ bao gồm gì?", ar: "ماذا يتضمن كل مستوى؟", ru: "Что входит в каждый уровень?" }, a: { fr: "Chaque formule définit le nombre de réseaux, de publications, de stories et le niveau de modération. Les trois niveaux augmentent progressivement la délégation.", en: "Each plan defines networks, posts, stories and moderation level. The three levels progressively increase delegation.", vi: "Mỗi gói xác định số mạng, bài đăng, story và mức độ quản lý. Ba cấp độ tăng dần khả năng ủy quyền.", ar: "كل باقة تحدد عدد الشبكات والمنشورات والقصص ومستوى الإدارة. المستويات الثلاثة تزيد التفويض تدريجيًا.", ru: "Каждый пакет задаёт количество сетей, публикаций, stories и уровень модерации. Три уровня постепенно увеличивают делегирование." } },
      { q: { fr: "Les tournages sont-ils inclus ?", en: "Are shoots included?", vi: "Quay chụp có bao gồm không?", ar: "هل التصوير مشمول؟", ru: "Включены ли съёмки?" }, a: { fr: "Non. Shooting photo/vidéo, déplacement, studio, mannequins et production sur site font l'objet d'un devis séparé.", en: "No. Photo/video shoots, travel, studio, models and on-site production are quoted separately.", vi: "Không. Quay chụp, di chuyển, studio, người mẫu và sản xuất tại chỗ báo giá riêng.", ar: "لا. يتم تسعير التصوير والتنقل والاستوديو والموديلات والإنتاج الميداني بشكل منفصل.", ru: "Нет. Фото/видеосъёмка, выезды, студия, модели и производство на месте считаются отдельно." } },
    ],
  },
  {
    id: "maintenance",
    num: "06",
    title: { fr: "WebCare & Maintenance", en: "WebCare & Maintenance", vi: "WebCare & Bảo trì" },
    short: { fr: "Corrections, évolutions et suivi du site.", en: "Fixes, updates and site monitoring.", vi: "Sửa lỗi, cập nhật và giám sát site." },
    description: { fr: "Maintenance technique, mises à jour de sécurité et petites évolutions pour garder votre site fiable.", en: "Technical maintenance, security updates and small evolutions to keep your site reliable.", vi: "Bảo trì kỹ thuật, cập nhật bảo mật và điều chỉnh nhỏ." },
    fromEur: 29,
    fromPeriod: "month",
    highlights: [
      { fr: "Mises à jour sécurité", en: "Security updates", vi: "Cập nhật bảo mật" },
      { fr: "Support prioritaire", en: "Priority support", vi: "Hỗ trợ ưu tiên" },
    ],
    plans: [
      {
        name: { fr: "Essentiel", en: "Essential", vi: "Cơ bản" },
        eur: 29,
        period: "month",
        features: [
          { fr: "4 modifications / mois", en: "4 changes / month", vi: "4 chỉnh sửa / tháng" },
          { fr: "Corrections de contenu et visuels", en: "Content and visual fixes", vi: "Sửa nội dung và hình ảnh" },
          { fr: "Interventions techniques courantes", en: "Routine technical interventions", vi: "Can thiệp kỹ thuật thường xuyên" },
          { fr: "Suivi standard", en: "Standard support", vi: "Hỗ trợ tiêu chuẩn" },
        ],
      },
      {
        name: { fr: "Business", en: "Business", vi: "Business" },
        eur: 49,
        period: "month",
        popular: true,
        features: [
          { fr: "10 modifications / mois", en: "10 changes / month", vi: "10 chỉnh sửa / tháng" },
          { fr: "Corrections de contenu, visuels et sections", en: "Content, visual and section updates", vi: "Chỉnh sửa nội dung, hình ảnh và phần" },
          { fr: "Interventions techniques courantes", en: "Routine technical interventions", vi: "Can thiệp kỹ thuật thường xuyên" },
          { fr: "Priorité de traitement", en: "Priority handling", vi: "Ưu tiên xử lý" },
          { fr: "Conseils d'évolution courante", en: "Routine improvement advice", vi: "Tư vấn cải tiến thường xuyên" },
        ],
      },
      {
        name: { fr: "Unlimited", en: "Unlimited", vi: "Unlimited" },
        eur: 99,
        period: "month",
        features: [
          { fr: "Modifications courantes illimitées dans le périmètre du site", en: "Unlimited routine changes within the site scope", vi: "Chỉnh sửa thường xuyên không giới hạn trong phạm vi website" },
          { fr: "Corrections de contenu, visuels et sections", en: "Content, visual and section updates", vi: "Chỉnh sửa nội dung, hình ảnh và phần" },
          { fr: "Suivi technique prioritaire", en: "Priority technical support", vi: "Hỗ trợ kỹ thuật ưu tiên" },
          { fr: "Petites évolutions incluses", en: "Small improvements included", vi: "Bao gồm các cải tiến nhỏ" },
          { fr: "Refontes et développements spécifiques sur devis", en: "Redesigns and major development quoted separately", vi: "Thiết kế lại và phát triển lớn báo giá riêng" },
        ],
      },
    ],
  },
  {
    id: "robotics",
    num: "07",
    title: { fr: "Robotique de service & IA", en: "Service Robotics & AI", vi: "Robot dịch vụ & AI", ar: "الروبوتات الخدمية والذكاء الاصطناعي", ru: "Сервисная робототехника и ИИ" },
    short: { fr: "Robots Korben pour automatiser, accueillir, livrer et nettoyer.", en: "Korben robots to automate, welcome, deliver and clean.", vi: "Robot Korben để tự động hóa, đón tiếp, giao hàng và vệ sinh.", ar: "روبوتات Korben للأتمتة والاستقبال والتوصيل والتنظيف.", ru: "Роботы Korben для автоматизации, приёма, доставки и уборки." },
    description: { fr: "Une gamme professionnelle de robots autonomes Korben pour l'hôtellerie, la restauration, le retail, la santé, la logistique et les entreprises. XR Agency vous aide à identifier le modèle, cadrer le déploiement et générer les demandes de démonstration.", en: "A professional range of Korben autonomous robots for hospitality, catering, retail, healthcare, logistics and business. XR Agency helps identify the model, scope deployment and generate demo requests.", vi: "Danh mục robot tự hành Korben cho khách sạn, nhà hàng, bán lẻ, y tế, logistics và doanh nghiệp. XR Agency giúp xác định mẫu, triển khai và tạo yêu cầu demo.", ar: "مجموعة احترافية من روبوتات Korben المستقلة للفنادق والمطاعم والتجزئة والصحة واللوجستيات والشركات.", ru: "Профессиональная линейка автономных роботов Korben для отелей, ресторанов, ритейла, медицины, логистики и бизнеса." },
    fromEur: 499,
    fromPeriod: "month",
    highlights: [
      { fr: "Location à partir de 499 €/mois", en: "Leasing from €499/month", vi: "Thuê từ 499 €/tháng", ar: "إيجار ابتداءً من 499€/شهر", ru: "Аренда от 499 €/мес." },
      { fr: "Achat annoncé : 8 000–21 000 € HT", en: "Published purchase range: €8,000–€21,000 excl. tax", vi: "Giá mua công bố: 8.000–21.000 € chưa VAT", ar: "شراء معلن: 8,000–21,000 € قبل الضريبة", ru: "Заявленный диапазон покупки: 8 000–21 000 € без НДС" },
      { fr: "SAV français & normes CE", en: "French support & CE standards", vi: "Hỗ trợ Pháp & tiêu chuẩn CE", ar: "دعم فرنسي ومعايير CE", ru: "Французский сервис и стандарты CE" },
    ],
    plans: [
      { name: { fr: "Location sur mesure", en: "Tailored leasing", vi: "Thuê theo nhu cầu" }, eur: 499, period: "month", popular: true, features: [
        { fr: "Robot adapté au scénario", en: "Robot matched to the use case", vi: "Robot phù hợp nhu cầu" },
        { fr: "Location à partir de 499 €/mois", en: "Leasing from €499/month", vi: "Thuê từ 499 €/tháng" },
        { fr: "Maintenance et mises à jour incluses selon offre", en: "Maintenance and updates included according to offer", vi: "Bảo trì và cập nhật theo gói" },
        { fr: "Accompagnement au déploiement", en: "Deployment support", vi: "Hỗ trợ triển khai" },
      ] },
      { name: { fr: "Achat professionnel", en: "Professional purchase", vi: "Mua chuyên nghiệp" }, eur: 8000, period: "once", features: [
        { fr: "Gamme annoncée de 8 000 à 21 000 € HT selon modèle", en: "Published range €8,000–€21,000 excl. tax depending on model", vi: "8.000–21.000 € chưa VAT tùy mẫu" },
        { fr: "Configuration et personnalisation selon projet", en: "Configuration and customisation by project", vi: "Cấu hình và tùy chỉnh theo dự án" },
        { fr: "Déploiement et accompagnement sur devis", en: "Deployment and support quoted by project", vi: "Triển khai và hỗ trợ báo giá riêng" },
      ] },
      { name: { fr: "Démonstration / événement", en: "Demo / event", vi: "Demo / sự kiện" }, eur: 250, period: "month", features: [
        { fr: "Location événementielle annoncée à partir de 250 €", en: "Event rental published from €250", vi: "Thuê sự kiện công bố từ 250 €" },
        { fr: "Robot adapté à l'animation ou démonstration", en: "Robot matched to demo or activation", vi: "Robot phù hợp demo / activation" },
        { fr: "Modalités à confirmer selon durée et lieu", en: "Terms confirmed by duration and location", vi: "Xác nhận theo thời lượng và địa điểm" },
      ] },
    ],
    steps: [
      { num: "01", title: { fr: "Diagnostic", en: "Diagnosis", vi: "Chẩn đoán" }, desc: { fr: "Nous identifions les tâches répétitives, les flux et les contraintes du site.", en: "We identify repetitive tasks, flows and site constraints.", vi: "Xác định tác vụ lặp lại, luồng vận hành và giới hạn mặt bằng." } },
      { num: "02", title: { fr: "Sélection", en: "Selection", vi: "Lựa chọn" }, desc: { fr: "Accueil, livraison, nettoyage, logistique ou humanoïde : nous orientons vers la famille adaptée.", en: "Welcome, delivery, cleaning, logistics or humanoid: we match the right family.", vi: "Đón tiếp, giao hàng, vệ sinh, logistics hoặc humanoid: chọn đúng nhóm robot." } },
      { num: "03", title: { fr: "Déploiement", en: "Deployment", vi: "Triển khai" }, desc: { fr: "Cartographie, configuration, contenus et intégration selon le scénario.", en: "Mapping, configuration, content and integration by scenario.", vi: "Lập bản đồ, cấu hình, nội dung và tích hợp theo kịch bản." } },
      { num: "04", title: { fr: "Pilotage", en: "Operations", vi: "Vận hành" }, desc: { fr: "Suivi de l'usage, optimisation et accompagnement commercial.", en: "Usage monitoring, optimisation and commercial support.", vi: "Theo dõi sử dụng, tối ưu và hỗ trợ thương mại." } },
    ],
    metrics: [
      { metric: "499 €", label: { fr: "à partir de / mois", en: "starting / month", vi: "từ / tháng" }, desc: { fr: "Location sur mesure annoncée par Korben.", en: "Tailored leasing published by Korben.", vi: "Mức thuê theo nhu cầu do Korben công bố." } },
      { metric: "8–21K €", label: { fr: "achat HT", en: "purchase excl. tax", vi: "mua chưa VAT" }, desc: { fr: "Fourchette d'achat publiée, selon le modèle.", en: "Published purchase range depending on model.", vi: "Khoảng giá mua công bố tùy mẫu." } },
      { metric: "4", label: { fr: "familles", en: "families", vi: "nhóm" }, desc: { fr: "Accueil, livraison, nettoyage, humanoïdes / polyvalents.", en: "Welcome, delivery, cleaning, humanoid / versatile.", vi: "Đón tiếp, giao hàng, vệ sinh, humanoid / đa năng." } },
    ],
    serviceFaqs: [
      { q: { fr: "Quel est le prix d'un robot Korben ?", en: "How much does a Korben robot cost?", vi: "Robot Korben giá bao nhiêu?" }, a: { fr: "Korben indique une fourchette d'achat de 8 000 à 21 000 € HT selon le modèle. La location sur mesure commence à 499 €/mois. Les tarifs exacts dépendent du robot et du projet.", en: "Korben publishes a purchase range of €8,000–€21,000 excl. tax depending on model. Tailored leasing starts at €499/month. Exact pricing depends on robot and project.", vi: "Korben công bố giá mua 8.000–21.000 € chưa VAT tùy mẫu. Thuê theo nhu cầu từ 499 €/tháng. Giá chính xác phụ thuộc robot và dự án." } },
      { q: { fr: "Le robot remplace-t-il les équipes ?", en: "Does the robot replace staff?", vi: "Robot có thay thế nhân viên không?" }, a: { fr: "Korben présente ses robots comme des assistants destinés à prendre en charge les tâches répétitives et à laisser les équipes se concentrer sur les missions à valeur ajoutée.", en: "Korben presents its robots as assistants handling repetitive tasks so teams can focus on higher-value work.", vi: "Korben định vị robot như trợ lý xử lý tác vụ lặp lại để nhân viên tập trung vào công việc có giá trị cao hơn." } },
      { q: { fr: "Peut-on tester avant de s'engager ?", en: "Can we test before committing?", vi: "Có thể thử trước khi quyết định không?" }, a: { fr: "Oui. Korben propose de tester un robot adapté au besoin pendant quelques jours, selon disponibilité et modalités.", en: "Yes. Korben offers short trials of a robot matched to the use case, subject to availability and terms.", vi: "Có. Korben đề xuất thử robot phù hợp trong vài ngày tùy khả năng cung cấp và điều kiện." } },
    ],
  },
];