export const SERVICES_PART2 = [
  {
    id: "maps",
    num: "04",
    title: { fr: "Google Maps Top 3", en: "Google Maps Top 3", vi: "Google Maps Top 3", ar: "Google Maps Top 3", ru: "Google Maps Top 3" },
    short: { fr: "Visibilité locale et positionnement carte.", en: "Local visibility and map ranking.", vi: "Hiển thị địa phương và xếp hạng bản đồ.", ar: "ظهور محلي وتحسين الحضور على الخرائط.", ru: "Локальная видимость и присутствие на карте." },
    description: { fr: "Optimisation de votre fiche Google Business Profile et stratégie locale avec un engagement clair : viser le Top 3 sur les requêtes et zones définies au diagnostic, avec une garantie "Top 3 ou remboursé" lorsque les critères, délais et conditions de la garantie sont réunis.", en: "Google Business Profile optimisation and local strategy with a clear commitment: target Top 3 visibility for the searches and areas defined at diagnosis, with a "Top 3 or money back" guarantee when the agreed criteria, timeframe and guarantee conditions are met.", vi: "Tối ưu Google Business Profile và chiến lược địa phương với cam kết rõ ràng: hướng tới Top 3 theo truy vấn và khu vực được xác định khi chẩn đoán, kèm bảo đảm "Top 3 hoặc hoàn tiền" khi đáp ứng các tiêu chí, thời hạn và điều kiện đã thỏa thuận." },
    fromEur: 990,
    fromPeriod: "year",
    highlights: [
      { fr: "Fiche Google optimisée", en: "Optimised Google profile", vi: "Hồ sơ Google tối ưu", ar: "ملف Google محسّن", ru: "Оптимизированный профиль Google" },
      { fr: "Suivi de positionnement", en: "Ranking monitoring", vi: "Theo dõi thứ hạng", ar: "متابعة الظهور والترتيب", ru: "Мониторинг позиций" },
      { fr: "Stratégie locale sur mesure", en: "Tailored local strategy", vi: "Chiến lược địa phương theo nhu cầu", ar: "استراتيجية محلية مخصصة", ru: "Индивидуальная локальная стратегия" },
    ],
    steps: [
      { num: "01", title: { fr: "Audit & benchmark", en: "Audit & benchmark", vi: "Kiểm toán & benchmark", ar: "التدقيق والمقارنة", ru: "Аудит и benchmark" }, desc: { fr: "Analyse de la fiche, des concurrents et des requêtes locales qui comptent.", en: "Analysis of the profile, competitors and relevant local searches.", vi: "Phân tích hồ sơ, đối thủ và các truy vấn địa phương quan trọng.", ar: "تحليل الملف والمنافسين وعمليات البحث المحلية المهمة.", ru: "Анализ профиля, конкурентов и целевых локальных запросов." } },
      { num: "02", title: { fr: "Optimisation GBP", en: "GBP optimisation", vi: "Tối ưu GBP", ar: "تحسين ملف GBP", ru: "Оптимизация GBP" }, desc: { fr: "Catégories, services, informations, contenus et signaux du profil sont retravaillés.", en: "Categories, services, information, content and profile signals are refined.", vi: "Danh mục, dịch vụ, thông tin, nội dung và tín hiệu hồ sơ được tối ưu.", ar: "إعادة ضبط الفئات والخدمات والمعلومات والمحتوى وإشارات الملف.", ru: "Категории, услуги, информация, контент и сигналы профиля дорабатываются." } },
      { num: "03", title: { fr: "Autorité locale", en: "Local authority", vi: "Uy tín địa phương", ar: "السلطة المحلية", ru: "Локальный авторитет" }, desc: { fr: "Cohérence locale, réputation et signaux externes renforcent la pertinence.", en: "Local consistency, reputation and external signals reinforce relevance.", vi: "Tính nhất quán địa phương, uy tín và tín hiệu bên ngoài củng cố mức độ liên quan.", ar: "الاتساق المحلي والسمعة والإشارات الخارجية تعزز الصلة.", ru: "Локальная согласованность, репутация и внешние сигналы усиливают релевантность." } },
      { num: "04", title: { fr: "Pilotage & reporting", en: "Monitoring & reporting", vi: "Theo dõi & báo cáo", ar: "المتابعة والتقارير", ru: "Мониторинг и отчётность" }, desc: { fr: "Suivi des requêtes, zones et signaux utiles avec reporting clair.", en: "Track relevant searches, areas and signals with clear reporting.", vi: "Theo dõi truy vấn, khu vực và tín hiệu với báo cáo rõ ràng.", ar: "متابعة الاستعلامات والمناطق والإشارات مع تقارير واضحة.", ru: "Отслеживание запросов, зон и сигналов с понятной отчётностью." } },
    ],
    metrics: [
      { metric: "990 €", label: { fr: "à partir de / an", en: "starting / year", vi: "từ / năm", ar: "ابتداءً من / سنة", ru: "от / год" }, desc: { fr: "Le tarif dépend du périmètre réel après audit.", en: "Pricing depends on the actual scope after audit.", vi: "Giá phụ thuộc phạm vi thực tế sau kiểm toán.", ar: "يعتمد السعر على النطاق الفعلي بعد التدقيق.", ru: "Цена зависит от фактического объёма после аудита." } },
      { metric: "Top 3", label: { fr: "objectif", en: "objective", vi: "mục tiêu", ar: "الهدف", ru: "цель" }, desc: { fr: "Travailler vers le Top 3 sur les requêtes retenues.", en: "Top 3 target on selected searches, backed by a refund guarantee when the agreed conditions are met.", vi: "Hướng tới Top 3 cho các truy vấn đã chọn, kèm bảo đảm hoàn tiền theo điều kiện đã thỏa thuận.", ar: "استهداف Top 3 للاستعلامات المحددة مع ضمان استرداد المبلغ عند استيفاء الشروط المتفق عليها.", ru: "Выход в Top 3 по выбранным запросам с гарантией возврата при соблюдении согласованных условий." } },
      { metric: "100%", label: { fr: "sur mesure", en: "tailored", vi: "tùy chỉnh", ar: "مخصص", ru: "индивидуально" }, desc: { fr: "Zone, concurrence et état initial déterminent le plan d'action.", en: "Area, competition and starting state shape the action plan.", vi: "Khu vực, cạnh tranh và trạng thái ban đầu xác định kế hoạch.", ar: "تحدد المنطقة والمنافسة والحالة الأولية خطة العمل.", ru: "Зона, конкуренция и исходное состояние определяют план действий." } },
    ],
    serviceFaqs: [
      { q: { fr: "Le Top 3 est-il garanti ?", en: "Is Top 3 guaranteed?", vi: "Top 3 có được đảm bảo không?", ar: "هل Top 3 مضمون؟", ru: "Гарантируется ли Top 3?" }, a: { fr: "Oui, dans le cadre de la garantie. Nous définissons au diagnostic les requêtes, zones, critères d’éligibilité et délai cible. Si les conditions de la garantie sont respectées sans atteindre le Top 3 prévu, le montant éligible est remboursé selon les conditions contractuelles.", en: "Yes, within the guarantee framework. At diagnosis we define the target searches, areas, eligibility criteria and target timeframe. If the guarantee conditions are met without reaching the agreed Top 3, the eligible amount is refunded under the contractual terms.", vi: "Có, trong phạm vi bảo đảm. Khi chẩn đoán, chúng tôi xác định truy vấn, khu vực, tiêu chí đủ điều kiện và thời hạn mục tiêu. Nếu đáp ứng điều kiện bảo đảm mà vẫn không đạt Top 3 đã thỏa thuận, khoản tiền đủ điều kiện sẽ được hoàn theo điều khoản hợp đồng.", ar: "نعم، ضمن إطار الضمان. نحدد عند التشخيص الاستعلامات والمناطق ومعايير الأهلية والمدة المستهدفة. إذا استوفيت شروط الضمان دون الوصول إلى Top 3 المتفق عليه، يتم رد المبلغ المؤهل وفق الشروط التعاقدية.", ru: "Да, в рамках гарантии. На этапе диагностики мы определяем запросы, зоны, критерии участия и целевой срок. Если условия гарантии соблюдены, но согласованный Top 3 не достигнут, соответствующая сумма возвращается по условиям договора." } },
      { q: { fr: "Pourquoi commencer à 990 € / an ?", en: "Why start at €990 / year?", vi: "Vì sao từ 990 € / năm?", ar: "لماذا يبدأ السعر من 990 € سنويًا؟", ru: "Почему от 990 € в год?" }, a: { fr: "Parce que le service inclut audit, optimisation et suivi. Les environnements concurrentiels peuvent nécessiter un périmètre supérieur.", en: "Because the service includes audit, optimisation and monitoring. Competitive markets may require a broader scope.", vi: "Vì dịch vụ bao gồm kiểm toán, tối ưu và theo dõi. Thị trường cạnh tranh có thể cần phạm vi rộng hơn.", ar: "لأن الخدمة تشمل التدقيق والتحسين والمتابعة. الأسواق شديدة التنافس قد تتطلب نطاقًا أوسع.", ru: "Потому что услуга включает аудит, оптимизацию и мониторинг. В конкурентных рынках объём может быть больше." } },
    ],

    plans: [
      {
        name: { fr: "Maps Top 3", en: "Maps Top 3", vi: "Maps Top 3" },
        eur: 990,
        period: "year",
        features: [
          { fr: "Audit local complet", en: "Full local audit", vi: "Kiểm toán địa phương" },
          { fr: "Optimisation fiche GBP + garantie Top 3", en: "GBP profile optimisation", vi: "Tối ưu hồ sơ GBP" },
          { fr: "Suivi mensuel", en: "Monthly monitoring", vi: "Theo dõi hàng tháng" },
        ],
      },
    ],
  },
  {
    id: "social",
    num: "05",
    title: { fr: "Social Media & Contenu", en: "Social Media & Content", vi: "Mạng xã hội & Nội dung", ar: "وسائل التواصل والمحتوى", ru: "Соцсети и контент" },
    short: { fr: "Stratégie, contenus et animation des réseaux.", en: "Strategy, content and community management.", vi: "Chiến lược, nội dung và quản lý cộng đồng.", ar: "استراتيجية ومحتوى وإدارة للمجتمعات الرقمية.", ru: "Стратегия, контент и управление социальными сетями." },
    description: { fr: "Calendrier éditorial, création de contenus et animation Instagram, Facebook, LinkedIn et TikTok.", en: "Editorial calendar, content creation and management of Instagram, Facebook, LinkedIn and TikTok.", vi: "Lịch biên tập, sáng tạo nội dung và quản lý Instagram, Facebook, LinkedIn, TikTok." },
    fromEur: 299,
    fromPeriod: "month",
    highlights: [
      { fr: "4 réseaux principaux", en: "4 main networks", vi: "4 mạng chính", ar: "4 شبكات رئيسية", ru: "4 основные сети" },
      { fr: "Calendrier éditorial", en: "Editorial calendar", vi: "Lịch biên tập", ar: "تقويم تحريري", ru: "Контент-план" },
      { fr: "Création + animation", en: "Creation + community management", vi: "Sáng tạo + quản lý cộng đồng", ar: "إنشاء المحتوى + إدارة المجتمع", ru: "Создание + комьюнити-менеджмент" },
    ],
    plans: [
      {
        name: { fr: "Présence Essentielle", en: "Essential Presence", vi: "Hiện diện Cơ bản" },
        eur: 299,
        period: "month",
        features: [
          { fr: "1 réseau social", en: "1 social network", vi: "1 mạng xã hội" },
          { fr: "8 publications / mois", en: "8 posts / month", vi: "8 bài đăng / tháng" },
          { fr: "Visuels + rédaction", en: "Visuals + copywriting", vi: "Hình ảnh + nội dung" },
          { fr: "Programmation des publications", en: "Post scheduling", vi: "Lên lịch đăng bài" },
          { fr: "Modération légère", en: "Light moderation", vi: "Kiểm duyệt cơ bản" },
        ],
      },
      {
        name: { fr: "Croissance Active", en: "Active Growth", vi: "Tăng trưởng Chủ động" },
        eur: 499,
        period: "month",
        popular: true,
        features: [
          { fr: "2 réseaux sociaux", en: "2 social networks", vi: "2 mạng xã hội" },
          { fr: "20 publications / mois", en: "20 posts / month", vi: "20 bài đăng / tháng" },
          { fr: "Visuels + copywriting", en: "Visuals + copywriting", vi: "Hình ảnh + copywriting" },
          { fr: "Stories / formats courts selon planning", en: "Stories / short formats according to schedule", vi: "Stories / định dạng ngắn theo lịch" },
          { fr: "Modération et réponses courantes", en: "Moderation and routine replies", vi: "Kiểm duyệt và trả lời thường xuyên" },
          { fr: "Reporting mensuel", en: "Monthly reporting", vi: "Báo cáo hàng tháng" },
        ],
      },
      {
        name: { fr: "Domination Sociale", en: "Social Domination", vi: "Phủ sóng Mạng xã hội" },
        eur: 699,
        period: "month",
        features: [
          { fr: "3 réseaux sociaux", en: "3 social networks", vi: "3 mạng xã hội" },
          { fr: "30 publications / mois", en: "30 posts / month", vi: "30 bài đăng / tháng" },
          { fr: "Création, rédaction et programmation", en: "Creation, copywriting and scheduling", vi: "Sáng tạo, viết và lên lịch" },
          { fr: "Stories / formats courts", en: "Stories / short formats", vi: "Stories / định dạng ngắn" },
          { fr: "Modération renforcée", en: "Enhanced moderation", vi: "Kiểm duyệt nâng cao" },
          { fr: "Veille + reporting mensuel", en: "Monitoring + monthly reporting", vi: "Theo dõi + báo cáo hàng tháng" },
        ],
      },
    ],
    steps: [
      { num: "01", title: { fr: "Positionnement", en: "Positioning", vi: "Định vị", ar: "التموضع", ru: "Позиционирование" }, desc: { fr: "Objectifs, audiences, ton, piliers éditoriaux et direction visuelle.", en: "Goals, audiences, tone, content pillars and visual direction.", vi: "Mục tiêu, đối tượng, giọng điệu, trụ cột nội dung và hướng hình ảnh.", ar: "الأهداف والجمهور والنبرة ومحاور المحتوى والتوجه البصري.", ru: "Цели, аудитории, тон, контентные направления и визуальная подача." } },
      { num: "02", title: { fr: "Production", en: "Production", vi: "Sản xuất", ar: "الإنتاج", ru: "Производство" }, desc: { fr: "Création des publications, carrousels, stories et formats courts selon la formule.", en: "Creation of posts, carousels, stories and short formats according to the plan.", vi: "Tạo bài đăng, carousel, story và nội dung ngắn theo gói.", ar: "إنتاج المنشورات والكاروُسيل والقصص والمقاطع القصيرة حسب الباقة.", ru: "Создание постов, каруселей, stories и коротких форматов по пакету." } },
      { num: "03", title: { fr: "Animation", en: "Community management", vi: "Quản lý cộng đồng", ar: "إدارة المجتمع", ru: "Комьюнити-менеджмент" }, desc: { fr: "Modération et réponses selon le niveau de délégation choisi.", en: "Moderation and replies according to the selected delegation level.", vi: "Kiểm duyệt và phản hồi theo mức độ ủy quyền.", ar: "إدارة التعليقات والردود وفق مستوى التفويض المختار.", ru: "Модерация и ответы в соответствии с выбранным уровнем делегирования." } },
      { num: "04", title: { fr: "Pilotage", en: "Reporting", vi: "Báo cáo", ar: "التقارير", ru: "Отчётность" }, desc: { fr: "Lecture des signaux, recommandations et ajustements éditoriaux.", en: "Review signals, recommendations and editorial adjustments.", vi: "Phân tích tín hiệu, đề xuất và điều chỉnh nội dung.", ar: "قراءة المؤشرات والتوصيات والتعديلات التحريرية.", ru: "Анализ сигналов, рекомендации и редакционные корректировки." } },
    ],
    serviceFaqs: [
      { q: { fr: "Que comprend chaque niveau ?", en: "What does each level include?", vi: "Mỗi cấp độ bao gồm gì?", ar: "ماذا يتضمن كل مستوى؟", ru: "Что входит в каждый уровень?" }, a: { fr: "Chaque formule définit le nombre de réseaux, de publications, de stories et le niveau de modération. Les trois niveaux augmentent progressivement la délégation.", en: "Each plan defines networks, posts, stories and moderation level. The three levels progressively increase delegation.", vi: "Mỗi gói xác định số mạng, bài đăng, story và mức độ quản lý. Ba cấp độ tăng dần khả năng ủy quyền.", ar: "كل باقة تحدد عدد الشبكات والمنشورات والقصص ومستوى الإدارة. المستويات الثلاثة تزيد التفويض تدريجيًا.", ru: "Каждый пакет задаёт количество сетей, публикаций, stories и уровень модерации. Три уровня постепенно увеличивают делегирование." } },
      { q: { fr: "Les tournages sont-ils inclus ?", en: "Are shoots included?", vi: "Quay chụp có bao gồm không?", ar: "هل التصوير مشمول؟", ru: "Включены ли съёмки?" }, a: { fr: "Non. Shooting photo/vidéo, déplacement, studio, mannequins et production sur site font l'objet d'un devis séparé.", en: "No. Photo/video shoots, travel, studio, models and on-site production are quoted separately.", vi: "Không. Quay chụp, di chuyển, studio, người mẫu và sản xuất tại chỗ báo giá riêng.", ar: "لا. يتم تسعير التصوير والتنقل والاستوديو والموديلات والإنتاج الميداني بشكل منفصل.", ru: "Нет. Фото/видеосъёмка, выезды, студия, модели и производство на месте считаются отдельно." } },
    ],
  },
  {
    id: "maintenance",
    num: "06",
    title: { fr: "WebCare & Maintenance", en: "WebCare & Maintenance", vi: "WebCare & Bảo trì" },
    short: { fr: "Corrections, évolutions et suivi du site.", en: "Fixes, updates and site monitoring.", vi: "Sửa lỗi, cập nhật và giám sát site." },
    description: { fr: "Maintenance technique, mises à jour de sécurité et petites évolutions pour garder votre site fiable.", en: "Technical maintenance, security updates and small evolutions to keep your site reliable.", vi: "Bảo trì kỹ thuật, cập nhật bảo mật và điều chỉnh nhỏ." },
    fromEur: 29,
    fromPeriod: "month",
    highlights: [
      { fr: "Mises à jour sécurité", en: "Security updates", vi: "Cập nhật bảo mật" },
      { fr: "Support prioritaire", en: "Priority support", vi: "Hỗ trợ ưu tiên" },
    ],
    plans: [
      {
        name: { fr: "Essentiel", en: "Essential", vi: "Cơ bản" },
        eur: 29,
        period: "month",
        features: [
          { fr: "4 modifications / mois", en: "4 changes / month", vi: "4 chỉnh sửa / tháng" },
          { fr: "Corrections de contenu et visuels", en: "Content and visual fixes", vi: "Sửa nội dung và hình ảnh" },
          { fr: "Interventions techniques courantes", en: "Routine technical interventions", vi: "Can thiệp kỹ thuật thường xuyên" },
          { fr: "Suivi standard", en: "Standard support", vi: "Hỗ trợ tiêu chuẩn" },
        ],
      },
      {
        name: { fr: "Business", en: "Business", vi: "Business" },
        eur: 49,
        period: "month",
        popular: true,
        features: [
          { fr: "10 modifications / mois", en: "10 changes / month", vi: "10 chỉnh sửa / tháng" },
          { fr: "Corrections de contenu, visuels et sections", en: "Content, visual and section updates", vi: "Chỉnh sửa nội dung, hình ảnh và phần" },
          { fr: "Interventions techniques courantes", en: "Routine technical interventions", vi: "Can thiệp kỹ thuật thường xuyên" },
          { fr: "Priorité de traitement", en: "Priority handling", vi: "Ưu tiên xử lý" },
          { fr: "Conseils d'évolution courante", en: "Routine improvement advice", vi: "Tư vấn cải tiến thường xuyên" },
        ],
      },
      {
        name: { fr: "Unlimited", en: "Unlimited", vi: "Unlimited" },
        eur: 99,
        period: "month",
        features: [
          { fr: "Modifications courantes illimitées dans le périmètre du site", en: "Unlimited routine changes within the site scope", vi: "Chỉnh sửa thường xuyên không giới hạn trong phạm vi website" },
          { fr: "Corrections de contenu, visuels et sections", en: "Content, visual and section updates", vi: "Chỉnh sửa nội dung, hình ảnh và phần" },
          { fr: "Suivi technique prioritaire", en: "Priority technical support", vi: "Hỗ trợ kỹ thuật ưu tiên" },
          { fr: "Petites évolutions incluses", en: "Small improvements included", vi: "Bao gồm các cải tiến nhỏ" },
          { fr: "Refontes et développements spécifiques sur devis", en: "Redesigns and major development quoted separately", vi: "Thiết kế lại và phát triển lớn báo giá riêng" },
        ],
      },
    ],
  },
];