export const SERVICES_PART1 = [
  {
    id: "websites",
    num: "01",
    title: { fr: "Création de sites web", en: "Website Creation", vi: "Thiết kế website", ar: "إنشاء المواقع", ru: "Создание сайтов" },
    short: { fr: "Sites sur-mesure, pensés comme des objets d'édition.", en: "Bespoke websites, crafted like editorial objects.", vi: "Website riêng biệt, được chế tác như một ấn phẩm.", ar: "مواقع مخصصة مصممة كأعمال تحريرية.", ru: "Индивидуальные сайты, созданные как цифровые редакционные объекты." },
    description: { fr: "Nous concevons des sites haute performance qui transforment vos visiteurs en clients : design sur-mesure, responsive et optimisé pour le référencement.", en: "We design high-performance websites that turn your visitors into customers: bespoke design, fully responsive and SEO-ready.", vi: "Chúng tôi thiết kế website hiệu suất cao biến khách truy cập thành khách hàng: thiết kế riêng, tương thích mọi thiết bị và chuẩn SEO.", ar: "نصمم مواقع عالية الأداء لتحويل الزوار إلى عملاء: تصميم مخصص ومتجاوب ومحسن لمحركات البحث.", ru: "Мы создаём высокопроизводительные сайты, превращающие посетителей в клиентов: индивидуальный дизайн, адаптивность и SEO-оптимизация." },
    fromEur: 499,
    fromPeriod: "once",
    highlights: [
      { fr: "Architecture optimisée et suivi des performances", en: "Optimized architecture and performance tracking", vi: "Điểm PageSpeed Architecture optimisée" },
      { fr: "Optimisation des performances et des médias", en: "Performance and media optimization", vi: "Tải trang dưới 2 giây" },
      { fr: "Expérience multi-secteurs", en: "Multi-sector experience", vi: "Kinh nghiệm đa ngành" },
      { fr: "Hébergement + domaine 1 an inclus", en: "1 year hosting + domain included", vi: "Bao gồm hosting + tên miền 1 năm", ar: "استضافة ونطاق لمدة عام مشمولان", ru: "Хостинг и домен на 1 год включены" },
    ],
    plans: [
      {
        name: { fr: "Site Vitrine Pro", en: "Pro Showcase Site", vi: "Website Giới thiệu Pro" },
        eur: 499,
        period: "once",
        features: [
          { fr: "Design responsive sur-mesure & mobile-first", en: "Bespoke responsive mobile-first design", vi: "Thiết kế responsive độc quyền tối ưu mobile" },
          { fr: "Jusqu'à 3 pages complètes & structurées", en: "Up to 3 complete structured pages", vi: "Tối đa 3 trang hoàn chỉnh và có cấu trúc" },
          { fr: "Formulaire de contact & bouton WhatsApp", en: "Contact form & direct WhatsApp button", vi: "Biểu mẫu liên hệ & nút WhatsApp trực tiếp" },
          { fr: "Optimisation SEO on-page & balisage sémantique", en: "On-page SEO & semantic tags", vi: "Tối ưu hóa SEO on-page & thẻ ngữ nghĩa" },
          { fr: "Hébergement haute vitesse 1 an + SSL inclus", en: "1 year high-speed hosting + SSL included", vi: "Bao gồm 1 năm lưu trữ tốc độ cao + chứng chỉ SSL" },
        ],
      },
      {
        name: { fr: "Site Business", en: "Business Site", vi: "Website Doanh nghiệp" },
        eur: 799,
        period: "once",
        popular: true,
        features: [
          { fr: "Tout le Site Vitrine Pro inclus", en: "Everything in Pro Showcase included", vi: "Bao gồm toàn bộ gói Giới thiệu Pro" },
          { fr: "Jusqu'à 5 pages d'exception sur-mesure", en: "Up to 5 bespoke premium pages", vi: "Tối đa 5 trang thiết kế riêng biệt cao cấp" },
          { fr: "Blog & module d'actualités avec CMS intuitif", en: "Integrated blog & news module with intuitive CMS", vi: "Tích hợp blog & chuyên mục tin tức với CMS dễ dùng" },
          { fr: "Architecture SEO avancée & maillage interne", en: "Advanced SEO architecture & internal linking", vi: "Kiến trúc SEO chuyên sâu & liên kết nội bộ tối ưu" },
          { fr: "Formulaire de devis qualifié & capture de leads", en: "Lead capture & qualified quote form", vi: "Biểu mẫu báo giá chuyên sâu & thu thập khách tiềm năng" },
          { fr: "Vitesse de chargement ultra-rapide (<0.5s)", en: "Ultra-fast loading speed (<0.5s)", vi: "Tốc độ tải trang cực nhanh (<0.5s)" },
          { fr: "Connexion Google Analytics & Search Console", en: "Google Analytics & Search Console setup", vi: "Tích hợp sẵn Google Analytics & Search Console" },
        ],
      },
      {
        name: { fr: "E-commerce & Réservation", en: "E-commerce & Booking", vi: "Thương mại điện tử & Đặt chỗ", ar: "التجارة الإلكترونية والحجز", ru: "E-commerce & Buchungen" },
        eur: 1499,
        period: "once",
        isQuoteOnly: true,
        features: [
          { fr: "Tarif indicatif à partir de 1 499 € (sur devis personnalisé)", en: "Indicative starting price from €1,499 (custom quote required)", vi: "Giá khởi điểm từ 1.499 € (báo giá riêng)" },
          { fr: "Échange préalable obligatoire avec un expert pour cadrer le projet", en: "Mandatory scoping discussion with a specialist", vi: "Trao đổi bắt buộc với chuyên viên" },
          { fr: "Tout le Site Business inclus", en: "Everything in Business Site included", vi: "Bao gồm toàn bộ gói Business" },
          { fr: "Catalogue produits illimité & gestion des stocks", en: "Unlimited product catalog & inventory management", vi: "Danh mục sản phẩm không giới hạn & quản lý kho" },
          { fr: "Paiement sécurisé par CB, Apple Pay & Google Pay (Stripe)", en: "Secure checkout via Card, Apple Pay & Google Pay (Stripe)", vi: "Thanh toán bảo mật qua Thẻ, Apple Pay & Google Pay" },
          { fr: "Module de réservation en ligne avec calendrier dynamique", en: "Online booking module with dynamic calendar", vi: "Mô-đun đặt lịch trực tuyến với lịch tương tác" },
          { fr: "Parcours d'achat ultra-fluide optimisé pour la conversion", en: "Ultra-smooth mobile checkout journey optimized for conversion", vi: "Hành trình mua hàng mượt mà tối ưu chuyển đổi" },
          { fr: "Espace client sécurisé & suivi automatique des commandes", en: "Secure customer account & automated order tracking", vi: "Tài khoản khách hàng bảo mật & theo dõi đơn tự động" },
        ],
      },
    ],
    steps: [
      { num: "01", title: { fr: "Architecture", en: "Architecture", vi: "Kiến trúc", ar: "البنية", ru: "Архитектура" }, desc: { fr: "Arborescence, parcours et hiérarchie des contenus avant le design final.", en: "Sitemap, user journey and content hierarchy before final design.", vi: "Cấu trúc, hành trình và thứ tự nội dung trước thiết kế cuối.", ar: "هيكلة الموقع ومسار المستخدم وتسلسل المحتوى قبل التصميم النهائي.", ru: "Структура, пользовательский путь и иерархия контента до финального дизайна." } },
      { num: "02", title: { fr: "Direction créative", en: "Creative direction", vi: "Định hướng sáng tạo", ar: "التوجيه الإبداعي", ru: "Креативное направление" }, desc: { fr: "Maquette premium, composants cohérents et expérience responsive.", en: "Premium mockup, coherent components and responsive experience.", vi: "Mockup cao cấp, thành phần nhất quán và trải nghiệm responsive.", ar: "ماكيت متميز ومكونات متناسقة وتجربة متجاوبة.", ru: "Премиальный макет, единая система компонентов и адаптивный опыт." } },
      { num: "03", title: { fr: "Production", en: "Production", vi: "Triển khai", ar: "التنفيذ", ru: "Разработка" }, desc: { fr: "Intégration, performance, SEO technique et formulaires fonctionnels.", en: "Implementation, performance, technical SEO and working forms.", vi: "Lập trình, hiệu năng, SEO kỹ thuật và biểu mẫu hoạt động.", ar: "التطوير والأداء وSEO التقني والنماذج الوظيفية.", ru: "Разработка, производительность, техническое SEO и рабочие формы." } },
      { num: "04", title: { fr: "Mise en ligne", en: "Launch", vi: "Ra mắt", ar: "الإطلاق", ru: "Запуск" }, desc: { fr: "Contrôle qualité, mise en production et transmission des accès.", en: "QA, production launch and access handover.", vi: "Kiểm tra chất lượng, đưa vào hoạt động và bàn giao quyền truy cập.", ar: "اختبارات الجودة والإطلاق وتسليم الوصول.", ru: "Контроль качества, запуск и передача доступов." } },
    ],
  },
  {
    id: "branding",
    num: "02",
    title: { fr: "Branding & Identité", en: "Branding & Identity", vi: "Thương hiệu & Nhận diện", ar: "الهوية والعلامة التجارية", ru: "Брендинг и айдентика" },
    short: { fr: "Identités durables, systèmes complets.", en: "Lasting identities, complete systems.", vi: "Nhận diện bền vững, hệ thống hoàn chỉnh.", ar: "هويات بصرية مستدامة وأنظمة متكاملة.", ru: "Выразительная айдентика и цельная система бренда." },
    description: { fr: "Un logo, une palette, une typographie et un système complet de déclinaisons de prestige.", en: "A logo, a palette, a typeface and a complete system of applications.", vi: "Logo, bảng màu, kiểu chữ và hệ thống ứng dụng hoàn chỉnh.", ar: "شعار ولوحة ألوان وخط ونظام متكامل للتطبيقات.", ru: "Логотип, палитра, типографика и полная система бренд-приложений." },
    fromEur: 199,
    fromPeriod: "once",
    highlights: [
      { fr: "Fichiers vectoriels AI, SVG, PNG, PDF", en: "Vector AI, SVG, PNG, PDF files", vi: "Tệp vector AI, SVG, PNG, PDF", ar: "ملفات AI وSVG وPNG وPDF", ru: "Векторные файлы AI, SVG, PNG и PDF" },
      { fr: "Cession intégrale des droits commerciaux", en: "Full commercial rights assigned", vi: "Chuyển giao 100% quyền thương mại", ar: "حقوق الاستخدام التجاري مشمولة بالكامل", ru: "Полная передача коммерческих прав" },
      { fr: "Charte graphique complète & harmonieuse", en: "Complete harmonious brand guidelines", vi: "Bộ quy chuẩn thương hiệu đồng bộ", ar: "دليل هوية بصرية متكامل", ru: "Полный гармоничный брендбук" },
    ],
    plans: [
      {
        name: { fr: "Logo Signature", en: "Signature Logo", vi: "Logo Signature", ar: "شعار Signature", ru: "Логотип Signature" },
        eur: 199,
        period: "once",
        features: [
          { fr: "Logo principal sur-mesure", en: "Main bespoke logo", vi: "Logo chính thiết kế độc quyền" },
          { fr: "Déclinaisons indispensables (sombre, clair, monochrome)", en: "Essential variations (dark, light, monochrome)", vi: "Các phiên bản thiết yếu (tối, sáng, đơn sắc)" },
          { fr: "Fichiers vectoriels haute résolution (AI, SVG, PNG, PDF)", en: "High-resolution vector files (AI, SVG, PNG, PDF)", vi: "Tệp vector độ nét cao (AI, SVG, PNG, PDF)" },
          { fr: "Favicon & icône d'application optimisés", en: "Optimized favicon & app icon", vi: "Favicon & biểu tượng ứng dụng tối ưu" },
          { fr: "Cession complète des droits d'exploitation", en: "Full commercial usage rights", vi: "Toàn quyền sử dụng thương mại" },
        ],
      },
      {
        name: { fr: "Brand Identity Kit", en: "Brand Identity Kit", vi: "Brand Identity Kit" },
        eur: 299,
        period: "once",
        popular: true,
        features: [
          { fr: "Tout le pack Logo Signature inclus", en: "Everything in Signature Logo included", vi: "Bao gồm trọn bộ Logo Signature" },
          { fr: "Palette chromatique de prestige (codes HEX, RGB, CMJN)", en: "Luxury color palette (HEX, RGB, CMYK codes)", vi: "Bảng màu cao cấp (mã HEX, RGB, CMYK)" },
          { fr: "Sélection typographique premium & hiérarchie visuelle", en: "Premium typography pairing & visual hierarchy", vi: "Bộ font chữ cao cấp & phân cấp hiển thị" },
          { fr: "Éléments graphiques, textures & motifs de marque", en: "Brand patterns, graphic elements & textures", vi: "Họa tiết nhận diện, hoa văn & chất liệu đồ họa" },
          { fr: "Gabarits réseaux sociaux prêts à l'emploi (Instagram/LinkedIn)", en: "Ready-to-use social media templates (Instagram/LinkedIn)", vi: "Mẫu bài đăng mạng xã hội (Instagram/LinkedIn)" },
        ],
      },
      {
        name: { fr: "Full Brand Suite", en: "Full Brand Suite", vi: "Full Brand Suite" },
        eur: 399,
        period: "once",
        features: [
          { fr: "Tout le Brand Identity Kit inclus", en: "Everything in Brand Identity Kit included", vi: "Bao gồm trọn bộ Brand Identity Kit" },
          { fr: "Brand Book complet & guide des normes graphiques (PDF de 20+ pages)", en: "Complete Brand Book & visual identity guidelines (20+ pages PDF)", vi: "Brand Book chi tiết & quy chuẩn sử dụng (PDF hơn 20 trang)" },
          { fr: "Déclinaisons papeterie de prestige (cartes de visite, entêtes, devis)", en: "Luxury stationery kit (business cards, letterheads, invoice templates)", vi: "Bộ nhận diện văn phòng cao cấp (danh thiếp, tiêu đề thư, báo giá)" },
          { fr: "Pack signatures d'e-mail animées & corporate", en: "Corporate & animated email signatures pack", vi: "Gói chữ ký email đồng bộ chuyên nghiệp" },
          { fr: "Accompagnement DA dédié & révisions prioritaires", en: "Dedicated art director support & priority revisions", vi: "Giám đốc nghệ thuật hỗ trợ trực tiếp & chỉnh sửa ưu tiên" },
        ],
      },
    ],
    steps: [
      { num: "01", title: { fr: "Plateforme de marque", en: "Brand platform", vi: "Nền tảng thương hiệu", ar: "منصة العلامة", ru: "Платформа бренда" }, desc: { fr: "Positionnement, territoire visuel, ton et principes de cohérence.", en: "Positioning, visual territory, tone and consistency principles.", vi: "Định vị, lãnh địa hình ảnh, giọng điệu và nguyên tắc nhất quán.", ar: "التموضع والهوية البصرية والنبرة ومبادئ الاتساق.", ru: "Позиционирование, визуальная территория, тон и принципы целостности." } },
      { num: "02", title: { fr: "Système visuel", en: "Visual system", vi: "Hệ thống hình ảnh", ar: "النظام البصري", ru: "Визуальная система" }, desc: { fr: "Logo, palette, typographie et déclinaisons pensées ensemble.", en: "Logo, palette, typography and applications designed as one system.", vi: "Logo, bảng màu, kiểu chữ và các ứng dụng được thiết kế đồng bộ.", ar: "الشعار والألوان والخطوط والتطبيقات ضمن نظام واحد.", ru: "Логотип, палитра, типографика и носители как единая система." } },
      { num: "03", title: { fr: "Déploiement", en: "Rollout", vi: "Triển khai", ar: "التطبيق", ru: "Развёртывание" }, desc: { fr: "Fichiers maîtres et règles d'utilisation pour garder une identité stable.", en: "Master files and usage rules to keep the identity consistent.", vi: "Tệp gốc và quy tắc sử dụng để giữ nhận diện nhất quán.", ar: "الملفات الأساسية وقواعد الاستخدام للحفاظ على الاتساق.", ru: "Исходники и правила использования для единого образа." } },
    ],
    serviceFaqs: [
      { q: { fr: "Quelle différence entre les trois niveaux ?", en: "What differs between the three levels?", vi: "Ba cấp độ khác nhau thế nào?", ar: "ما الفرق بين المستويات الثلاثة؟", ru: "Чем отличаются три уровня?" }, a: { fr: "Le niveau choisi détermine la profondeur du système : logo seul, identité complète, puis suite de marque avec Brand Book et déclinaisons.", en: "The level determines system depth: logo only, complete identity, then a full brand suite with Brand Book and applications.", vi: "Cấp độ quyết định độ sâu của hệ thống: logo, nhận diện hoàn chỉnh rồi bộ thương hiệu đầy đủ với Brand Book và ứng dụng.", ar: "يحدد المستوى عمق النظام: شعار فقط، هوية كاملة، ثم حزمة علامة متكاملة مع Brand Book وتطبيقات.", ru: "Уровень определяет глубину системы: только логотип, полная айдентика, затем бренд-пакет с Brand Book и носителями." } },
    ],
  },
  {
    id: "seo",
    num: "03",
    title: { fr: "Référencement SEO", en: "SEO Optimization", vi: "Tối ưu hóa SEO", ar: "تحسين محركات البحث", ru: "SEO-оптимизация" },
    short: { fr: "Visibilité durable sur Google.", en: "Sustainable Google visibility.", vi: "Hiển thị bền vững trên Google.", ar: "ظهور مستدام على Google.", ru: "Устойчивая видимость в Google." },
    description: { fr: "Une stratégie SEO pédagogique et transparente pour le long terme.", en: "An educational and transparent long-term SEO strategy.", vi: "Chiến lược SEO minh bạch dài hạn.", ar: "استراتيجية SEO واضحة وشفافة لبناء ظهور طويل الأمد.", ru: "Понятная и прозрачная SEO-стратегия для долгосрочной видимости." },
    fromEur: 299,
    fromPeriod: "month",
    highlights: [
      { fr: "Acquisition organique", en: "Organic acquisition", vi: "Lưu lượng tự nhiên", ar: "اكتساب عضوي", ru: "Органический трафик" },
      { fr: "Contenus SEO ciblés", en: "Targeted SEO content", vi: "Nội dung SEO mục tiêu", ar: "محتوى SEO مستهدف", ru: "Таргетированный SEO-контент" },
    ],
    plans: [
      {
        name: { fr: "SEO Starter", en: "SEO Starter", vi: "SEO Starter" },
        eur: 299,
        period: "month",
        features: [
          { fr: "Audit & mots-clés", en: "Audit & keywords", vi: "Kiểm toán & từ khóa" },
          { fr: "Optimisation on-page", en: "On-page optimisation", vi: "Tối ưu on-page" },
        ],
      },
      {
        name: { fr: "SEO Growth", en: "SEO Growth", vi: "SEO Growth" },
        eur: 499,
        period: "month",
        popular: true,
        features: [
          { fr: "Tout le Starter", en: "Everything in Starter", vi: "Toàn bộ Starter" },
          { fr: "Contenus mensuels", en: "Monthly content", vi: "Nội dung hàng tháng" },
          { fr: "Reporting", en: "Reporting", vi: "Báo cáo" },
        ],
      },
    ],
  },
];
