import type { L } from "./i18n";

export const UI: Record<string, L> = {
  navServices: { fr: "Services", en: "Services", vi: "Dịch vụ" },
  navPricing: { fr: "Tarifs", en: "Pricing", vi: "Bảng giá" },
  navWork: { fr: "Réalisations", en: "Work", vi: "Dự án" },
  navIntelligence: { fr: "Intelligence", en: "Intelligence", vi: "Intelligence" },
  navFaq: { fr: "FAQ", en: "FAQ", vi: "Hỏi đáp" },
  navContact: { fr: "Contact", en: "Contact", vi: "Liên hệ" },
  bookCall: { fr: "Réserver un appel", en: "Book a call", vi: "Đặt lịch gọi" },

  heroKicker: {
    fr: "Agence digitale premium",
    en: "Premium Digital Agency",
    vi: "Agencе kỹ thuật số cao cấp",
  },
  heroEdition: { fr: "Édition MMXXVI", en: "Edition MMXXVI", vi: "Ấn bản MMXXVI" },
  heroReadTime: { fr: "Lecture 4 min", en: "4 min read", vi: "Đọc 4 phút" },
  heroSummary: { fr: "Sommaire", en: "Summary", vi: "Mục lục" },
  heroPlate: { fr: "Planche — I", en: "Plate — I", vi: "Bản — I" },
  heroQuote: {
    fr: "« Nous ne cherchons pas la tendance. Nous cherchons la justesse. »",
    en: "“We don't chase trends. We chase precision.”",
    vi: "“Chúng tôi không chạy theo xu hướng. Chúng tôi tìm sự chuẩn xác.”",
  },
  heroQuoteAuthor: {
    fr: "— Direction artistique, MMXXVI",
    en: "— Art direction, MMXXVI",
    vi: "— Chỉ đạo nghệ thuật, MMXXVI",
  },
  heroTitle1: { fr: "L'Art du", en: "The Art of", vi: "The Art of" },
  heroTitleAccent: { fr: "Digital", en: "Digital", vi: "Digital" },
  heroTitle2: { fr: "Sur-Mesure.", en: "Craftsmanship.", vi: "Craftsmanship." },
  heroLead: {
    fr: "Une maison indépendante qui compose des expériences digitales pour marques exigeantes : identité, sites, référencement, Google Maps, IA.",
    en: "An independent house composing digital experiences for demanding brands: identity, websites, SEO, Google Maps, AI.",
    vi: "Một studio độc lập kiến tạo trải nghiệm số cho những thương hiệu khắt khe: nhận diện, website, SEO, Google Maps, AI.",
  },
  heroMeta: {
    fr: "Paris — Sur rendez-vous.",
    en: "Paris — By appointment.",
    vi: "Paris — Theo lịch hẹn.",
  },
  ctaAnalysis: { fr: "Lancer mon analyse", en: "Start my analysis", vi: "Bắt đầu phân tích" },
  ctaContinue: { fr: "Continuer", en: "Continue", vi: "Tiếp tục" },

  trustBarLabel: {
    fr: "XR Agency · projets & expertise",
    en: "XR Agency · projects & expertise",
    vi: "XR Agency · dự án & chuyên môn",
  },
  trustBarClients: {
    fr: "Projets internationaux · FR / EN / VI",
    en: "International projects · FR / EN / VI",
    vi: "Dự án quốc tế · FR / EN / VI",
  },
  statProjects: { fr: "Projets livrés", en: "Projects delivered", vi: "Dự án bàn giao" },
  statYears: { fr: "Années d'expertise", en: "Years of expertise", vi: "Năm kinh nghiệm" },
  statRemote: { fr: "Remote — 6 fuseaux", en: "Remote — 6 time zones", vi: "Remote — 6 múi giờ" },
  statProduction: { fr: "Production mondiale", en: "Global production", vi: "Sản xuất toàn cầu" },
  statSatisfaction: {
    fr: "Satisfaction client",
    en: "Client satisfaction",
    vi: "Hài lòng khách hàng",
  },
  statResponse: { fr: "Temps de réponse", en: "Response time", vi: "Thời gian phản hồi" },

  chapter1: { fr: "Chapitre — I · Maison", en: "Chapter — I · House", vi: "Chương — I · Studio" },
  chapter2: {
    fr: "Chapitre — II · Services",
    en: "Chapter — II · Services",
    vi: "Chương — II · Dịch vụ",
  },
  chapter3: {
    fr: "Chapitre — III · Tarifs",
    en: "Chapter — III · Pricing",
    vi: "Chương — III · Bảng giá",
  },
  chapter4: {
    fr: "Chapitre — IV · Portfolio",
    en: "Chapter — IV · Portfolio",
    vi: "Chương — IV · Dự án",
  },
  chapter5: {
    fr: "Chapitre — V · Témoignages",
    en: "Chapter — V · Testimonials",
    vi: "Chương — V · Cảm nhận",
  },
  chapter6: {
    fr: "Chapitre — VI · Questions",
    en: "Chapter — VI · Questions",
    vi: "Chương — VI · Câu hỏi",
  },
  chapter7: { fr: "Correspondance", en: "Correspondence", vi: "Liên hệ" },

  aboutLabel: { fr: "À propos de XR Agency", en: "About XR Agency", vi: "Về XR Agency" },
  aboutTitle1: {
    fr: "Nous ne suivons pas les tendances.",
    en: "We don't follow trends.",
    vi: "Chúng tôi không chạy theo xu hướng.",
  },
  aboutTitle2: {
    fr: "Nous les définissons.",
    en: "We define them.",
    vi: "Chúng tôi tạo ra chúng.",
  },
  aboutText: {
    fr: "Nous croyons en un monde où la technologie et l'humain s'unissent pour créer des expériences inoubliables. Plusieurs expertises, une seule maison, composées à la main.",
    en: "We believe in a world where technology and humans unite to create unforgettable experiences. Multiple disciplines, one house, composed by hand.",
    vi: "Chúng tôi tin vào một thế giới nơi công nghệ và con người cùng tạo nên những trải nghiệm khó quên. Nhiều chuyên môn, một studio, chế tác thủ công.",
  },

  intelLabel: {
    fr: "IA Stratégique",
    en: "Strategic Business AI",
    vi: "Strategic Business AI",
  },
  intelTitle: {
    fr: "XRAGENCY Intelligence",
    en: "XRAGENCY Intelligence",
    vi: "XRAGENCY Intelligence",
  },
  intelIntro: {
    fr: "Bienvenue. J'analyse votre activité et je compose la stratégie digitale idéale, avec une estimation de budget.",
    en: "Welcome. I analyse your business and build the ideal digital strategy, with a budget estimate.",
    vi: "Xin chào. Tôi sẽ phân tích doanh nghiệp của bạn và xây dựng chiến lược số phù hợp, kèm ước tính ngân sách.",
  },
  intelDuration: {
    fr: "Durée estimée — 2 minutes",
    en: "Estimated duration — 2 minutes",
    vi: "Thời lượng — 2 phút",
  },
  intelOnline: {
    fr: "Stratège senior · en ligne",
    en: "Senior strategist · online",
    vi: "Chuyên gia chiến lược · trực tuyến",
  },
  intelStart: { fr: "Lancer mon analyse", en: "Start my analysis", vi: "Bắt đầu phân tích" },
  intelRestart: { fr: "Recommencer", en: "Start over", vi: "Làm lại" },
  intelBack: { fr: "Retour", en: "Back", vi: "Quay lại" },
  intelNext: { fr: "Suivant", en: "Next", vi: "Tiếp theo" },
  intelStep: { fr: "Étape", en: "Step", vi: "Bước" },
  intelOf: { fr: "sur", en: "of", vi: "trên" },
  intelQ1: {
    fr: "Quel est votre secteur d'activité ?",
    en: "What is your industry?",
    vi: "Bạn hoạt động trong lĩnh vực nào?",
  },
  intelQ2: {
    fr: "Quel est votre objectif prioritaire ?",
    en: "What is your priority objective?",
    vi: "Mục tiêu ưu tiên của bạn là gì?",
  },
  intelQ3: {
    fr: "Où en êtes-vous aujourd'hui ?",
    en: "Where do you stand today?",
    vi: "Hiện tại bạn đang ở đâu?",
  },
  intelQ4: {
    fr: "Quel budget mensuel envisagez-vous ?",
    en: "What monthly budget do you have in mind?",
    vi: "Ngân sách hàng tháng dự kiến của bạn?",
  },
  intelResultLabel: {
    fr: "Stratégie recommandée",
    en: "Recommended strategy",
    vi: "Chiến lược đề xuất",
  },
  intelResultTitle: { fr: "Votre feuille de route", en: "Your roadmap", vi: "Lộ trình của bạn" },
  intelEstimate: { fr: "Estimation de devis", en: "Quote estimate", vi: "Ước tính báo giá" },
  intelSetup: { fr: "Mise en place", en: "Setup", vi: "Triển khai" },
  intelRecurring: {
    fr: "Accompagnement mensuel",
    en: "Monthly retainer",
    vi: "Đồng hành hàng tháng",
  },
  intelSend: {
    fr: "Recevoir ce devis sur WhatsApp",
    en: "Get this quote on WhatsApp",
    vi: "Nhận báo giá qua WhatsApp",
  },
  intelDisclaimer: {
    fr: "Estimation indicative établie à partir de nos grilles tarifaires. Le devis définitif est confirmé sous 24 h.",
    en: "Indicative estimate based on our published price lists. The final quote is confirmed within 24 hours.",
    vi: "Ước tính tham khảo dựa trên bảng giá của chúng tôi. Báo giá cuối cùng được xác nhận trong 24 giờ.",
  },
  intelWhy: { fr: "Pourquoi", en: "Why", vi: "Vì sao" },
  intelOptionsTitle: {
    fr: "Options & suppléments",
    en: "Options & add-ons",
    vi: "Tùy chọn & phụ phí",
  },
  intelOptionLang: {
    fr: "Langue supplémentaire — +100 € par langue",
    en: "Extra language — +$130 per language",
    vi: "Ngôn ngữ bổ sung — +2.200.000 ₫ mỗi ngôn ngữ",
  },
  intelOptionBooking: {
    fr: "Système de réservation en ligne — sur devis",
    en: "Online booking system — on quote",
    vi: "Hệ thống đặt chỗ trực tuyến — theo báo giá",
  },
  intelOptionEcom: {
    fr: "E-commerce à partir de 1 499 € — ajusté selon le nombre de produits",
    en: "E-commerce from $1,943 — adjusted to the number of products",
    vi: "Thương mại điện tử từ 32.978.000 ₫ — điều chỉnh theo số lượng sản phẩm",
  },
  intelTimeline: { fr: "Mise en ligne estimée", en: "Estimated go-live", vi: "Dự kiến ra mắt" },
  intelTimelineValue: { fr: "7 à 21 jours", en: "7 to 21 days", vi: "7 đến 21 ngày" },
  intelProgress: { fr: "Analyse", en: "Analysis", vi: "Phân tích" },

  servicesLabel: { fr: "Nos services", en: "Our services", vi: "Dịch vụ của chúng tôi" },
  servicesTitle1: { fr: "Ce que nous", en: "What we", vi: "Những gì chúng tôi" },
  servicesTitle2: { fr: "faisons.", en: "do.", vi: "thực hiện." },
  servicesLead: {
    fr: "Plusieurs expertises. Une seule maison. Composées à la main pour marques exigeantes.",
    en: "Multiple disciplines. One house. Composed by hand for demanding brands.",
    vi: "Nhiều chuyên môn. Một studio. Chế tác thủ công cho những thương hiệu khắt khe.",
  },
  from: { fr: "À partir de", en: "From", vi: "Từ" },
  discover: { fr: "Découvrir", en: "Discover", vi: "Khám phá" },

  pricingLabel: { fr: "Grille tarifaire", en: "Price list", vi: "Bảng giá" },
  pricingTitle1: { fr: "Des tarifs", en: "Transparent", vi: "Mức giá" },
  pricingTitle2: { fr: "transparents.", en: "pricing.", vi: "minh bạch." },
  pricingLead: {
    fr: "Toutes nos formules, sans frais cachés. Chaque offre mène directement au configurateur IA pour un devis personnalisé.",
    en: "Every plan, with no hidden fees. Each offer leads straight to the AI configurator for a tailored quote.",
    vi: "Tất cả các gói, không phí ẩn. Mỗi gói dẫn thẳng đến trình cấu hình AI để nhận báo giá riêng.",
  },
  popular: { fr: "Le plus choisi", en: "Most popular", vi: "Được chọn nhiều nhất" },
  choosePlan: { fr: "Choisir cette formule", en: "Choose this plan", vi: "Chọn gói này" },
  customQuote: { fr: "Demander un devis", en: "Request a quote", vi: "Yêu cầu báo giá" },

  mapsLabel: { fr: "Service premium", en: "Premium service", vi: "Dịch vụ cao cấp" },
  mapsVisibility: {
    fr: "Visibilité moyenne",
    en: "Average visibility",
    vi: "Khả năng hiển thị trung bình",
  },
  mapsYourBusiness: { fr: "Votre entreprise", en: "Your business", vi: "Doanh nghiệp của bạn" },
  mapsCompetitor: { fr: "Concurrent", en: "Competitor", vi: "Đối thủ" },
  mapsLocalPack: { fr: "Local Pack — TOP 3", en: "Local Pack — TOP 3", vi: "Local Pack — TOP 3" },

  aiLabel: { fr: "Assistants IA", en: "AI Assistants", vi: "Trợ lý AI" },
  aiCompare: {
    fr: "Humain vs Intelligence artificielle",
    en: "Human vs Artificial Intelligence",
    vi: "Con người và Trí tuệ nhân tạo",
  },
  aiFeature: { fr: "Critère", en: "Criterion", vi: "Tiêu chí" },
  aiHuman: { fr: "Humain", en: "Human", vi: "Con người" },
  aiAi: { fr: "IA", en: "AI", vi: "AI" },
  aiAvailability: { fr: "Disponibilité", en: "Availability", vi: "Khả dụng" },
  aiHours: { fr: "8 h / jour", en: "8h / day", vi: "8 giờ / ngày" },
  aiResponse: { fr: "Temps de réponse", en: "Response time", vi: "Thời gian phản hồi" },
  aiResponseHuman: { fr: "5 — 30 min", en: "5 — 30 min", vi: "5 — 30 phút" },
  aiResponseAi: { fr: "Instantané", en: "Instant", vi: "Tức thì" },
  aiLanguages: { fr: "Langues", en: "Languages", vi: "Ngôn ngữ" },
  aiUnlimited: { fr: "Illimité", en: "Unlimited", vi: "Không giới hạn" },
  aiCost: { fr: "Coût mensuel", en: "Monthly cost", vi: "Chi phí hàng tháng" },

  workLabel: {
    fr: "Portfolio · Études de cas",
    en: "Portfolio · Case studies",
    vi: "Dự án · Nghiên cứu tình huống",
  },
  workTitle1: { fr: "Références", en: "Selected", vi: "Selected" },
  workTitle2: { fr: "Sélectionnées.", en: "work.", vi: "work." },
  equation: {
    fr: "Stratégie × (Design + Technologie) = Résultats",
    en: "Strategy × (Design + Tech) = Results",
    vi: "Chiến lược × (Thiết kế + Công nghệ) = Kết quả",
  },

  trustLabel: { fr: "Ils nous font confiance", en: "They trust us", vi: "Họ tin tưởng chúng tôi" },
  trustTitle1: {
    fr: "Des entreprises locales",
    en: "Local and international businesses",
    vi: "Doanh nghiệp địa phương",
  },
  trustTitle2: { fr: "et internationales.", en: "trust us.", vi: "tin tưởng chúng tôi." },
  trustSubtitle: {
    fr: "Des entreprises locales et internationales nous confient leur présence digitale. Des études de cas authentiques arrivent prochainement.",
    en: "Local and international businesses trust us with their digital presence. Authentic case studies coming soon.",
    vi: "Các doanh nghiệp địa phương và quốc tế tin tưởng giao phó sự hiện diện số cho chúng tôi. Các nghiên cứu tình sẽ có sớm.",
  },
  workCase: {
    fr: "Obtenir le même résultat",
    en: "Get the same result",
    vi: "Đạt kết quả tương tự",
  },
  workVerified: { fr: "Avis vérifié", en: "Verified review", vi: "Đánh giá đã xác minh" },
  workLinkedCase: {
    fr: "Voir l'étude de cas",
    en: "View the case study",
    vi: "Xem nghiên cứu tình huống",
  },

  faqLabel: {
    fr: "Questions fréquentes",
    en: "Frequently asked questions",
    vi: "Câu hỏi thường gặp",
  },
  faqTitle1: { fr: "Tout ce qu'il faut", en: "Everything you need", vi: "Mọi điều bạn cần" },
  faqTitle2: { fr: "savoir.", en: "to know.", vi: "biết." },

  // ── FAQ Categories ──
  faqCatAll: { fr: "Toutes", en: "All", vi: "Tất cả" },
  faqCatSites: { fr: "Sites internet", en: "Websites", vi: "Website" },
  faqCatSeo: { fr: "SEO & visibilité", en: "SEO & visibility", vi: "SEO & hiển thị" },
  faqCatAds: { fr: "Google Ads", en: "Google Ads", vi: "Google Ads" },
  faqCatIa: {
    fr: "Intelligence Artificielle",
    en: "Artificial Intelligence",
    vi: "Trí tuệ nhân tạo",
  },
  faqCatTarifs: { fr: "Tarifs & accompagnement", en: "Pricing & support", vi: "Bảng giá & hỗ trợ" },
  faqCatDelais: { fr: "Délais", en: "Timelines", vi: "Thời gian" },
  faqCatGeneral: { fr: "Général", en: "General", vi: "Chung" },
  faqShowAll: {
    fr: "Voir toutes les questions",
    en: "See all questions",
    vi: "Xem tất cả câu hỏi",
  },
  faqShowLess: { fr: "Voir moins", en: "Show less", vi: "Xem ít hơn" },

  contactLabel: {
    fr: "Gratuit · 30 min · Sans engagement",
    en: "Free · 30 min · No commitment",
    vi: "Miễn phí · 30 phút · Không ràng buộc",
  },
  contactTitle1: { fr: "Réservez votre", en: "Book your free", vi: "Đặt lịch" },
  contactTitle2: {
    fr: "consultation digitale.",
    en: "digital consultation.",
    vi: "tư vấn số miễn phí.",
  },
  contactLead: {
    fr: "Un appel stratégique de 30 minutes avec notre équipe. Nous auditons votre présence actuelle et vous remettons une feuille de route actionnable — que vous travailliez avec nous ou non.",
    en: "A 30-minute strategy call with our team. We audit your current presence and hand you an actionable roadmap — whether you work with us or not.",
    vi: "Cuộc gọi chiến lược 30 phút cùng đội ngũ của chúng tôi. Chúng tôi kiểm tra hiện diện số của bạn và trao lộ trình hành động — dù bạn có hợp tác hay không.",
  },
  contactPoint1: {
    fr: "Zoom / Google Meet / WhatsApp vidéo",
    en: "Zoom / Google Meet / WhatsApp video",
    vi: "Zoom / Google Meet / video WhatsApp",
  },
  contactPoint2: {
    fr: "Confirmation sous 1 heure ouvrée",
    en: "Confirmation within 1 business hour",
    vi: "Xác nhận trong 1 giờ làm việc",
  },
  contactPoint3: {
    fr: "Heure de Paris (CET) · Disponibilité mondiale",
    en: "Paris time (CET) · Global availability",
    vi: "Giờ Paris (CET) · Phục vụ toàn cầu",
  },
  contactWhatsapp: {
    fr: "Écrire sur WhatsApp",
    en: "Message on WhatsApp",
    vi: "Nhắn tin WhatsApp",
  },
  contactEmail: { fr: "Nous écrire", en: "Email us", vi: "Gửi e-mail" },
  contactHeading: {
    fr: "Construisons votre avantage digital.",
    en: "Let's build your digital advantage.",
    vi: "Hãy xây dựng lợi thế số của bạn.",
  },
  contactFormName: { fr: "Nom", en: "Name", vi: "Tên" },
  contactFormEmail: { fr: "Email", en: "Email", vi: "Email" },
  contactFormCompany: { fr: "Entreprise", en: "Company", vi: "Công ty" },
  contactFormWebsite: { fr: "Site internet", en: "Website", vi: "Website" },
  contactFormMessage: { fr: "Message", en: "Message", vi: "Tin nhắn" },
  contactFormNeed: { fr: "Quel est votre besoin ?", en: "What do you need?", vi: "Bạn cần gì?" },
  contactFormNeedSite: { fr: "Création de site", en: "Website creation", vi: "Tạo website" },
  contactFormNeedRedesign: { fr: "Refonte", en: "Redesign", vi: "Thiết kế lại" },
  contactFormNeedSeo: { fr: "SEO", en: "SEO", vi: "SEO" },
  contactFormNeedAds: { fr: "Publicité", en: "Advertising", vi: "Quảng cáo" },
  contactFormNeedAi: { fr: "IA & Automatisation", en: "AI & Automation", vi: "AI & Tự động hóa" },
  contactFormNeedStrategy: {
    fr: "Stratégie digitale",
    en: "Digital strategy",
    vi: "Chiến lược số",
  },
  contactFormNeedOther: { fr: "Autre", en: "Other", vi: "Khác" },
  contactFormSubmit: {
    fr: "Parlons de votre projet",
    en: "Let's talk about your project",
    vi: "Hãy bàn về dự án của bạn",
  },
  contactQuote: {
    fr: "« Une correspondance vaut mille présentations. Écrivez-nous — nous répondons sous 24 h. »",
    en: "“One letter is worth a thousand presentations. Write to us — we reply within 24 hours.”",
    vi: "“Một lá thư giá trị hơn ngàn bài thuyết trình. Hãy viết cho chúng tôi — chúng tôi trả lời trong 24 giờ.”",
  },
  footerMade: {
    fr: "Fait avec obsession — Paris, France",
    en: "Made with obsession — Paris, France",
    vi: "Thực hiện với sự tận tâm — Paris, Pháp",
  },
  footerRights: {
    fr: "© 2026 XR Agency — Tous droits réservés",
    en: "© 2026 XR Agency — All rights reserved",
    vi: "© 2026 XR Agency — Bảo lưu mọi quyền",
  },
  serviceOverview: {
    fr: "Présentation détaillée",
    en: "Detailed overview",
    vi: "Tổng quan chi tiết",
  },
  serviceProcess: {
    fr: "Méthode & Livrables",
    en: "Method & Deliverables",
    vi: "Phương pháp & Bàn giao",
  },
  serviceProcessDesc: {
    fr: "Un workflow transparent et rigoureux, de l'audit initial à la livraison finale.",
    en: "A transparent and rigorous workflow, from initial audit to final delivery.",
    vi: "Quy trình làm việc minh bạch và chuẩn mực, từ đánh giá ban đầu đến bàn giao cuối cùng.",
  },
  serviceCompareTitle: {
    fr: "Pourquoi choisir XR Agency ?",
    en: "Why choose XR Agency?",
    vi: "Tại sao chọn XR Agency?",
  },
  serviceCompareDesc: {
    fr: "Découvrez la différence d'un studio d'élite par rapport aux prestataires généralistes.",
    en: "Discover the difference of an elite studio compared to generalist providers.",
    vi: "Sự khác biệt của một studio chuyên nghiệp so với các đơn vị đại trà.",
  },
  serviceFaqTitle: {
    fr: "Questions fréquentes",
    en: "Frequently asked questions",
    vi: "Câu hỏi thường gặp",
  },
  backToServices: { fr: "← Retour à l'accueil", en: "← Back to home", vi: "← Về trang chủ" },
  explorePacks: { fr: "Découvrir les formules", en: "Explore plans", vi: "Khám phá các gói" },
  getCustomQuote: {
    fr: "Configurer mon devis IA",
    en: "Configure my AI quote",
    vi: "Cấu hình báo giá AI",
  },
  bookDirectWhatsapp: {
    fr: "Échanger sur WhatsApp",
    en: "Chat on WhatsApp",
    vi: "Trao đổi qua WhatsApp",
  },
  resultsGuaranteed: {
    fr: "Performance et satisfaction suivies",
    en: "Performance and satisfaction tracking",
    vi: "Theo dõi hiệu suất & sự hài lòng",
  },
  featureComparison: {
    fr: "Critères d'évaluation",
    en: "Evaluation criteria",
    vi: "Tiêu chí đánh giá",
  },
  withXrAgency: { fr: "XR Agency", en: "XR Agency", vi: "XR Agency" },
  traditionalAgency: {
    fr: "Standard du marché",
    en: "Market standard",
    vi: "Tiêu chuẩn thị trường",
  },
  otherServices: {
    fr: "Découvrez nos autres expertises",
    en: "Discover our other expertises",
    vi: "Khám phá các dịch vụ khác",
  },
  readyToStart: {
    fr: "Prêt à propulser votre activité ?",
    en: "Ready to scale your business?",
    vi: "Sẵn sàng bứt phá doanh nghiệp?",
  },
  contactUsNow: {
    fr: "Contactez notre équipe senior pour recevoir une proposition adaptée à votre projet.",
    en: "Contact our senior team for a proposal tailored to your project.",
    vi: "Liên hệ với đội ngũ chuyên gia để nhận đề xuất phù hợp với dự án của bạn.",
  },

  // ── Showcase / Portfolio ──
  showcaseLabel: {
    fr: "Inspirations · Direction artistique",
    en: "Inspirations · Art direction",
    vi: "Cảm hứng · Chỉ đạo nghệ thuật",
  },
  showcaseTitle1: {
    fr: "Inspirations de style.",
    en: "Style inspirations.",
    vi: "Cảm hứng phong cách.",
  },
  showcaseTitle2: { fr: "Direction artistique.", en: "Art direction.", vi: "Chỉ đạo nghệ thuật." },
  showcaseLead: {
    fr: "Ces sites illustrent le niveau d'exigence, l'esthétique et le standard de qualité que nous appliquons à chaque projet. Ils ne sont pas des réalisations XR Agency, mais représentent la direction artistique que nous visons pour votre marque.",
    en: "These websites illustrate the level of demand, aesthetics and quality standard we apply to every project. They are not XR Agency creations, but represent the art direction we aim for your brand.",
    vi: "Những website này minh họa mức độ yêu cầu, thẩm mỹ và tiêu chuẩn chất lượng mà chúng tôi áp dụng cho mỗi dự án. Đây không phải là tác phẩm của XR Agency, mà đại diện cho hướng nghệ thuật chúng tôi hướng đến cho thương hiệu của bạn.",
  },
  showcaseDisclaimer: {
    fr: "Les sites présentés sont des références de direction artistique et non des projets réalisés par XR Agency. Ils illustrent le niveau d'exigence et le style que nous appliquons.",
    en: "The sites shown are art direction references, not XR Agency projects. They illustrate the standard and style we deliver.",
    vi: "Các website được trình bày là tham khảo chỉ đạo nghệ thuật, không phải dự án XR Agency đã thực hiện. Chúng minh họa mức độ yêu cầu và phong cách chúng tôi áp dụng.",
  },
  showcaseVisitSite: { fr: "Visiter le site", en: "Visit website", vi: "Xem website" },
  showcaseAllSectors: { fr: "Tous les secteurs", en: "All sectors", vi: "Tất cả lĩnh vực" },
  showcaseAllServices: { fr: "Tous les services", en: "All services", vi: "Tất cả dịch vụ" },
  serviceWebsite: { fr: "Site web", en: "Website", vi: "Website" },
  serviceEcommerce: { fr: "E-commerce", en: "E-commerce", vi: "Thương mại điện tử" },
  serviceBooking: { fr: "Réservation", en: "Booking", vi: "Đặt chỗ" },
  serviceBranding: { fr: "Branding", en: "Branding", vi: "Thương hiệu" },
  serviceSeo: { fr: "SEO", en: "SEO", vi: "SEO" },
  serviceSocial: { fr: "Social Media", en: "Social Media", vi: "Mạng xã hội" },
  serviceStrategy: { fr: "Stratégie digitale", en: "Digital Strategy", vi: "Chiến lược số" },
  serviceAi: { fr: "IA", en: "AI", vi: "AI" },
  serviceWebcare: { fr: "Webcare", en: "Webcare", vi: "Webcare" },

  showcaseSiteVitrine: { fr: "Site vitrine", en: "Showcase site", vi: "Website giới thiệu" },
  showcaseEcommerce: { fr: "E-commerce", en: "E-commerce", vi: "Thương mại điện tử" },
  showcaseBoth: {
    fr: "Vitrine + E-commerce",
    en: "Showcase + E-commerce",
    vi: "Giới thiệu + TMĐT",
  },
  showcaseWebApp: { fr: "Web App", en: "Web App", vi: "Ứng dụng web" },

  // Sectors
  sectorLuxe: { fr: "Luxe & Joaillerie", en: "Luxury & Jewelry", vi: "Xa xỉ & Trang sức" },
  sectorGastronomie: { fr: "Gastronomie", en: "Fine Dining", vi: "Ẩm thực cao cấp" },
  sectorHotellerie: {
    fr: "Hôtellerie & Tourisme",
    en: "Hospitality & Travel",
    vi: "Khách sạn & Du lịch",
  },
  sectorImmobilier: { fr: "Immobilier", en: "Real Estate", vi: "Bất động sản" },
  sectorSante: { fr: "Santé & Bien-être", en: "Health & Wellness", vi: "Sức khỏe & Sức khỏe" },
  sectorBeaute: { fr: "Beauté & Cosmétique", en: "Beauty & Cosmetics", vi: "Làm đẹp & Mỹ phẩm" },
  sectorAuto: { fr: "Automobile", en: "Automotive", vi: "Ô tô" },
  sectorMode: { fr: "Mode & Prêt-à-porter", en: "Fashion & Ready-to-wear", vi: "Thời trang" },
  sectorArchitecture: {
    fr: "Architecture & Design",
    en: "Architecture & Design",
    vi: "Kiến trúc & Thiết kế",
  },
  sectorTech: { fr: "Tech & Innovation", en: "Tech & Innovation", vi: "Công nghệ & Đổi mới" },
  sectorCoaching: {
    fr: "Coaching & Formation",
    en: "Coaching & Training",
    vi: "Huấn luyện & Đào tạo",
  },
  sectorArtisanat: {
    fr: "Artisanat & BTP",
    en: "Crafts & Construction",
    vi: "Thủ công & Xây dựng",
  },

  // ── Legal mentions ──
  legalTitle: { fr: "Mentions légales", en: "Legal information", vi: "Thông tin pháp lý" },
  legalCompany: { fr: "Société", en: "Company", vi: "Công ty" },
  legalForm: { fr: "Forme juridique", en: "Legal form", vi: "Hình thức pháp lý" },
  legalCapital: { fr: "Capital social", en: "Share capital", vi: "Vốn điều lệ" },
  legalRcs: { fr: "Immatriculation", en: "Registration", vi: "Đăng ký" },
  legalSiren: { fr: "SIREN", en: "SIREN", vi: "SIREN" },
  legalSiret: { fr: "SIRET", en: "SIRET", vi: "SIRET" },
  legalTva: { fr: "N° TVA intracommunautaire", en: "VAT number", vi: "Mã số thuế VAT" },
  legalDirector: {
    fr: "Directeur de la publication",
    en: "Publication director",
    vi: "Giám đốc xuất bản",
  },
  legalAddress: { fr: "Siège social", en: "Registered office", vi: "Trụ sở chính" },
  legalHosting: { fr: "Hébergement", en: "Hosting", vi: "Lưu trữ" },
  legalHostingProvider: {
    fr: "Vercel Inc. — 340 S Lemon Ave #4133, Walnut, CA 91789, USA",
    en: "Vercel Inc. — 340 S Lemon Ave #4133, Walnut, CA 91789, USA",
    vi: "Vercel Inc. — 340 S Lemon Ave #4133, Walnut, CA 91789, USA",
  },
  legalCopyright: {
    fr: "© 2026 XR Agency — Tous droits réservés",
    en: "© 2026 XR Agency — All rights reserved",
    vi: "© 2026 XR Agency — Mọi quyền được bảo lưu",
  },
  legalPrivacy: {
    fr: "Politique de confidentialité",
    en: "Privacy policy",
    vi: "Chính sách bảo mật",
  },
  legalPrivacyText: {
    fr: "Les données collectées (nom, email, téléphone) sont exclusivement utilisées dans le cadre de notre relation commerciale. Elles ne sont jamais transmises à des tiers. Conformément au RGPD, vous pouvez exercer votre droit d'accès, de rectification ou de suppression en nous écrivant à contact.xragency@gmail.com.",
    en: "Data collected (name, email, phone) is used solely within our business relationship. It is never shared with third parties. Under GDPR, you may exercise your right to access, rectify or delete data by writing to contact.xragency@gmail.com.",
    vi: "Dữ liệu thu thập (tên, email, điện thoại) chỉ được sử dụng trong mối quan hệ kinh doanh. Không bao giờ chia sẻ với bên thứ ba. Theo RGPD, bạn có quyền truy cập, sửa đổi hoặc xóa dữ liệu bằng cách gửi email đến contact.xragency@gmail.com.",
  },
  legalTerms: {
    fr: "Conditions générales",
    en: "Terms & conditions",
    vi: "Điều khoản sử dụng",
  },
  footerContact: {
    fr: "Contact",
    en: "Contact",
    vi: "Liên hệ",
  },
  footerLegal: {
    fr: "Mentions légales",
    en: "Legal info",
    vi: "Thông tin pháp lý",
  },
  ctaReassurance: {
    fr: "Réponse rapide · FR / EN / VI · Sans engagement",
    en: "Fast response · FR / EN / VI · No commitment",
    vi: "Phản hồi nhanh · FR / EN / VI · Không cam kết",
  },

  // ── SaaS Dashboard ──
  dashTitle: { fr: "Tableau de bord", en: "Dashboard", vi: "Bảng điều khiển" },
  dashProspects: { fr: "Prospects", en: "Prospects", vi: "Khách tiềm năng" },
  dashAudits: { fr: "Audits", en: "Audits", vi: "Kiểm toán" },
  dashNewAudit: { fr: "Nouvel audit", en: "New audit", vi: "Kiểm toán mới" },
  dashSettings: { fr: "Paramètres", en: "Settings", vi: "Cài đặt" },
  dashLogout: { fr: "Déconnexion", en: "Sign out", vi: "Đăng xuất" },
  dashLogin: { fr: "Connexion", en: "Sign in", vi: "Đăng nhập" },
  dashTotalProspects: { fr: "Total prospects", en: "Total prospects", vi: "Tổng khách tiềm năng" },
  dashAuditsCompleted: {
    fr: "Audits terminés",
    en: "Audits completed",
    vi: "Kiểm toán hoàn thành",
  },
  dashAvgScore: { fr: "Score moyen", en: "Average score", vi: "Điểm trung bình" },
  dashConversionRate: { fr: "Taux conversion", en: "Conversion rate", vi: "Tỷ lệ chuyển đổi" },
  dashRecentActivity: { fr: "Activité récente", en: "Recent activity", vi: "Hoạt động gần đây" },
  dashQuickAudit: { fr: "Audit rapide", en: "Quick audit", vi: "Kiểm toán nhanh" },
  dashEnterUrl: {
    fr: "Entrez une URL pour analyser",
    en: "Enter a URL to analyze",
    vi: "Nhập URL để phân tích",
  },
  dashAnalyze: { fr: "Analyser", en: "Analyze", vi: "Phân tích" },
  dashNoProspects: { fr: "Aucun prospect", en: "No prospects yet", vi: "Chưa có khách tiềm năng" },
  dashAddProspect: { fr: "Ajouter un prospect", en: "Add prospect", vi: "Thêm khách" },
  dashNoAudits: { fr: "Aucun audit", en: "No audits yet", vi: "Chưa có kiểm toán" },
  dashRunAudit: { fr: "Lancer un audit", en: "Run an audit", vi: "Chạy kiểm toán" },
  dashScore: { fr: "Score", en: "Score", vi: "Điểm" },
  dashStatus: { fr: "Statut", en: "Status", vi: "Trạng thái" },
  dashDate: { fr: "Date", en: "Date", vi: "Ngày" },
  dashActions: { fr: "Actions", en: "Actions", vi: "Hành động" },
  dashBusinessName: { fr: "Entreprise", en: "Business", vi: "Doanh nghiệp" },
  dashWebsite: { fr: "Site web", en: "Website", vi: "Trang web" },
  dashIndustry: { fr: "Secteur", en: "Industry", vi: "Ngành" },
  dashLocation: { fr: "Localisation", en: "Location", vi: "Vị trí" },
  dashContact: { fr: "Contact", en: "Contact", vi: "Liên hệ" },
  dashNotes: { fr: "Notes", en: "Notes", vi: "Ghi chú" },
  dashOpportunities: { fr: "Opportunités", en: "Opportunities", vi: "Cơ hội" },
  dashIssues: { fr: "Problèmes détectés", en: "Issues detected", vi: "Vấn đề phát hiện" },
  dashExecutiveSummary: {
    fr: "Synthèse exécutive",
    en: "Executive summary",
    vi: "Tóm tắt điều hành",
  },
  dashCategoryBreakdown: {
    fr: "Détail par catégorie",
    en: "Category breakdown",
    vi: "Chi tiết theo danh mục",
  },
  dashRecommendedServices: {
    fr: "Services recommandés",
    en: "Recommended services",
    vi: "Dịch vụ đề xuất",
  },
  dashEmail: { fr: "Email", en: "Email", vi: "Email" },
  dashPassword: { fr: "Mot de passe", en: "Password", vi: "Mật khẩu" },
  dashForgotPassword: { fr: "Mot de passe oublié ?", en: "Forgot password?", vi: "Quên mật khẩu?" },
  dashNoAccount: { fr: "Pas de compte ?", en: "No account?", vi: "Chưa có tài khoản?" },
  dashSignUp: { fr: "S'inscrire", en: "Sign up", vi: "Đăng ký" },
  dashWelcomeBack: { fr: "Bienvenue", en: "Welcome back", vi: "Chào mừng trở lại" },
  dashLoginSubtitle: {
    fr: "Connectez-vous à votre espace d'audit",
    en: "Sign in to your audit workspace",
    vi: "Đăng nhập vào không gian kiểm toán",
  },
  statusNew: { fr: "Nouveau", en: "New", vi: "Mới" },
  statusAudited: { fr: "Audité", en: "Audited", vi: "Đã kiểm toán" },
  statusContacted: { fr: "Contacté", en: "Contacted", vi: "Đã liên hệ" },
  statusQualified: { fr: "Qualifié", en: "Qualified", vi: "Đủ điều kiện" },
  statusClient: { fr: "Client", en: "Client", vi: "Khách hàng" },
  statusPending: { fr: "En attente", en: "Pending", vi: "Đang chờ" },
  statusCrawling: { fr: "Crawl en cours", en: "Crawling", vi: "Đang thu thập" },
  statusAnalyzing: { fr: "Analyse en cours", en: "Analyzing", vi: "Đang phân tích" },
  statusCompleted: { fr: "Terminé", en: "Completed", vi: "Hoàn thành" },
  statusFailed: { fr: "Échec", en: "Failed", vi: "Thất bại" },

  // ── About Section ──
  aboutKicker: {
    fr: "External Agency Intelligence",
    en: "External Agency Intelligence",
    vi: "Trí tuệ Agency Ngoại bộ",
  },
  aboutHeading: {
    fr: "Votre direction digitale & studio d'élite,",
    en: "Your digital direction & elite studio,",
    vi: "Hướng dẫn số & studio đẳng cấp của bạn,",
  },
  aboutHeadingAccent: {
    fr: "activés à la demande.",
    en: "activated on demand.",
    vi: "kích hoạt theo yêu cầu.",
  },
  aboutLead: {
    fr: "Pourquoi recruter et gérer 5 salariés quand vous pouvez brancher instantanément une équipe senior complète, coordonnée et disponible au moment où votre entreprise accélère ?",
    en: "Why hire and manage 5 employees when you can instantly plug in a complete, coordinated senior team available exactly when your business accelerates?",
    vi: "Tại sao phải tuyển dụng và quản lý 5 nhân viên khi bạn có thể kết nối ngay lập tức một đội ngũ cấp cao hoàn chỉnh, phối hợp nhịp nhàng và sẵn sàng khi doanh nghiệp tăng tốc?",
  },
  aboutTeamLabel: {
    fr: "Collectif Senior · Paris, Asie & USA",
    en: "Senior Collective · Paris, Asia & USA",
    vi: "Tập thể Cấp cao · Paris, Châu Á & USA",
  },
  aboutHubKicker: {
    fr: "Hub Modulaire d'Expertises",
    en: "Modular Expertise Hub",
    vi: "Trung tâm Chuyên môn Mô-đun",
  },
  aboutHubTitle: {
    fr: "Explorez les 6 piliers de frappe de votre agence externe",
    en: "Explore the 6 pillars of your external agency",
    vi: "Khám phá 6 trụ cột của agency ngoại bộ",
  },
  aboutHubHint: {
    fr: "Cliquez sur un pôle pour voir son impact",
    en: "Click a pillar to see its impact",
    vi: "Nhấn vào một trụ cột để xem tác động",
  },
  aboutPoleLabel: {
    fr: "Pôle",
    en: "Pillar",
    vi: "Trụ cột",
  },
  aboutPoleActivated: {
    fr: "Activé à la demande",
    en: "Activated on demand",
    vi: "Kích hoạt theo yêu cầu",
  },
  aboutDeliverables: {
    fr: "Livrables & interventions directes :",
    en: "Deliverables & direct interventions:",
    vi: "Kết quả bàn giao & can thiệp trực tiếp:",
  },
  aboutImpactLabel: {
    fr: "Impact & Résultat Mesuré",
    en: "Impact & Measured Result",
    vi: "Tác động & Kết quả Đo lường",
  },
  aboutImpactDesc: {
    fr: "Chaque pôle est déployé avec une obligation de rigueur et un reporting transparent.",
    en: "Each pillar is deployed with rigorous standards and transparent reporting.",
    vi: "Mỗi trụ cột được triển khai với tiêu chuẩn nghiêm ngặt và báo cáo minh bạch.",
  },
  aboutTestPole: {
    fr: "Tester ce pôle dans le configurateur IA →",
    en: "Test this pillar in the AI configurator →",
    vi: "Thử trụ cột này trong bộ cấu hình AI →",
  },
  aboutChoiceKicker: {
    fr: "Le Choix Stratégique",
    en: "The Strategic Choice",
    vi: "Lựa chọn Chiến lược",
  },
  aboutChoiceTitle: {
    fr: "Recruter une équipe interne ou brancher XR Agency ?",
    en: "Hire an internal team or plug in XR Agency?",
    vi: "Tuyển đội nội bộ hay kết nối XR Agency?",
  },
  aboutChoiceLead: {
    fr: "Comparez la flexibilité, le coût et l'impact direct sur votre trésorerie.",
    en: "Compare flexibility, cost and direct impact on your cash flow.",
    vi: "So sánh tính linh hoạt, chi phí và tác động trực tiếp đến dòng tiền.",
  },
  aboutTraditional: {
    fr: "Option Traditionnelle",
    en: "Traditional Option",
    vi: "Phương án Truyền thống",
  },
  aboutInHouse: {
    fr: "En interne",
    en: "In-house",
    vi: "Nội bộ",
  },
  aboutRecruitTitle: {
    fr: "Recrutement de 4 à 5 salariés",
    en: "Hiring 4 to 5 employees",
    vi: "Tuyển dụng 4 đến 5 nhân viên",
  },
  aboutRecruitCost: {
    fr: "/mois + charges",
    en: "/month + payroll taxes",
    vi: "/tháng + thuế",
  },
  aboutCon1: {
    fr: "3 à 6 mois de processus de recrutement",
    en: "3 to 6 months of recruitment process",
    vi: "3 đến 6 tháng quy trình tuyển dụng",
  },
  aboutCon2: {
    fr: "Charges patronales, matériel, congés payés",
    en: "Payroll taxes, equipment, paid leave",
    vi: "Thuế, thiết bị, nghỉ phép",
  },
  aboutCon3: {
    fr: "Compétences limitées à chaque profil recruté",
    en: "Skills limited to each recruited profile",
    vi: "Kỹ năng giới hạn ở mỗi hồ sơ tuyển dụng",
  },
  aboutCon4: {
    fr: "Risque financier lourd et rigidité contractuelle",
    en: "Heavy financial risk and contractual rigidity",
    vi: "Rủi ro tài chính lớn và ràng buộc hợp đồng",
  },
  aboutRecommended: {
    fr: "Recommandé",
    en: "Recommended",
    vi: "Đề xuất",
  },
  aboutExternalFormula: {
    fr: "Formule Hub Externe",
    en: "External Hub Plan",
    vi: "Gói Trung tâm Ngoại bộ",
  },
  aboutXrLabel: {
    fr: "XR Agency",
    en: "XR Agency",
    vi: "XR Agency",
  },
  aboutDigitalTitle: {
    fr: "Votre Direction Digitale & IA Immédiate",
    en: "Your Immediate Digital & AI Direction",
    vi: "Hướng dẫn Số & AI Ngay lập tức",
  },
  aboutFromLabel: {
    fr: "/mois ou au forfait",
    en: "/month or flat rate",
    vi: "/tháng hoặc trọn gói",
  },
  aboutPro1: {
    fr: "Opérationnel en 48 heures ouvrées",
    en: "Operational within 48 business hours",
    vi: "Hoạt động trong 48 giờ làm việc",
  },
  aboutPro2: {
    fr: "Accès à un collectif senior (DA, Dev, SEO, IA)",
    en: "Access to a senior collective (DA, Dev, SEO, AI)",
    vi: "Truy cập tập thể cấp cao (DA, Dev, SEO, AI)",
  },
  aboutPro3: {
    fr: "Zéro charge patronale, zéro engagement contraignant",
    en: "Zero payroll tax, zero binding commitment",
    vi: "Không thuế, không ràng buộc hợp đồng",
  },
  aboutPro4: {
    fr: "Objectifs définis et suivi transparent",
    en: "Defined objectives and transparent monitoring",
    vi: "Mục tiêu rõ ràng và theo dõi minh bạch",
  },
  aboutSimulateCta: {
    fr: "Simuler mon accompagnement externe",
    en: "Simulate my external support",
    vi: "Mô phỏng hỗ trợ ngoại bộ",
  },

  // ── Intelligence Section Labels ──
  intelAdvisorActive: {
    fr: "Conseiller Stratégique IA Actif · Analyse personnalisée",
    en: "AI Strategic Advisor Active · Personalized analysis",
    vi: "Cố vấn Chiến lược AI Đang hoạt động · Phân tích cá nhân hóa",
  },
  intelAuditTimer: {
    fr: "Audit & Estimation sous 60s",
    en: "Audit & Estimate in 60s",
    vi: "Audit & Ước tính trong 60s",
  },
  intelAdvisorName: {
    fr: "XR Intelligence · Stratège Digitale",
    en: "XR Intelligence · Digital Strategy",
    vi: "XR Intelligence · Chiến lược số",
  },
  intelAdvisorSub: {
    fr: "XR Agency Paris & International",
    en: "XR Agency Paris & International",
    vi: "XR Agency Paris & Quốc tế",
  },
  intelRestartLabel: {
    fr: "Recommencer",
    en: "Start over",
    vi: "Làm lại",
  },
  intelSetupLabel: {
    fr: "Mise en place",
    en: "Setup",
    vi: "Triển khai",
  },
  intelMonthlyLabel: {
    fr: "Suivi Mensuel",
    en: "Monthly Tracking",
    vi: "Theo dõi Hàng tháng",
  },
  intelYearlyLabel: {
    fr: "Google Maps (Annuel)",
    en: "Google Maps (Annual)",
    vi: "Google Maps (Hàng năm)",
  },
  intelSendWhatsapp: {
    fr: "Transmettre mon plan sur WhatsApp",
    en: "Send my plan via WhatsApp",
    vi: "Gửi kế hoạch qua WhatsApp",
  },
  intelCopyPlan: {
    fr: "Copier le plan",
    en: "Copy plan",
    vi: "Sao chép kế hoạch",
  },
  intelPlanCopied: {
    fr: "Plan copié !",
    en: "Plan copied!",
    vi: "Đã sao chép!",
  },
  intelFormule: {
    fr: "Formule :",
    en: "Plan:",
    vi: "Gói:",
  },
  intelWhyLabel: {
    fr: "Pourquoi :",
    en: "Why:",
    vi: "Vì sao:",
  },

  // ── Logo & Global ──
  logoSubtitle: {
    fr: "Le Digital",
    en: "The Digital",
    vi: "Digital",
  },

  // ── Marquee ──
  marqueeServices: {
    fr: "Sites Web \u00B7 Identité · SEO · Google Maps · Social Media · IA · Maintenance · ",
    en: "Websites · Branding · SEO · Google Maps · Social Media · AI · Maintenance · ",
    vi: "Website · Nhận diện · SEO · Google Maps · Mạng xã hội · AI · Bảo trì · ",
  },

  // ── Parallax Captions ──
  dividerCaption1: {
    fr: "Architecture · Design · Performance",
    en: "Architecture · Design · Performance",
    vi: "Kiến trúc · Thiết kế · Hiệu năng",
  },
  dividerCaption2: {
    fr: "L'art du détail · The art of detail",
    en: "The art of detail",
    vi: "Nghệ thuật của chi tiết",
  },
  dividerCaption3: {
    fr: "Paris · Dubaï · Tokyo · New York",
    en: "Paris · Dubai · Tokyo · New York",
    vi: "Paris · Dubai · Tokyo · New York",
  },
  dividerCaption4: {
    fr: "Votre prochaine réussite commence ici",
    en: "Your next success starts here",
    vi: "Thành công tiếp theo bắt đầu từ đây",
  },

  // ── Gallery Captions ──
  galleryCaption1: {
    fr: "Direction Stratégique",
    en: "Strategic Direction",
    vi: "Định hướng Chiến lược",
  },
  galleryCaption2: {
    fr: "Atelier Créatif & UX",
    en: "Creative Workshop & UX",
    vi: "Xưởng Sáng tạo & UX",
  },
  galleryCaption3: { fr: "Conception Éditoriale", en: "Editorial Design", vi: "Thiết kế Biên tập" },
  galleryCaption4: {
    fr: "Ingénierie & Déploiement",
    en: "Engineering & Deployment",
    vi: "Kỹ thuật & Triển khai",
  },
};
