import type { L } from "./i18n";

export const UI: Record<string, L> = {
  navServices: { fr: "Services", en: "Services", vi: "Dịch vụ" },
  navPricing: { fr: "Tarifs", en: "Pricing", vi: "Bảng giá" },
  navWork: { fr: "Réalisations", en: "Work", vi: "Dự án" },
  navIntelligence: { fr: "Intelligence", en: "Intelligence", vi: "Intelligence" },
  navFaq: { fr: "FAQ", en: "FAQ", vi: "Hỏi đáp" },
  navContact: { fr: "Contact", en: "Contact", vi: "Liên hệ" },
  bookCall: { fr: "Réserver un appel", en: "Book a call", vi: "Đặt lịch gọi" },

  heroKicker: {
    fr: "Feature — Studio digital de prestige",
    en: "Feature — Prestige digital studio",
    vi: "Chuyên đề — Studio digital cao cấp",
  },
  heroEdition: { fr: "Édition MMXXVI", en: "Edition MMXXVI", vi: "Ấn bản MMXXVI" },
  heroReadTime: { fr: "Lecture 4 min", en: "4 min read", vi: "Đọc 4 phút" },
  heroSummary: { fr: "Sommaire", en: "Summary", vi: "Mục lục" },
  heroPlate: { fr: "Planche — I", en: "Plate — I", vi: "Bản — I" },
  heroQuote: {
    fr: "« Nous ne cherchons pas la tendance. Nous cherchons la justesse. »",
    en: "“We don't chase trends. We chase precision.”",
    vi: "“Chúng tôi không chạy theo xu hướng. Chúng tôi tìm sự chuẩn xác.”",
  },
  heroQuoteAuthor: {
    fr: "— Direction artistique, MMXXVI",
    en: "— Art direction, MMXXVI",
    vi: "— Chỉ đạo nghệ thuật, MMXXVI",
  },
  heroTitle1: { fr: "The Art of", en: "The Art of", vi: "The Art of" },
  heroTitleAccent: { fr: "Digital", en: "Digital", vi: "Digital" },
  heroTitle2: { fr: "Craftsmanship.", en: "Craftsmanship.", vi: "Craftsmanship." },
  heroLead: {
    fr: "Une maison indépendante qui compose des expériences digitales pour marques exigeantes : identité, sites, référencement, Google Maps, IA.",
    en: "An independent house composing digital experiences for demanding brands: identity, websites, SEO, Google Maps, AI.",
    vi: "Một studio độc lập kiến tạo trải nghiệm số cho những thương hiệu khắt khe: nhận diện, website, SEO, Google Maps, AI.",
  },
  heroMeta: { fr: "Paris — Sur rendez-vous.", en: "Paris — By appointment.", vi: "Paris — Theo lịch hẹn." },
  ctaAnalysis: { fr: "Lancer mon analyse", en: "Start my analysis", vi: "Bắt đầu phân tích" },
  ctaContinue: { fr: "Continuer", en: "Continue", vi: "Tiếp tục" },

  statProjects: { fr: "Projets livrés", en: "Projects delivered", vi: "Dự án bàn giao" },
  statYears: { fr: "Années d'expertise", en: "Years of expertise", vi: "Năm kinh nghiệm" },
  statRemote: { fr: "Remote — 6 fuseaux", en: "Remote — 6 time zones", vi: "Remote — 6 múi giờ" },
  statProduction: { fr: "Production mondiale", en: "Global production", vi: "Sản xuất toàn cầu" },

  chapter1: { fr: "Chapitre — I · Maison", en: "Chapter — I · House", vi: "Chương — I · Studio" },
  chapter2: { fr: "Chapitre — II · Services", en: "Chapter — II · Services", vi: "Chương — II · Dịch vụ" },
  chapter3: { fr: "Chapitre — III · Tarifs", en: "Chapter — III · Pricing", vi: "Chương — III · Bảng giá" },
  chapter4: { fr: "Chapitre — IV · Portfolio", en: "Chapter — IV · Portfolio", vi: "Chương — IV · Dự án" },
  chapter5: { fr: "Chapitre — V · Témoignages", en: "Chapter — V · Testimonials", vi: "Chương — V · Cảm nhận" },
  chapter6: { fr: "Chapitre — VI · Questions", en: "Chapter — VI · Questions", vi: "Chương — VI · Câu hỏi" },
  chapter7: { fr: "Correspondance", en: "Correspondence", vi: "Liên hệ" },

  aboutLabel: { fr: "À propos de XR Agency", en: "About XR Agency", vi: "Về XR Agency" },
  aboutTitle1: { fr: "Nous ne suivons pas les tendances.", en: "We don't follow trends.", vi: "Chúng tôi không chạy theo xu hướng." },
  aboutTitle2: { fr: "Nous les définissons.", en: "We define them.", vi: "Chúng tôi tạo ra chúng." },
  aboutText: {
    fr: "Nous croyons en un monde où la technologie et l'humain s'unissent pour créer des expériences inoubliables. Sept disciplines, une seule maison, composées à la main.",
    en: "We believe in a world where technology and humans unite to create unforgettable experiences. Seven disciplines, one house, composed by hand.",
    vi: "Chúng tôi tin vào một thế giới nơi công nghệ và con người cùng tạo nên những trải nghiệm khó quên. Bảy lĩnh vực, một studio, chế tác thủ công.",
  },

  intelLabel: { fr: "Strategic Business AI", en: "Strategic Business AI", vi: "Strategic Business AI" },
  intelTitle: { fr: "XRAGENCY Intelligence", en: "XRAGENCY Intelligence", vi: "XRAGENCY Intelligence" },
  intelIntro: {
    fr: "Bienvenue. J'analyse votre activité et je compose la stratégie digitale idéale, avec une estimation de budget.",
    en: "Welcome. I analyse your business and build the ideal digital strategy, with a budget estimate.",
    vi: "Xin chào. Tôi sẽ phân tích doanh nghiệp của bạn và xây dựng chiến lược số phù hợp, kèm ước tính ngân sách.",
  },
  intelDuration: { fr: "Durée estimée — 2 minutes", en: "Estimated duration — 2 minutes", vi: "Thời lượng — 2 phút" },
  intelOnline: { fr: "Stratège senior · en ligne", en: "Senior strategist · online", vi: "Chuyên gia chiến lược · trực tuyến" },
  intelStart: { fr: "Lancer mon analyse", en: "Start my analysis", vi: "Bắt đầu phân tích" },
  intelRestart: { fr: "Recommencer", en: "Start over", vi: "Làm lại" },
  intelBack: { fr: "Retour", en: "Back", vi: "Quay lại" },
  intelNext: { fr: "Suivant", en: "Next", vi: "Tiếp theo" },
  intelStep: { fr: "Étape", en: "Step", vi: "Bước" },
  intelOf: { fr: "sur", en: "of", vi: "trên" },
  intelQ1: { fr: "Quel est votre secteur d'activité ?", en: "What is your industry?", vi: "Bạn hoạt động trong lĩnh vực nào?" },
  intelQ2: { fr: "Quel est votre objectif prioritaire ?", en: "What is your priority objective?", vi: "Mục tiêu ưu tiên của bạn là gì?" },
  intelQ3: { fr: "Où en êtes-vous aujourd'hui ?", en: "Where do you stand today?", vi: "Hiện tại bạn đang ở đâu?" },
  intelQ4: { fr: "Quel budget mensuel envisagez-vous ?", en: "What monthly budget do you have in mind?", vi: "Ngân sách hàng tháng dự kiến của bạn?" },
  intelResultLabel: { fr: "Stratégie recommandée", en: "Recommended strategy", vi: "Chiến lược đề xuất" },
  intelResultTitle: { fr: "Votre feuille de route", en: "Your roadmap", vi: "Lộ trình của bạn" },
  intelEstimate: { fr: "Estimation de devis", en: "Quote estimate", vi: "Ước tính báo giá" },
  intelSetup: { fr: "Mise en place", en: "Setup", vi: "Triển khai" },
  intelRecurring: { fr: "Accompagnement mensuel", en: "Monthly retainer", vi: "Đồng hành hàng tháng" },
  intelSend: { fr: "Recevoir ce devis sur WhatsApp", en: "Get this quote on WhatsApp", vi: "Nhận báo giá qua WhatsApp" },
  intelDisclaimer: {
    fr: "Estimation indicative établie à partir de nos grilles tarifaires. Le devis définitif est confirmé sous 24 h.",
    en: "Indicative estimate based on our published price lists. The final quote is confirmed within 24 hours.",
    vi: "Ước tính tham khảo dựa trên bảng giá của chúng tôi. Báo giá cuối cùng được xác nhận trong 24 giờ.",
  },

  servicesLabel: { fr: "Nos services", en: "Our services", vi: "Dịch vụ của chúng tôi" },
  servicesTitle1: { fr: "Ce que nous", en: "What we", vi: "Những gì chúng tôi" },
  servicesTitle2: { fr: "faisons.", en: "do.", vi: "thực hiện." },
  servicesLead: {
    fr: "Sept disciplines. Une seule maison. Composées à la main pour marques exigeantes.",
    en: "Seven disciplines. One house. Composed by hand for demanding brands.",
    vi: "Bảy lĩnh vực. Một studio. Chế tác thủ công cho những thương hiệu khắt khe.",
  },
  from: { fr: "À partir de", en: "From", vi: "Từ" },
  discover: { fr: "Découvrir", en: "Discover", vi: "Khám phá" },

  pricingLabel: { fr: "Grille tarifaire", en: "Price list", vi: "Bảng giá" },
  pricingTitle1: { fr: "Des tarifs", en: "Transparent", vi: "Mức giá" },
  pricingTitle2: { fr: "transparents.", en: "pricing.", vi: "minh bạch." },
  pricingLead: {
    fr: "Toutes nos formules, sans frais cachés. Chaque offre mène directement au configurateur IA pour un devis personnalisé.",
    en: "Every plan, with no hidden fees. Each offer leads straight to the AI configurator for a tailored quote.",
    vi: "Tất cả các gói, không phí ẩn. Mỗi gói dẫn thẳng đến trình cấu hình AI để nhận báo giá riêng.",
  },
  popular: { fr: "Le plus choisi", en: "Most popular", vi: "Được chọn nhiều nhất" },
  choosePlan: { fr: "Choisir cette formule", en: "Choose this plan", vi: "Chọn gói này" },
  customQuote: { fr: "Demander un devis", en: "Request a quote", vi: "Yêu cầu báo giá" },

  mapsLabel: { fr: "Service premium", en: "Premium service", vi: "Dịch vụ cao cấp" },
  mapsVisibility: { fr: "Visibilité moyenne", en: "Average visibility", vi: "Khả năng hiển thị trung bình" },
  mapsYourBusiness: { fr: "Votre entreprise", en: "Your business", vi: "Doanh nghiệp của bạn" },
  mapsCompetitor: { fr: "Concurrent", en: "Competitor", vi: "Đối thủ" },
  mapsLocalPack: { fr: "Local Pack — TOP 3", en: "Local Pack — TOP 3", vi: "Local Pack — TOP 3" },

  aiLabel: { fr: "Assistants IA 24/7", en: "AI Assistants 24/7", vi: "Trợ lý AI 24/7" },
  aiCompare: { fr: "Humain vs Intelligence artificielle", en: "Human vs Artificial Intelligence", vi: "Con người và Trí tuệ nhân tạo" },
  aiFeature: { fr: "Critère", en: "Criterion", vi: "Tiêu chí" },
  aiHuman: { fr: "Humain", en: "Human", vi: "Con người" },
  aiAi: { fr: "IA", en: "AI", vi: "AI" },
  aiAvailability: { fr: "Disponibilité", en: "Availability", vi: "Khả dụng" },
  aiHours: { fr: "8 h / jour", en: "8h / day", vi: "8 giờ / ngày" },
  aiResponse: { fr: "Temps de réponse", en: "Response time", vi: "Thời gian phản hồi" },
  aiResponseHuman: { fr: "5 — 30 min", en: "5 — 30 min", vi: "5 — 30 phút" },
  aiResponseAi: { fr: "Instantané", en: "Instant", vi: "Tức thì" },
  aiLanguages: { fr: "Langues", en: "Languages", vi: "Ngôn ngữ" },
  aiUnlimited: { fr: "Illimité", en: "Unlimited", vi: "Không giới hạn" },
  aiCost: { fr: "Coût mensuel", en: "Monthly cost", vi: "Chi phí hàng tháng" },

  workLabel: { fr: "Portfolio · Études de cas", en: "Portfolio · Case studies", vi: "Dự án · Nghiên cứu tình huống" },
  workTitle1: { fr: "Selected", en: "Selected", vi: "Selected" },
  workTitle2: { fr: "work.", en: "work.", vi: "work." },
  equation: { fr: "Stratégie × (Design + Tech) = Résultats", en: "Strategy × (Design + Tech) = Results", vi: "Chiến lược × (Thiết kế + Công nghệ) = Kết quả" },

  trustLabel: { fr: "Ils nous font confiance", en: "They trust us", vi: "Họ tin tưởng chúng tôi" },
  trustTitle1: { fr: "Des marques de prestige", en: "Prestigious brands", vi: "Những thương hiệu danh tiếng" },
  trustTitle2: { fr: "choisissent XRAGENCY.", en: "choose XRAGENCY.", vi: "chọn XRAGENCY." },
  trustRating: { fr: "4,9/5 — sur la base de 150+ avis clients.", en: "4.9/5 — based on 150+ customer reviews.", vi: "4,9/5 — dựa trên hơn 150 đánh giá khách hàng." },

  faqLabel: { fr: "Questions fréquentes", en: "Frequently asked questions", vi: "Câu hỏi thường gặp" },
  faqTitle1: { fr: "Tout ce qu'il faut", en: "Everything you need", vi: "Mọi điều bạn cần" },
  faqTitle2: { fr: "savoir.", en: "to know.", vi: "biết." },

  contactLabel: { fr: "Gratuit · 30 min · Sans engagement", en: "Free · 30 min · No commitment", vi: "Miễn phí · 30 phút · Không ràng buộc" },
  contactTitle1: { fr: "Réservez votre", en: "Book your free", vi: "Đặt lịch" },
  contactTitle2: { fr: "consultation digitale.", en: "digital consultation.", vi: "tư vấn số miễn phí." },
  contactLead: {
    fr: "Un appel stratégique de 30 minutes avec notre équipe. Nous auditons votre présence actuelle et vous remettons une feuille de route actionnable — que vous travailliez avec nous ou non.",
    en: "A 30-minute strategy call with our team. We audit your current presence and hand you an actionable roadmap — whether you work with us or not.",
    vi: "Cuộc gọi chiến lược 30 phút cùng đội ngũ của chúng tôi. Chúng tôi kiểm tra hiện diện số của bạn và trao lộ trình hành động — dù bạn có hợp tác hay không.",
  },
  contactPoint1: { fr: "Zoom / Google Meet / WhatsApp vidéo", en: "Zoom / Google Meet / WhatsApp video", vi: "Zoom / Google Meet / video WhatsApp" },
  contactPoint2: { fr: "Confirmation sous 1 heure ouvrée", en: "Confirmation within 1 business hour", vi: "Xác nhận trong 1 giờ làm việc" },
  contactPoint3: { fr: "Heure de Paris (CET) · Disponibilité mondiale", en: "Paris time (CET) · Global availability", vi: "Giờ Paris (CET) · Phục vụ toàn cầu" },
  contactWhatsapp: { fr: "Écrire sur WhatsApp", en: "Message on WhatsApp", vi: "Nhắn tin WhatsApp" },
  contactEmail: { fr: "Nous écrire", en: "Email us", vi: "Gửi e-mail" },
  contactQuote: {
    fr: "« Une correspondance vaut mille présentations. Écrivez-nous — nous répondons sous 24 h. »",
    en: "“One letter is worth a thousand presentations. Write to us — we reply within 24 hours.”",
    vi: "“Một lá thư giá trị hơn ngàn bài thuyết trình. Hãy viết cho chúng tôi — chúng tôi trả lời trong 24 giờ.”",
  },
  footerMade: { fr: "Fait avec obsession — Paris, France", en: "Made with obsession — Paris, France", vi: "Thực hiện với sự tận tâm — Paris, Pháp" },
  footerRights: { fr: "© 2026 XR Agency — Tous droits réservés", en: "© 2026 XR Agency — All rights reserved", vi: "© 2026 XR Agency — Bảo lưu mọi quyền" },
};