export type PortfolioReference = {
  name: string;
  url: string;
  sector: string;
  type: "Vitrine" | "E-commerce" | "Branding" | "SaaS" | "Portail";
  image: string;
};

const images: Record<string, string> = {
  luxe: "https://images.unsplash.com/photo-1525507119028-ed4c629a60a3?auto=format&fit=crop&q=85&w=1200",
  hotel: "https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&q=85&w=1200",
  restaurant: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&q=85&w=1200",
  immobilier: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&q=85&w=1200",
  auto: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&q=85&w=1200",
  architecture: "https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&q=85&w=1200",
  mode: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&q=85&w=1200",
  beaute: "https://images.unsplash.com/photo-1596462502278-27bfdc403398?auto=format&fit=crop&q=85&w=1200",
  sante: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&q=85&w=1200",
  droit: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?auto=format&fit=crop&q=85&w=1200",
  finance: "https://images.unsplash.com/photo-1559526324-593bc073d938?auto=format&fit=crop&q=85&w=1200",
  tech: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=85&w=1200",
  education: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=85&w=1200",
  sport: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&q=85&w=1200",
  voyage: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&q=85&w=1200",
  maison: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&q=85&w=1200",
  joaillerie: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?auto=format&fit=crop&q=85&w=1200",
  food: "https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&q=85&w=1200",
  spa: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?auto=format&fit=crop&q=85&w=1200",
  construction: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=85&w=1200",
};

export const PORTFOLIO_REFERENCES: PortfolioReference[] = [
  { name: "Hermès", url: "https://www.hermes.com/", sector: "luxe", type: "E-commerce", image: images.luxe },
  { name: "CHANEL", url: "https://www.chanel.com/", sector: "luxe", type: "E-commerce", image: images.luxe },
  { name: "Dior", url: "https://www.dior.com/", sector: "luxe", type: "E-commerce", image: images.luxe },
  { name: "Aman", url: "https://www.aman.com/", sector: "hotel", type: "Vitrine", image: images.hotel },
  { name: "Rosewood Hotels", url: "https://www.rosewoodhotels.com/", sector: "hotel", type: "Vitrine", image: images.hotel },
  { name: "Four Seasons", url: "https://www.fourseasons.com/", sector: "hotel", type: "Vitrine", image: images.hotel },
  { name: "Noma", url: "https://noma.dk/", sector: "restaurant", type: "Vitrine", image: images.restaurant },
  { name: "Eleven Madison Park", url: "https://www.elevenmadisonpark.com/", sector: "restaurant", type: "Vitrine", image: images.restaurant },
  { name: "Le Bernardin", url: "https://www.le-bernardin.com/", sector: "restaurant", type: "Vitrine", image: images.restaurant },
  { name: "Sotheby's International Realty", url: "https://www.sothebysrealty.com/", sector: "immobilier", type: "Portail", image: images.immobilier },
  { name: "Knight Frank", url: "https://www.knightfrank.com/", sector: "immobilier", type: "Portail", image: images.immobilier },
  { name: "Savills", url: "https://www.savills.com/", sector: "immobilier", type: "Portail", image: images.immobilier },
  { name: "Porsche", url: "https://www.porsche.com/", sector: "auto", type: "Vitrine", image: images.auto },
  { name: "Ferrari", url: "https://www.ferrari.com/", sector: "auto", type: "Vitrine", image: images.auto },
  { name: "Lamborghini", url: "https://www.lamborghini.com/", sector: "auto", type: "Vitrine", image: images.auto },
  { name: "Foster + Partners", url: "https://www.fosterandpartners.com/", sector: "architecture", type: "Vitrine", image: images.architecture },
  { name: "Bjarke Ingels Group", url: "https://big.dk/", sector: "architecture", type: "Vitrine", image: images.architecture },
  { name: "Snøhetta", url: "https://snohetta.com/", sector: "architecture", type: "Vitrine", image: images.architecture },
  { name: "NET-A-PORTER", url: "https://www.net-a-porter.com/", sector: "mode", type: "E-commerce", image: images.mode },
  { name: "SSENSE", url: "https://www.ssense.com/", sector: "mode", type: "E-commerce", image: images.mode },
  { name: "FARFETCH", url: "https://www.farfetch.com/", sector: "mode", type: "E-commerce", image: images.mode },
  { name: "Aesop", url: "https://www.aesop.com/", sector: "beaute", type: "E-commerce", image: images.beaute },
  { name: "Glossier", url: "https://www.glossier.com/", sector: "beaute", type: "E-commerce", image: images.beaute },
  { name: "Sephora", url: "https://www.sephora.com/", sector: "beaute", type: "E-commerce", image: images.beaute },
  { name: "Mayo Clinic", url: "https://www.mayoclinic.org/", sector: "sante", type: "Portail", image: images.sante },
  { name: "Cleveland Clinic", url: "https://my.clevelandclinic.org/", sector: "sante", type: "Portail", image: images.sante },
  { name: "One Medical", url: "https://www.onemedical.com/", sector: "sante", type: "Vitrine", image: images.sante },
  { name: "Latham & Watkins", url: "https://www.lw.com/", sector: "droit", type: "Vitrine", image: images.droit },
  { name: "Freshfields", url: "https://www.freshfields.com/", sector: "droit", type: "Vitrine", image: images.droit },
  { name: "Clifford Chance", url: "https://www.cliffordchance.com/", sector: "droit", type: "Vitrine", image: images.droit },
  { name: "Stripe", url: "https://stripe.com/", sector: "finance", type: "SaaS", image: images.finance },
  { name: "Revolut", url: "https://www.revolut.com/", sector: "finance", type: "Vitrine", image: images.finance },
  { name: "Wise", url: "https://wise.com/", sector: "finance", type: "Vitrine", image: images.finance },
  { name: "Linear", url: "https://linear.app/", sector: "tech", type: "SaaS", image: images.tech },
  { name: "Notion", url: "https://www.notion.so/", sector: "tech", type: "SaaS", image: images.tech },
  { name: "Vercel", url: "https://vercel.com/", sector: "tech", type: "SaaS", image: images.tech },
  { name: "Coursera", url: "https://www.coursera.org/", sector: "education", type: "SaaS", image: images.education },
  { name: "MasterClass", url: "https://www.masterclass.com/", sector: "education", type: "SaaS", image: images.education },
  { name: "Duolingo", url: "https://www.duolingo.com/", sector: "education", type: "SaaS", image: images.education },
  { name: "Nike", url: "https://www.nike.com/", sector: "sport", type: "E-commerce", image: images.sport },
  { name: "adidas", url: "https://www.adidas.com/", sector: "sport", type: "E-commerce", image: images.sport },
  { name: "PUMA", url: "https://www.puma.com/", sector: "sport", type: "E-commerce", image: images.sport },
  { name: "Airbnb", url: "https://www.airbnb.com/", sector: "voyage", type: "Portail", image: images.voyage },
  { name: "Booking.com", url: "https://www.booking.com/", sector: "voyage", type: "Portail", image: images.voyage },
  { name: "Expedia", url: "https://www.expedia.com/", sector: "voyage", type: "Portail", image: images.voyage },
  { name: "Vitra", url: "https://www.vitra.com/", sector: "maison", type: "E-commerce", image: images.maison },
  { name: "Herman Miller", url: "https://www.hermanmiller.com/", sector: "maison", type: "E-commerce", image: images.maison },
  { name: "IKEA", url: "https://www.ikea.com/", sector: "maison", type: "E-commerce", image: images.maison },
  { name: "Cartier", url: "https://www.cartier.com/", sector: "joaillerie", type: "E-commerce", image: images.joaillerie },
  { name: "Tiffany & Co.", url: "https://www.tiffany.com/", sector: "joaillerie", type: "E-commerce", image: images.joaillerie },
  { name: "Van Cleef & Arpels", url: "https://www.vancleefarpels.com/", sector: "joaillerie", type: "E-commerce", image: images.joaillerie },
  { name: "Eataly", url: "https://www.eataly.com/", sector: "food", type: "E-commerce", image: images.food },
  { name: "Whole Foods Market", url: "https://www.wholefoodsmarket.com/", sector: "food", type: "E-commerce", image: images.food },
  { name: "HelloFresh", url: "https://www.hellofresh.com/", sector: "food", type: "E-commerce", image: images.food },
  { name: "Six Senses", url: "https://www.sixsenses.com/", sector: "spa", type: "Vitrine", image: images.spa },
  { name: "Mandarin Oriental", url: "https://www.mandarinoriental.com/", sector: "spa", type: "Vitrine", image: images.spa },
  { name: "Soho House", url: "https://www.sohohouse.com/", sector: "spa", type: "Vitrine", image: images.spa },
  { name: "Bechtel", url: "https://www.bechtel.com/", sector: "construction", type: "Vitrine", image: images.construction },
  { name: "VINCI", url: "https://www.vinci.com/", sector: "construction", type: "Vitrine", image: images.construction },
  { name: "Bouygues Construction", url: "https://www.bouygues-construction.com/", sector: "construction", type: "Vitrine", image: images.construction },
];

export const PORTFOLIO_SECTORS = [
  ["luxe", "Luxe"], ["hotel", "Hôtellerie"], ["restaurant", "Restauration"], ["immobilier", "Immobilier"], ["auto", "Automobile"],
  ["architecture", "Architecture"], ["mode", "Mode"], ["beaute", "Beauté"], ["sante", "Santé"], ["droit", "Droit"],
  ["finance", "Finance"], ["tech", "Tech / SaaS"], ["education", "Éducation"], ["sport", "Sport"], ["voyage", "Voyage"],
  ["maison", "Maison / Design"], ["joaillerie", "Joaillerie"], ["food", "Food / Épicerie"], ["spa", "Spa / Wellness"], ["construction", "Construction"],
] as const;
