import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Check, Search, Sparkles, TrendingUp } from "lucide-react";
import { Nav } from "@/components/site/Nav";
import { Contact } from "@/components/site/Contact";

export const Route = createFileRoute("/services/seo")({
  head: () => ({ meta: [{ title: "SEO — Référencement naturel | XR Agency" }, { name: "description", content: "Stratégie SEO transparente pour gagner en visibilité sur Google et attirer une demande qualifiée." }] }),
  component: SeoPage,
});

const plans = [
  { name: "SEO Local", price: 299, label: "/ mois", features: ["Audit technique & sémantique", "Recherche de mots-clés à intention commerciale", "Optimisation des pages prioritaires", "Suivi mensuel des positions", "Rapport clair et recommandations"] },
  { name: "SEO Growth", price: 499, label: "/ mois", features: ["Tout le SEO Local", "Stratégie éditoriale", "Optimisations continues", "Développement de l'autorité", "Reporting et pilotage mensuel"] },
  { name: "SEO Authority", price: 799, label: "/ mois", features: ["Stratégie SEO complète", "Architecture sémantique avancée", "Contenus stratégiques", "Autorité & netlinking selon opportunités", "Pilotage prioritaire"] },
];

function SeoPage() {
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground"><Nav /><main className="pt-28"><section className="relative overflow-hidden border-b border-border/60 py-16 sm:py-24 lg:py-32"><div className="absolute inset-0 bg-[radial-gradient(circle_at_70%_20%,hsl(var(--primary)/.13),transparent_38%)]" /><div className="relative mx-auto grid max-w-7xl gap-10 px-5 lg:grid-cols-[1.05fr_.95fr] lg:px-10 lg:items-end"><div><span className="label-mono text-[10px] uppercase tracking-[0.25em] text-primary">XR AGENCY · 03 · SEO</span><h1 className="display-serif mt-6 text-[clamp(3.2rem,8vw,7rem)] leading-[.86]">Être trouvé.<br/><em className="not-italic italic text-primary">Au bon moment.</em></h1><p className="mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">Une stratégie SEO lisible, progressive et orientée business. Nous travaillons les recherches qui peuvent réellement générer des demandes, des rendez-vous et des ventes.</p><div className="mt-8 flex flex-wrap gap-3"><a href="#plans" className="inline-flex items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-[10px] font-semibold uppercase tracking-widest text-primary-foreground">Voir les formules <ArrowRight className="h-4 w-4" /></a><Link to="/#quote" className="inline-flex items-center gap-2 rounded-full border border-border bg-card/70 px-6 py-3.5 text-[10px] font-semibold uppercase tracking-widest">Analyser mon activité</Link></div></div><div className="relative min-h-[330px] overflow-hidden rounded-[2rem] border border-border bg-card shadow-2xl"><div className="absolute inset-0 bg-[linear-gradient(135deg,transparent_0%,hsl(var(--primary)/.06)_45%,transparent_100%)]" /><div className="absolute left-6 right-6 top-7 rounded-2xl border border-border bg-background/90 p-5 shadow-xl backdrop-blur"><div className="flex items-center gap-2"><Search className="h-4 w-4 text-primary"/><span className="text-xs font-medium">luxury architects in London</span></div><div className="mt-5 space-y-2"><div className="h-2 w-4/5 rounded-full bg-primary/25"/><div className="h-2 w-3/5 rounded-full bg-muted"/><div className="h-2 w-2/5 rounded-full bg-muted"/></div></div><div className="absolute bottom-7 left-7 flex items-center gap-3 rounded-2xl border border-border bg-background/90 px-4 py-3 shadow-xl backdrop-blur"><TrendingUp className="h-4 w-4 text-primary"/><span className="text-xs">Visibilité · Autorité · Conversion</span></div></div></div></section>
    <section className="border-b border-border/60 py-16 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-3 md:grid-cols-3">{[["01","Fondations","Audit technique, structure et intention de recherche."],["02","Optimisation","Pages, contenus et maillage pensés pour Google et les visiteurs."],["03","Autorité","Suivi, contenus et signaux externes selon les opportunités."]].map(([num,title,desc]) => <div key={num} className="group rounded-[1.5rem] border border-border bg-card/50 p-6 transition-all hover:-translate-y-1 hover:border-primary/40"><span className="label-mono text-[9px] text-primary">{num}</span><h2 className="display-serif mt-8 text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p></div>)}</div></div></section>
    <section id="plans" className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span className="label-mono text-[10px] uppercase tracking-[0.25em] text-primary">Les formules</span><h2 className="display-serif mt-4 text-4xl sm:text-6xl">Un niveau de SEO adapté à votre ambition.</h2></div><div className="max-w-md text-sm leading-6 text-muted-foreground">Les montants sont des points de départ. La stratégie finale est calibrée selon votre marché, votre concurrence et vos objectifs.</div></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{plans.map((plan,index)=><article key={plan.name} className={`relative overflow-hidden rounded-[1.75rem] border p-7 transition-all hover:-translate-y-1 hover:shadow-2xl sm:p-8 ${index===1?"border-primary/50 bg-primary/[0.05]":"border-border bg-card/60"}`}><div className="flex items-center justify-between"><span className="label-mono text-[9px] text-primary">0{index+1}</span>{index===1&&<span className="label-mono rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-[8px] text-primary">RECOMMANDÉ</span>}</div><h3 className="display-serif mt-7 text-3xl">{plan.name}</h3><div className="mt-6 flex items-end gap-2 border-y border-border py-5"><span className="display-serif text-5xl text-primary">{plan.price} €</span><span className="label-mono mb-1 text-[9px] text-muted-foreground">{plan.label}</span></div><ul className="mt-6 space-y-3">{plan.features.map((feature)=><li key={feature} className="flex gap-3 text-sm leading-5 text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{feature}</li>)}</ul><a href={`https://wa.me/33767566783?text=${encodeURIComponent(`Bonjour XR Agency, je souhaite parler du forfait SEO « ${plan.name} » à ${plan.price} €/mois.`)}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary px-5 py-3.5 text-[10px] font-semibold uppercase tracking-wider text-primary-foreground">Parler à Alexandre <Sparkles className="h-4 w-4"/></a></article>)}</div></div></section>
    <section className="border-t border-border/60 py-16"><div className="mx-auto max-w-4xl px-5 text-center"><Sparkles className="mx-auto h-5 w-5 text-primary"/><h2 className="display-serif mt-4 text-4xl sm:text-5xl">Le SEO n'est pas un bouton. C'est un actif.</h2><p className="mx-auto mt-5 max-w-2xl text-sm leading-7 text-muted-foreground">Nous construisons une visibilité qui continue de travailler pour votre entreprise dans le temps, avec des indicateurs compréhensibles et des actions concrètes.</p></div></section>
  </main><Contact /></div>;
}
