import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronDown, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { useState, type ReactNode } from "react";
import { useLang, type Lang } from "@/lib/i18n";
import { Nav } from "@/components/site/Nav";

export const Route = createFileRoute("/services/seo")({ component: SEOPage });

type Copy = Record<Lang, string>;
type Plan = { name: Copy; price: Copy; period: Copy; audience: Copy; features: Copy[]; popular?: boolean; annual?: boolean };
const c = (fr: string, en: string, vi: string): Copy => ({ fr, en, vi });

const monthly: Plan[] = [
  {
    name: c("SEO Foundation", "SEO Foundation", "SEO Foundation"), price: c("499 €", "$647", "11 000 000 ₫"), period: c("/ mois", "/ month", "/ tháng"),
    audience: c("Les fondations solides pour commencer à gagner en visibilité.", "A solid SEO foundation for businesses ready to become visible.", "Nền tảng SEO vững chắc để bắt đầu tăng khả năng hiển thị."),
    features: [c("Audit SEO complet initial", "Full initial SEO audit", "Audit SEO tổng thể ban đầu"), c("Audit technique & indexation", "Technical & indexing audit", "Audit kỹ thuật & lập chỉ mục"), c("Recherche de mots-clés", "Keyword research", "Nghiên cứu từ khóa"), c("Analyse des concurrents", "Competitor analysis", "Phân tích đối thủ"), c("Mapping des mots-clés", "Keyword mapping", "Lập bản đồ từ khóa"), c("Optimisation on-page", "On-page optimisation", "Tối ưu on-page"), c("Métadonnées & structure Hn", "Metadata & heading structure", "Metadata & cấu trúc heading"), c("Maillage interne", "Internal linking", "Liên kết nội bộ"), c("Search Console & indexation", "Search Console & indexing", "Search Console & indexation"), c("Rapport mensuel", "Monthly report", "Báo cáo hàng tháng")],
  },
  {
    name: c("SEO Growth", "SEO Growth", "SEO Growth"), price: c("999 €", "$1,294", "22 000 000 ₫"), period: c("/ mois", "/ month", "/ tháng"), popular: true,
    audience: c("Notre formule la plus populaire pour générer du trafic qualifié et des leads.", "Our most popular plan for qualified traffic and leads.", "Gói phổ biến nhất để tăng traffic chất lượng và lead."),
    features: [c("Tout SEO Foundation", "Everything in SEO Foundation", "Tất cả tính năng SEO Foundation"), c("Recherche de mots-clés avancée", "Advanced keyword research", "Nghiên cứu từ khóa nâng cao"), c("Analyse concurrentielle avancée", "Advanced competitor analysis", "Phân tích đối thủ nâng cao"), c("Stratégie éditoriale mensuelle", "Monthly content strategy", "Chiến lược nội dung hàng tháng"), c("Jusqu'à 4 contenus SEO / mois", "Up to 4 SEO content assets / month", "Tối đa 4 nội dung SEO / tháng"), c("Optimisation des pages commerciales", "Commercial page optimisation", "Tối ưu trang thương mại"), c("SEO local & Google Business Profile", "Local SEO & Google Business Profile", "Local SEO & Google Business Profile"), c("Stratégie Google Maps", "Google Maps strategy", "Chiến lược Google Maps"), c("Stratégie d'autorité & backlinks", "Authority & backlink strategy", "Chiến lược authority & backlink"), c("Schema & optimisation technique", "Schema & technical optimisation", "Schema & tối ưu kỹ thuật"), c("Analyse trafic, positions & conversions", "Traffic, rankings & conversion analysis", "Phân tích traffic, rankings & conversion"), c("Point stratégique mensuel", "Monthly strategy call", "Buổi chiến lược hàng tháng")],
  },
  {
    name: c("SEO Domination", "SEO Domination", "SEO Domination"), price: c("1 999 €", "$2,591", "44 000 000 ₫"), period: c("/ mois", "/ month", "/ tháng"),
    audience: c("Pour les marchés compétitifs où Google est directement lié au chiffre d'affaires.", "For competitive markets where Google visibility directly impacts revenue.", "Dành cho thị trường cạnh tranh nơi Google tác động trực tiếp đến doanh thu."),
    features: [c("Tout SEO Growth", "Everything in SEO Growth", "Tất cả tính năng SEO Growth"), c("SEO technique avancé", "Advanced technical SEO", "SEO kỹ thuật nâng cao"), c("Jusqu'à 8 contenus SEO / mois", "Up to 8 SEO content assets / month", "Tối đa 8 nội dung SEO / tháng"), c("Landing pages commerciales avancées", "Advanced commercial landing pages", "Landing pages thương mại nâng cao"), c("Google Maps & Local SEO avancé", "Advanced Google Maps & Local SEO", "Google Maps & Local SEO nâng cao"), c("Campagne d'autorité & backlinks", "Authority & backlink campaign", "Chiến dịch authority & backlink"), c("Backlink intelligence concurrentielle", "Competitor backlink intelligence", "Phân tích backlink đối thủ"), c("Content gap & SERP gap", "Content gap & SERP gap", "Content gap & SERP gap"), c("SEO international & multi-localisation", "International & multi-location SEO", "SEO quốc tế & đa địa điểm"), c("Optimisation avancée de conversion", "Advanced conversion optimisation", "Tối ưu chuyển đổi nâng cao"), c("Suivi hebdomadaire", "Weekly ranking monitoring", "Theo dõi ranking hàng tuần"), c("Stratège SEO dédié", "Dedicated SEO strategist", "SEO strategist riêng"), c("Support prioritaire", "Priority support", "Hỗ trợ ưu tiên")],
  },
];

const annual: Plan[] = [
  {
    name: c("SEO Accelerator", "SEO Accelerator", "SEO Accelerator"), price: c("9 900 €", "$12,852", "217 800 000 ₫"), period: c("/ an", "/ year", "/ năm"), annual: true,
    audience: c("12 mois pour construire un véritable actif SEO et capitaliser sur chaque mois précédent.", "12 months to build a compounding organic acquisition asset.", "12 tháng để xây dựng tài sản acquisition organic tăng trưởng theo thời gian."),
    features: [c("Tout le système SEO Growth", "Everything in the SEO Growth system", "Toàn bộ hệ thống SEO Growth"), c("5 contenus SEO / mois", "5 SEO content assets / month", "5 nội dung SEO / tháng"), c("SEO local + Google Maps", "Local SEO + Google Maps", "Local SEO + Google Maps"), c("Stratégie d'autorité & backlinks", "Authority & backlink strategy", "Chiến lược authority & backlink"), c("Optimisation conversion", "Conversion optimisation", "Tối ưu chuyển đổi"), c("Reporting & stratégie mensuels", "Monthly reporting & strategy", "Báo cáo & chiến lược hàng tháng"), c("Audit SEO approfondi trimestriel", "Quarterly deep-dive SEO audit", "Audit SEO chuyên sâu hàng quý"), c("Roadmap SEO annuelle", "Annual SEO roadmap", "Roadmap SEO hàng năm"), c("Intelligence concurrentielle avancée", "Advanced competitor intelligence", "Competitive intelligence nâng cao"), c("Stratège SEO dédié", "Dedicated SEO strategist", "SEO strategist riêng"), c("Économie vs Growth mensuel", "Savings vs monthly Growth", "Tiết kiệm so với Growth hàng tháng")],
  },
  {
    name: c("SEO Domination Annual", "SEO Domination Annual", "SEO Domination Annual"), price: c("19 900 €", "$25,812", "437 800 000 ₫"), period: c("/ an", "/ year", "/ năm"), annual: true,
    audience: c("Notre programme le plus complet pour faire de Google un canal d'acquisition stratégique.", "Our most complete programme for turning Google into a strategic acquisition channel.", "Chương trình toàn diện nhất để biến Google thành kênh acquisition chiến lược."),
    features: [c("Tout SEO Accelerator", "Everything in SEO Accelerator", "Tất cả tính năng SEO Accelerator"), c("Jusqu'à 10 contenus SEO / mois", "Up to 10 SEO content assets / month", "Tối đa 10 nội dung SEO / tháng"), c("SEO international & multi-location", "International & multi-location SEO", "SEO quốc tế & đa địa điểm"), c("Gestion Google Business Profile", "Google Business Profile management", "Quản lý Google Business Profile"), c("Backlink & authority premium", "Premium backlink & authority", "Backlink & authority premium"), c("Digital PR opportunities", "Digital PR opportunities", "Cơ hội Digital PR"), c("Competitor backlink intelligence", "Competitor backlink intelligence", "Competitive backlink intelligence"), c("Content gap & SERP gap", "Content gap & SERP gap", "Content gap & SERP gap"), c("Suivi hebdomadaire positions & performance", "Weekly rankings & performance monitoring", "Theo dõi ranking & performance hàng tuần"), c("Revue stratégique trimestrielle", "Quarterly strategy review", "Review chiến lược hàng quý"), c("Consulting stratégique prioritaire", "Priority strategic consulting", "Tư vấn chiến lược ưu tiên"), c("Économie vs Domination mensuel", "Savings vs monthly Domination", "Tiết kiệm so với Domination hàng tháng")],
  },
];

function CTA({ children, href = "/#quote", secondary = false }: { children: ReactNode; href?: string; secondary?: boolean }) {
  return <a href={href} className={`group inline-flex items-center justify-center gap-2 rounded-full px-6 py-3.5 text-xs font-semibold uppercase tracking-[0.14em] transition-all ${secondary ? "border border-border bg-card/50 text-foreground hover:border-primary/50 hover:bg-primary/5" : "bg-primary text-primary-foreground shadow-lg shadow-primary/20 hover:-translate-y-0.5 hover:shadow-xl hover:shadow-primary/25"}`}>{children}<ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" /></a>;
}

function FeatureList({ features, t }: { features: Copy[]; t: (v: Copy) => string }) {
  return <ul className="space-y-3">{features.map((feature, i) => <li key={i} className="flex gap-2.5 text-sm leading-5 text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{t(feature)}</li>)}</ul>;
}

function PlanCard({ plan, t, lang }: { plan: Plan; t: (v: Copy) => string; lang: Lang }) {
  return <article className={`relative flex h-full flex-col rounded-3xl border p-6 sm:p-8 ${plan.popular ? "border-primary/60 bg-primary/[0.05] shadow-2xl shadow-primary/10" : "border-border bg-card/40"}`}>
    {plan.popular && <div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1.5 text-xs font-bold uppercase tracking-[0.16em] text-primary-foreground">{t(c("Le plus choisi", "Most popular", "Phổ biến nhất"))}</div>}
    {plan.annual && <div className="mb-4 inline-flex w-fit rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-primary">{t(c("Engagement annuel", "Annual programme", "Chương trình hàng năm"))}</div>}
    <h3 className="text-2xl font-semibold tracking-tight">{t(plan.name)}</h3>
    <p className="mt-3 min-h-[48px] text-sm leading-6 text-muted-foreground">{t(plan.audience)}</p>
    <div className="mt-6 flex items-end gap-1 border-b border-border/70 pb-6"><span className="text-4xl font-semibold tracking-tight">{plan.price[lang]}</span><span className="pb-1 text-sm text-muted-foreground">{t(plan.period)}</span></div>
    <div className="mt-6 flex-1"><FeatureList features={plan.features} t={t} /></div>
    <CTA href="/#quote">{t(c("Choisir cette formule", "Choose this plan", "Chọn gói này"))}</CTA>
  </article>;
}

function SEOPage() {
  const { t, lang } = useLang();
  const [openFaq, setOpenFaq] = useState<number | null>(null);
  const faq = [
    [c("Combien de temps faut-il pour voir des résultats ?", "How long does SEO take to show results?", "Bao lâu để thấy kết quả SEO?"), c("Le SEO est cumulatif. Nous cherchons des gains mesurables dès les premières phases, puis renforçons progressivement contenu, autorité et positions.", "SEO compounds. We look for measurable progress early, then progressively build content, authority and rankings.", "SEO tích lũy theo thời gian. Chúng tôi tìm kiếm tiến bộ có thể đo lường sớm rồi tăng dần content, authority và rankings.")],
    [c("Pouvez-vous garantir la première position Google ?", "Can you guarantee the #1 Google position?", "Bạn có thể đảm bảo vị trí #1 Google không?"), c("Non. Une agence sérieuse ne peut pas garantir une position Google précise. Nous garantissons une stratégie structurée, un travail documenté et un suivi transparent.", "No. No serious agency can guarantee a specific Google ranking. We guarantee structured execution, transparent reporting and a clear strategy.", "Không. Không agency nghiêm túc nào có thể đảm bảo một vị trí Google cụ thể. Chúng tôi đảm bảo chiến lược rõ ràng, triển khai có hệ thống và báo cáo minh bạch.")],
    [c("Pourquoi choisir un plan annuel ?", "Why choose an annual plan?", "Tại sao nên chọn gói hàng năm?"), c("Parce que les résultats SEO se construisent dans le temps. 12 mois permettent de capitaliser sur chaque contenu, signal d'autorité et donnée de conversion.", "Because SEO compounds over time. 12 months lets every piece of content, authority signal and conversion insight reinforce the next.", "Vì SEO tích lũy theo thời gian. 12 tháng cho phép content, authority signals và dữ liệu conversion hỗ trợ lẫn nhau.")],
    [c("SEO remplace-t-il Google Ads ?", "Does SEO replace Google Ads?", "SEO có thay thế Google Ads không?"), c("Non. Ils se complètent. Le SEO construit un actif organique à long terme tandis que le paid search permet d'acheter de la demande immédiatement.", "No. They complement each other. SEO builds a long-term organic asset while paid search buys demand immediately.", "Không. Hai kênh bổ trợ nhau. SEO xây dựng tài sản organic dài hạn còn paid search mua nhu cầu ngay lập tức.")],
  ];

  return <div className="min-h-screen bg-background text-foreground"><Nav /><main>
    <section className="relative overflow-hidden border-b border-border/60 py-12 sm:py-16 lg:py-24" style={{ "--service-tint": "#6f9bd1" } as React.CSSProperties}>
      <div aria-hidden className="absolute inset-0 -z-10" style={{ background: "radial-gradient(55% 55% at 70% 20%, color-mix(in srgb, var(--service-tint) 18%, transparent), transparent 72%)" }} />
      <div className="mx-auto max-w-7xl px-5 sm:px-8">
        <div className="grid overflow-hidden rounded-[2rem] border border-primary/45 bg-card/60 shadow-2xl lg:grid-cols-[1.05fr_.95fr]">
          <div className="flex flex-col justify-end p-6 sm:p-10 lg:p-14">
            <span className="label-mono text-sm uppercase tracking-[0.2em] text-primary">XR AGENCY · 03 · SEO</span>
            <h1 className="display-serif mt-5 max-w-4xl text-[clamp(3rem,7vw,6.8rem)] leading-[0.88]">{t(c("Transformez Google en canal d'acquisition.", "Turn Google into an acquisition channel.", "Biến Google thành kênh thu hút khách hàng."))}</h1>
            <p className="mt-7 max-w-2xl text-base leading-7 text-foreground/80 sm:text-lg">{t(c("Plus de visibilité. Plus de trafic qualifié. Plus de demandes. Une stratégie SEO conçue pour produire un actif commercial durable.", "More visibility. More qualified traffic. More enquiries. An SEO system designed to build a durable commercial asset.", "Tăng visibility. Tăng traffic chất lượng. Tăng lead. Một hệ thống SEO được thiết kế để xây dựng tài sản thương mại bền vững."))}</p>
            <div className="mt-7 grid gap-2 sm:grid-cols-3">{[c("Audit SEO complet initial", "Full initial SEO audit", "Audit SEO tổng thể ban đầu"), c("Recherche de mots-clés", "Keyword research", "Nghiên cứu từ khóa"), c("SEO local & Google Business Profile", "Local SEO & Google Business Profile", "Local SEO & Google Business Profile")].map((proof, i) => <div key={i} className="rounded-xl border border-border/70 bg-background/45 px-3 py-3 text-sm leading-5 backdrop-blur"><span className="mb-2 block h-px w-7 bg-primary" />{t(proof)}</div>)}</div>
            <div className="mt-9 flex flex-wrap gap-3"><a href="/#quote" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-semibold uppercase tracking-[0.1em] text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:-translate-y-0.5">Composer mon devis <ArrowRight className="h-4 w-4" /></a><a href="https://wa.me/33767566783" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-border bg-background/60 px-5 py-3.5 text-sm font-semibold transition-all hover:border-primary hover:text-primary">WhatsApp <ArrowRight className="h-4 w-4" /></a></div>
          </div>
          <div className="relative min-h-[360px] overflow-hidden border-t border-primary/25 lg:border-l lg:border-t-0"><img src="https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1800&q=88" alt="SEO analytics" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent" /><div className="absolute inset-4 rounded-[1.5rem] border border-white/20" /></div>
        </div>
      </div>
    </section>

    <section className="border-b border-border/60 py-16 sm:py-20"><div className="mx-auto grid max-w-6xl gap-6 px-5 sm:grid-cols-3 sm:px-8"><div className="rounded-2xl border border-border bg-card/30 p-6"><Search className="h-5 w-5 text-primary" /><h2 className="mt-4 font-semibold">{t(c("Être trouvé", "Be found", "Được tìm thấy"))}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{t(c("Nous ciblons les recherches qui comptent vraiment pour votre activité.", "Target the searches that actually matter to your business.", "Tập trung vào những tìm kiếm thực sự quan trọng với doanh nghiệp."))}</p></div><div className="rounded-2xl border border-border bg-card/30 p-6"><TrendingUp className="h-5 w-5 text-primary" /><h2 className="mt-4 font-semibold">{t(c("Monter dans les résultats", "Climb the rankings", "Tăng thứ hạng"))}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{t(c("Technique, contenu, autorité et données travaillent ensemble.", "Technical SEO, content, authority and data work together.", "Technical SEO, content, authority và dữ liệu hoạt động cùng nhau."))}</p></div><div className="rounded-2xl border border-border bg-card/30 p-6"><Sparkles className="h-5 w-5 text-primary" /><h2 className="mt-4 font-semibold">{t(c("Convertir le trafic", "Convert traffic", "Chuyển đổi traffic"))}</h2><p className="mt-2 text-sm leading-6 text-muted-foreground">{t(c("Le SEO ne s'arrête pas au clic : nous optimisons le parcours vers la demande.", "SEO does not stop at the click: we optimise the path to enquiry.", "SEO không dừng ở click: chúng tôi tối ưu hành trình đến lead."))}</p></div></div></section>

    <section id="plans" className="scroll-mt-24 py-20 sm:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="mb-12 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">01 / MONTHLY</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">{t(c("Choisissez votre niveau d'accélération.", "Choose your growth level.", "Chọn cấp độ tăng trưởng."))}</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">{t(c("Commencez au niveau adapté à votre marché. Upgradez quand vos ambitions et vos résultats augmentent.", "Start at the level that fits your market. Upgrade as your ambitions and results grow.", "Bắt đầu ở cấp độ phù hợp. Nâng cấp khi tham vọng và kết quả tăng lên."))}</p></div><div className="grid gap-5 lg:grid-cols-3">{monthly.map((plan) => <PlanCard key={plan.name.fr} plan={plan} t={t} lang={lang} />)}</div></div></section>

    <section className="border-y border-primary/20 bg-primary/[0.035] py-20 sm:py-24"><div className="mx-auto max-w-7xl px-5 sm:px-8"><div className="mb-10 max-w-3xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">02 / ANNUAL</p><h2 className="mt-3 text-4xl font-semibold tracking-tight sm:text-5xl">{t(c("Construisez un actif SEO sur 12 mois.", "Build your SEO asset over 12 months.", "Xây dựng tài sản SEO trong 12 tháng."))}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{t(c("Les programmes annuels sont conçus pour maximiser la capitalisation entre contenu, autorité, rankings et conversion.", "Annual programmes maximise the compounding effect between content, authority, rankings and conversion.", "Chương trình hàng năm tối đa hóa hiệu ứng tích lũy giữa content, authority, rankings và conversion."))}</p></div><div className="grid gap-5 lg:grid-cols-2">{annual.map((plan) => <PlanCard key={plan.name.fr} plan={plan} t={t} lang={lang} />)}</div></div></section>

    <section className="py-20 sm:py-28"><div className="mx-auto max-w-6xl px-5 sm:px-8"><div className="rounded-3xl border border-border bg-card/40 p-7 sm:p-10"><div className="flex flex-col gap-8 lg:flex-row lg:items-center lg:justify-between"><div className="max-w-2xl"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">FREE SEO AUDIT</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">{t(c("Avant d'acheter, voyez ce qui bloque votre croissance.", "Before you buy, see what is blocking your growth.", "Trước khi mua, hãy xem điều gì đang cản trở tăng trưởng."))}</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">{t(c("Nous analysons votre visibilité, vos concurrents, vos opportunités de mots-clés et vos priorités techniques. Vous recevez ensuite une recommandation claire.", "We analyse visibility, competitors, keyword opportunities and technical priorities, then give you a clear recommendation.", "Chúng tôi phân tích visibility, đối thủ, cơ hội từ khóa và ưu tiên kỹ thuật rồi đưa ra đề xuất rõ ràng."))}</p></div><CTA href="/#quote">{t(c("Demander l'audit gratuit", "Request the free audit", "Yêu cầu audit miễn phí"))}</CTA></div></div></div></section>

    <section className="border-t border-border/60 py-20 sm:py-24"><div className="mx-auto max-w-4xl px-5 sm:px-8"><div className="text-center"><p className="text-xs font-semibold uppercase tracking-[0.2em] text-primary">FAQ</p><h2 className="mt-3 text-3xl font-semibold">{t(c("Questions fréquentes", "Frequently asked questions", "Câu hỏi thường gặp"))}</h2></div><div className="mt-10 divide-y divide-border rounded-2xl border border-border">{faq.map(([question, answer], i) => <div key={i}><button type="button" onClick={() => setOpenFaq(openFaq === i ? null : i)} className="flex w-full items-center justify-between gap-6 p-5 text-left text-sm font-medium"><span>{t(question)}</span><ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${openFaq === i ? "rotate-180 text-primary" : ""}`} /></button>{openFaq === i && <div className="px-5 pb-5 text-sm leading-7 text-muted-foreground">{t(answer)}</div>}</div>)}</div></div></section>

    <section className="px-5 pb-24 pt-8 sm:px-8"><div className="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-primary/30 bg-primary p-8 text-center text-primary-foreground shadow-2xl shadow-primary/15 sm:p-12"><h2 className="text-3xl font-semibold tracking-tight sm:text-5xl">{t(c("Votre prochain client vous cherche déjà.", "Your next customer is already searching.", "Khách hàng tiếp theo của bạn đang tìm kiếm."))}</h2><p className="mx-auto mt-4 max-w-2xl text-sm leading-6 opacity-85">{t(c("La question n'est pas de savoir si vos clients cherchent. C'est de savoir s'ils vous trouvent, ou trouvent votre concurrent.", "The question is not whether customers search. It is whether they find you or your competitor.", "Vấn đề không phải khách hàng có tìm kiếm hay không. Mà là họ tìm thấy bạn hay đối thủ."))}</p><div className="mt-8"><a href="/#quote" className="group inline-flex items-center gap-2 rounded-full bg-background px-7 py-4 text-xs font-bold uppercase tracking-[0.15em] text-foreground transition-transform hover:-translate-y-0.5">{t(c("Construire ma stratégie SEO", "Build my SEO strategy", "Xây dựng chiến lược SEO"))}<ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" /></a></div></div></section>
  </main></div>;
}
