import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, ChevronDown, Search, ShieldCheck, Sparkles, TrendingUp } from "lucide-react";
import { useState } from "react";
import { useLang } from "@/lib/i18n";
import { Nav } from "@/components/site/Nav";

export const Route = createFileRoute("/services/seo")({ component: SEOPage });

type Lang = "fr" | "en" | "vi";
type Copy = Record<Lang, string>;

type Plan = {
  name: Copy;
  price: Copy;
  period: Copy;
  audience: Copy;
  features: Copy[];
  popular?: boolean;
  annual?: boolean;
};

const c = (fr: string, en: string, vi: string): Copy => ({ fr, en, vi });

const monthly: Plan[] = [
  {
    name: c("SEO Foundation", "SEO Foundation", "SEO Foundation"), price: c("499 €", "$647", "11 000 000 ₫"), period: c("/ mois", "/ month", "/ tháng"),
    audience: c("Les fondations solides pour commencer à gagner en visibilité.", "A solid SEO foundation for businesses ready to become visible.", "Nền tảng SEO vững chắc để bắt đầu tăng khả năng hiển thị."),
    features: [c("Audit SEO complet initial", "Full initial SEO audit", "Audit SEO tổng thể ban đầu"), c("Audit technique & indexation", "Technical & indexing audit", "Audit kỹ thuật & lập chỉ mục"), c("Recherche de mots-clés", "Keyword research", "Nghiên cứu từ khóa"), c("Analyse des concurrents", "Competitor analysis", "Phân tích đối thủ"), c("Mapping des mots-clés", "Keyword mapping", "Lập bản đồ từ khóa"), c("Optimisation on-page", "On-page optimisation", "Tối ưu on-page"), c("Optimisation des métadonnées", "Metadata optimisation", "Tối ưu metadata"), c("Structure Hn & maillage interne", "Heading structure & internal linking", "Cấu trúc heading & liên kết nội bộ"), c("Suivi Search Console & indexation", "Search Console & indexing monitoring", "Theo dõi Search Console & indexation"), c("Rapport mensuel", "Monthly performance report", "Báo cáo hiệu suất hàng tháng")],
  },
  {
    name: c("SEO Growth", "SEO Growth", "SEO Growth"), price: c("999 €", "$1,294", "22 000 000 ₫"), period: c("/ mois", "/ month", "/ tháng"), popular: true,
    audience: c("Notre formule la plus populaire pour générer du trafic qualifié et des leads.", "Our most popular plan for consistent organic growth and qualified leads.", "Gói phổ biến nhất để tăng trưởng organic ổn định và tạo lead chất lượng."),
    features: [c("Tout SEO Foundation", "Everything in SEO Foundation", "Tất cả tính năng SEO Foundation"), c("Recherche de mots-clés avancée", "Advanced keyword research", "Nghiên cứu từ khóa nâng cao"), c("Analyse concurrentielle avancée", "Advanced competitor analysis", "Phân tích đối thủ nâng cao"), c("Stratégie éditoriale mensuelle", "Monthly content strategy", "Chiến lược nội dung hàng tháng"), c("Jusqu'à 4 contenus SEO / mois", "Up to 4 SEO content assets / month", "Tối đa 4 nội dung SEO / tháng"), c("Optimisation des pages commerciales", "Commercial landing-page optimisation", "Tối ưu landing pages thương mại"), c("SEO local & Google Business Profile", "Local SEO & Google Business Profile", "Local SEO & Google Business Profile"), c("Stratégie Google Maps", "Google Maps strategy", "Chiến lược Google Maps"), c("Stratégie d'autorité & backlinks", "Authority & backlink strategy", "Chiến lược authority & backlink"), c("Schema & optimisation technique", "Schema & technical optimisation", "Schema & tối ưu kỹ thuật"), c("Analyse trafic, positions & conversions", "Traffic, rankings & conversion analysis", "Phân tích traffic, rankings & conversion"), c("Point stratégique mensuel", "Monthly strategy call", "Buổi chiến lược hàng tháng")],
  },
  {
    name: c("SEO Domination", "SEO Domination", "SEO Domination"), price: c("1 999 €", "$2,591", "44 000 000 ₫"), period: c("/ mois", "/ month", "/ tháng"),
    audience: c("Pour les marchés compétitifs où la visibilité Google est directement liée au chiffre d'affaires.", "For competitive markets where Google visibility directly impacts revenue.", "Dành cho thị trường cạnh tranh nơi visibility trên Google tác động trực tiếp đến doanh thu."),
    features: [c("Tout SEO Growth", "Everything in SEO Growth", "Tất cả tính năng SEO Growth"), c("SEO technique avancé", "Advanced technical SEO", "SEO kỹ thuật nâng cao"), c("Jusqu'à 8 contenus SEO / mois", "Up to 8 SEO content assets / month", "Tối đa 8 nội dung SEO / tháng"), c("Landing pages commerciales avancées", "Advanced commercial landing pages", "Landing pages thương mại nâng cao"), c("Google Maps & Local SEO avancé", "Advanced Google Maps & Local SEO", "Google Maps & Local SEO nâng cao"), c("Campagne d'autorité & backlinks", "Authority & backlink campaign", "Chiến dịch authority & backlink"), c("Analyse des backlinks concurrents", "Competitor backlink intelligence", "Phân tích backlink đối thủ"), c("Content gap & SERP gap analysis", "Content gap & SERP gap analysis", "Phân tích content gap & SERP gap"), c("SEO international & multi-localisation", "International & multi-location SEO", "SEO quốc tế & đa địa điểm"), c("Optimisation avancée de conversion", "Advanced conversion optimisation", "Tối ưu chuyển đổi nâng cao"), c("Suivi hebdomadaire des positions", "Weekly ranking monitoring", "Theo dõi ranking hàng tuần"), c("Stratège SEO dédié", "Dedicated SEO strategist", "SEO strategist riêng"), c("Support prioritaire", "Priority support", "Hỗ trợ ưu tiên")],
  },
];

const annual: Plan[] = [
  {
    name: c("SEO Accelerator", "SEO Accelerator", "SEO Accelerator"), price: c("9 900 €", "$12,852", "217 800 000 ₫"), period: c("/ an", "/ year", "/ năm"), annual: true,
    audience: c("12 mois pour construire un véritable actif SEO, avec une stratégie qui capitalise sur chaque mois précédent.", "12 months to build a compounding organic acquisition asset.", "12 tháng để xây dựng tài sản acquisition organic tăng trưởng theo thời gian."),
    features: [c("Tout le système SEO Growth", "Everything in the SEO Growth system", "Toàn bộ hệ thống SEO Growth"), c("5 contenus SEO / mois", "5 SEO content assets / month", "5 nội dung SEO / tháng"), c("SEO local + Google Maps", "Local SEO + Google Maps", "Local SEO + Google Maps"), c("Stratégie d'autorité & backlinks", "Authority & backlink strategy", "Chiến lược authority & backlink"), c("Optimisation conversion", "Conversion optimisation", "Tối ưu chuyển đổi"), c("Reporting & stratégie mensuels", "Monthly reporting & strategy", "Báo cáo & chiến lược hàng tháng"), c("Audit SEO approfondi trimestriel", "Quarterly deep-dive SEO audit", "Audit SEO chuyên sâu hàng quý"), c("Roadmap SEO annuelle", "Annual SEO roadmap", "Roadmap SEO hàng năm"), c("Intelligence concurrentielle avancée", "Advanced competitor intelligence", "Competitive intelligence nâng cao"), c("Stratège SEO dédié", "Dedicated SEO strategist", "SEO strategist riêng"), c("Économie vs abonnement mensuel Growth", "Savings vs monthly Growth", "Tiết kiệm so với Growth hàng tháng")],
  },
  {
    name: c("SEO Domination Annual", "SEO Domination Annual", "SEO Domination Annual"), price: c("19 900 €", "$25,812", "437 800 000 ₫"), period: c("/ an", "/ year", "/ năm"), annual: true,
    audience: c("Notre programme le plus complet pour faire de Google un canal d'acquisition stratégique.", "Our most complete programme for turning Google into a strategic acquisition channel.", "Chương trình toàn diện nhất để biến Google thành kênh acquisition chiến lược."),
    features: [c("Tout SEO Accelerator", "Everything in SEO Accelerator", "Tất cả tính năng SEO Accelerator"), c("Jusqu'à 10 contenus SEO / mois", "Up to 10 SEO content assets / month", "Tối đa 10 nội dung SEO / tháng"), c("SEO international & multi-location", "International & multi-location SEO", "SEO quốc tế & đa địa điểm"), c("Google Business Profile management", "Google Business Profile management", "Quản lý Google Business Profile"), c("Backlink & authority premium", "Premium backlink & authority strategy", "Chiến lược backlink & authority premium"), c("Digital PR opportunities", "Digital PR opportunities", "Cơ hội Digital PR"), c("Competitor backlink intelligence", "Competitor backlink intelligence", "Competitive backlink intelligence"), c("Content gap & SERP gap analysis", "Content gap & SERP gap analysis", "Phân tích content gap & SERP gap"), c("Suivi hebdomadaire positions & performance", "Weekly rankings & performance monitoring", "Theo dõi ranking & performance hàng tuần"), c("Revue stratégique trimestrielle", "Quarterly strategy review", "Review chiến lược hàng quý"), c("Consulting stratégique prioritaire", "Priority strategic consulting", "Tư vấn chiến lược ưu tiên"), c("Économie vs Domination mensuel", "Savings vs monthly Domination", "Tiết kiệm so với Domination hàng tháng")],
  },
];

const comparison = [["Audit technique", "✓", "✓", "✓", "✓", "✓"], ["Keyword research", "✓", "Advanced", "Advanced", "Advanced", "Advanced"], ["Content SEO", "—", "4 / mois", "8 / mois", "5 / mois", "10 / mois"], ["Local SEO", "Basic", "Advanced", "Advanced", "Advanced", "Advanced"], ["Google Maps", "Basic", "✓", "✓", "✓", "✓"], ["Authority / backlinks", "—", "Strategy", "Campaign", "Campaign", "Premium"], ["International SEO", "—", "—", "✓", "✓", "✓"], ["Conversion SEO", "—", "✓", "Advanced", "✓", "Advanced"], ["Reporting", "Monthly", "Detailed", "Advanced", "Advanced", "Advanced"], ["Strategist dédié", "—", "—", "✓", "✓", "✓"]];

function CTA({ children, href = "/#quote", secondary = false }: { children: React.ReactNode; href?: string; secondary?: boolean }) { return <a href={href} className={`group inline-flex items-center justify-center gap-2 rounded-full px-6 py-3.5 text-[10px] font-semibold uppercase tracking-[0.14em] transition-all ${secondary ? "border border-border bg-card/50 text-foreground hover:border-primary/50 hover:bg-primary/5" : "bg-primary text-primary-foreground shadow-lg shadow-primary/20 hover:-translate-y-0.5 hover:shadow-xl hover:shadow-primary/25"}`}>{children}<ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-1" /></a>; }
function FeatureList({ features, t }: { features: Copy[]; t: (v: Copy) => string }) { return <ul className="space-y-3">{features.map((feature, i) => <li key={i} className="flex gap-2.5 text-sm leading-5 text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary" />{t(feature)}</li>)}</ul>; }

function SEOPage() {
  const { t, lang } = useLang(); const [openFaq, setOpenFaq] = useState<number | null>(null); const money = (plan: Plan) => plan.price[lang];
  const faq = [c("Combien de temps faut-il pour voir des résultats ?", "How long does SEO take to show results?", "Bao lâu để thấy kết quả SEO?"), c("Pouvez-vous garantir la première position Google ?", "Can you guarantee the #1 Google position?", "Bạn có thể đảm bảo vị trí #1 Google không?"), c("Pourquoi choisir un plan annuel ?", "Why choose an annual plan?", "Tại sao nên chọn gói hàng năm?"), c("SEO remplace-t-il Google Ads ?", "Does SEO replace Google Ads?", "SEO có thay thế Google Ads không?")];
  const answers = [c("Le SEO est cumulatif. Nous cherchons des gains mesurables dès les premières phases, puis nous renforçons progressivement contenu, autorité et positions.", "SEO compounds. We look for measurable progress early, then progressively build content, authority and rankings.", "SEO tích lũy theo thời gian. Chúng tôi tìm kiếm tiến bộ có thể đo lường sớm rồi tăng dần content, authority và rankings."), c("Non. Une agence sérieuse ne peut pas garantir une position Google précise. Nous garantissons en revanche une stratégie structurée, un travail documenté et un suivi transparent.", "No. No serious agency can guarantee a specific Google ranking. We guarantee structured execution, transparent reporting and a clear strategy.", "Không. Không agency nghiêm túc nào có thể đảm bảo một vị trí Google cụ thể. Chúng tôi đảm bảo chiến lược rõ ràng, triển khai có hệ thống và báo cáo minh bạch."), c("Parce que les résultats SEO se construisent dans le temps. Un engagement de 12 mois permet de capitaliser sur chaque contenu, chaque signal d'autorité et chaque donnée de conversion.", "Because SEO compounds over time. A 12-month engagement lets every piece of content, authority signal and conversion insight reinforce the next.", "Vì SEO tích lũy theo thời gian. 12 tháng cho phép content, authority signals và dữ liệu conversion hỗ trợ lẫn nhau."), c("Non. Ils se complètent. Le SEO construit un actif organique à long terme tandis que le paid search permet d'acheter de la demande immédiatement.", "No. They complement each other. SEO builds a long-term organic asset while paid search buys demand immediately.", "Không. Hai kênh bổ trợ nhau. SEO xây dựng tài sản organic dài hạn còn paid search mua nhu cầu ngay lập tức.")];

  return <div className="min-h-screen bg-background text-foreground"><Nav /><main>
    <section className="relative overflow-hidden px-5 pb-20 pt-36 sm:px-8 lg:pb-28 lg:pt-44"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,hsl(var(--primary)/0.13),transparent_42%)]" /><div className="relative mx-auto max-w-[1180px] text-center"><div className="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/5 px-4 py-2 text-[9px] font-semibold uppercase tracking-[0.2em] text-primary"><Sparkles className="h-3.5 w-3.5" /> XR / SEO GROWTH SYSTEM</div><h1 className="mx-auto max-w-5xl text-balance text-5xl font-semibold tracking-[-0.055em] sm:text-6xl lg:text-8xl">{lang === "fr" ? <>Ne payez plus pour chaque clic.<br /><span className="text-primary">Possédez votre visibilité.</span></> : lang === "vi" ? <>Đừng trả tiền cho từng cú click.<br /><span className="text-primary">Hãy sở hữu visibility.</span></> : <>Stop paying for every click.<br /><span className="text-primary">Own your search visibility.</span></>}</h1><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-muted-foreground sm:text-lg">{t(c("Un système SEO complet conçu pour augmenter votre visibilité, votre trafic qualifié et votre chiffre d'affaires — sans dépendre entièrement de Google Ads ou des réseaux sociaux.", "A complete SEO growth system designed to increase visibility, qualified traffic and revenue — without depending entirely on Google Ads or social media.", "Hệ thống SEO toàn diện giúp tăng visibility, traffic chất lượng và doanh thu — không phụ thuộc hoàn toàn vào Google Ads hay social media."))}</p><div className="mt-9 flex flex-col justify-center gap-3 sm:flex-row"><CTA>{t(c("Obtenir mon audit SEO gratuit", "Get my free SEO audit", "Nhận audit SEO miễn phí"))}</CTA><CTA secondary href="#plans">{t(c("Voir les offres", "View SEO plans", "Xem gói SEO"))}</CTA></div><div className="mt-6 text-[9px] uppercase tracking-[0.16em] text-muted-foreground">{t(c("Sans engagement · Sans obligation · Réponse rapide", "No commitment · No obligation · Fast response", "Không cam kết · Không bắt buộc · Phản hồi nhanh"))}</div></div></section>

    <section className="border-y border-border/70 bg-card/20 px-5 py-12 sm:px-8"><div className="mx-auto grid max-w-[1180px] gap-4 md:grid-cols-3">{[[Search,c("Votre client cherche.","Your customer is searching.","Khách hàng đang tìm kiếm."),c("Mais s'il ne vous trouve pas, il trouve votre concurrent.","If they can't find you, they find your competitor.","Nếu không thấy bạn, họ sẽ thấy đối thủ.")],[TrendingUp,c("Le trafic n'est pas le but.","Traffic isn't the goal.","Traffic không phải mục tiêu."),c("Nous construisons de la visibilité là où elle peut devenir des demandes, réservations et ventes.","We build visibility where it can become enquiries, bookings and sales.","Chúng tôi xây dựng visibility nơi nó có thể tạo enquiry, booking và sales.")],[ShieldCheck,c("Pas de promesse magique.","No magic promises.","Không lời hứa viển vông."),c("Une stratégie documentée, des actions réelles et un reporting transparent.","Documented strategy, real execution and transparent reporting.","Chiến lược rõ ràng, triển khai thực tế và báo cáo minh bạch.")]].map(([Icon,title,desc]) => <div key={title.fr} className="rounded-2xl border border-border bg-background/60 p-6"><Icon className="h-5 w-5 text-primary" /><p className="mt-4 text-lg font-medium">{t(title as Copy)}</p><p className="mt-2 text-sm text-muted-foreground">{t(desc as Copy)}</p></div>)}</div></section>

    <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-[1180px]"><div className="max-w-2xl"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">01 / THE SYSTEM</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{t(c("Nous ne faisons pas simplement du SEO.", "We don't just 'do SEO'.", "Chúng tôi không chỉ 'làm SEO'."))}</h2><p className="mt-5 text-muted-foreground">{t(c("Nous construisons un système d'acquisition organique : technique, contenu, autorité, local, Google Maps et conversion travaillent ensemble.", "We build an organic acquisition system: technical SEO, content, authority, local search, Google Maps and conversion work together.", "Chúng tôi xây dựng hệ thống acquisition organic: technical SEO, content, authority, local search, Google Maps và conversion hoạt động cùng nhau."))}</p></div><div className="mt-12 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{[["TECHNICAL SEO","Crawl, indexation, architecture, Core Web Vitals, schema, performance."],["ON-PAGE","Search intent, titles, headings, internal linking and commercial relevance."],["CONTENT","Keyword strategy, landing pages and content built around real search demand."],["LOCAL SEO","Google Business Profile, local relevance, citations and location pages."],["GOOGLE MAPS","A focused local visibility strategy for the map pack and discovery."],["AUTHORITY","Backlink strategy, competitive gaps and relevant authority building."]].map(([title,desc])=><div key={title} className="rounded-2xl border border-border bg-card/30 p-6 transition-all hover:-translate-y-1 hover:border-primary/40"><div className="label-mono text-[9px] tracking-[0.16em] text-primary">{title}</div><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p></div>)}</div></div></section>

    <section id="plans" className="scroll-mt-20 border-y border-border/70 bg-card/20 px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-[1240px]"><div className="text-center"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">02 / CHOOSE YOUR GROWTH LEVEL</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{t(c("Choisissez votre vitesse de croissance.", "Choose your growth velocity.", "Chọn tốc độ tăng trưởng."))}</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">{t(c("Commencez avec les fondations. Accélérez avec Growth. Dominez avec notre système complet.", "Start with the foundation. Accelerate with Growth. Dominate with the complete system.", "Bắt đầu với nền tảng. Tăng tốc với Growth. Dominate với hệ thống toàn diện."))}</p></div><div className="mt-12 grid gap-4 lg:grid-cols-3">{monthly.map(plan=><div key={plan.name.en} className={`relative flex flex-col rounded-3xl border p-7 ${plan.popular?"border-primary bg-primary/[0.055] shadow-2xl shadow-primary/10 lg:-translate-y-3":"border-border bg-background/60"}`}>{plan.popular&&<div className="absolute -top-3 left-1/2 -translate-x-1/2 rounded-full bg-primary px-4 py-1.5 text-[8px] font-bold uppercase tracking-[0.16em] text-primary-foreground">{t(c("LE PLUS POPULAIRE","MOST POPULAR","PHỔ BIẾN NHẤT"))}</div>}<div className="label-mono text-[9px] uppercase tracking-[0.18em] text-primary">{t(plan.name)}</div><div className="mt-5 flex items-end gap-1"><span className="text-4xl font-semibold tracking-tight">{money(plan)}</span><span className="pb-1 text-xs text-muted-foreground">{t(plan.period)}</span></div><p className="mt-4 min-h-[72px] text-sm leading-6 text-muted-foreground">{t(plan.audience)}</p><CTA>{t(c("Choisir cette formule","Choose this plan","Chọn gói này"))}</CTA><div className="my-7 h-px bg-border" /><FeatureList features={plan.features} t={t} /></div>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-[1240px]"><div className="mx-auto max-w-3xl text-center"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">03 / COMPOUNDING ADVANTAGE</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{t(c("Ne louez pas votre visibilité. Construisez-la.", "Don't rent your visibility. Build it.", "Đừng thuê visibility. Hãy xây dựng nó."))}</h2><p className="mt-4 text-muted-foreground">{t(c("Les plans annuels sont conçus pour transformer 12 mois de SEO en un actif qui continue à travailler pour votre entreprise.", "Annual plans turn 12 months of SEO into an acquisition asset that keeps working for your business.", "Gói hàng năm biến 12 tháng SEO thành tài sản acquisition tiếp tục làm việc cho doanh nghiệp."))}</p></div><div className="mt-12 grid gap-5 lg:grid-cols-2">{annual.map((plan,i)=><div key={plan.name.en} className={`relative overflow-hidden rounded-3xl border p-8 ${i===1?"border-primary/50 bg-primary/[0.055]":"border-border bg-card/30"}`}><div className="absolute right-6 top-6 rounded-full border border-primary/30 px-3 py-1 text-[8px] font-bold uppercase tracking-[0.16em] text-primary">{i===1?t(c("MEILLEURE VALEUR","BEST VALUE","GIÁ TRỊ TỐT NHẤT")):t(c("12 MOIS","12 MONTHS","12 THÁNG"))}</div><div className="max-w-lg"><div className="label-mono text-[9px] uppercase tracking-[0.18em] text-primary">{t(plan.name)}</div><div className="mt-5 flex items-end gap-1"><span className="text-4xl font-semibold tracking-tight">{money(plan)}</span><span className="pb-1 text-xs text-muted-foreground">{t(plan.period)}</span></div><div className="mt-3 inline-flex rounded-full border border-primary/20 bg-primary/5 px-3 py-1 text-[9px] font-semibold uppercase tracking-[0.12em] text-primary">{i===0?t(c("2 mois offerts vs Growth mensuel","2 months free vs monthly Growth","Tặng tương đương 2 tháng so với Growth hàng tháng")):t(c("2 mois offerts vs Domination mensuel","2 months free vs monthly Domination","Tặng tương đương 2 tháng so với Domination hàng tháng"))}</div><p className="mt-4 text-sm leading-6 text-muted-foreground">{t(plan.audience)}</p><div className="mt-6"><CTA>{t(c("Construire mon plan 12 mois","Build my 12-month plan","Xây dựng kế hoạch 12 tháng"))}</CTA></div></div><div className="my-7 h-px bg-border" /><div className="grid gap-x-8 gap-y-3 sm:grid-cols-2"><FeatureList features={plan.features} t={t} /></div></div>)}</div></div></section>

    <section className="border-y border-border/70 bg-card/20 px-5 py-20 sm:px-8 lg:py-24"><div className="mx-auto max-w-[1240px]"><div className="text-center"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">04 / COMPARISON</div><h2 className="mt-4 text-3xl font-semibold tracking-[-0.04em] sm:text-4xl">{t(c("Comparez. Puis choisissez votre niveau.", "Compare. Then choose your level.", "So sánh. Sau đó chọn cấp độ."))}</h2></div><div className="mt-10 overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[900px] border-collapse text-left text-sm"><thead><tr className="bg-card"><th className="p-4 font-medium">{t(c("Inclus","Included","Bao gồm"))}</th>{monthly.map(p=><th key={p.name.en} className={`p-4 font-semibold ${p.popular?"text-primary":""}`}>{t(p.name)}</th>)}<th className="p-4 font-semibold text-primary">{t(annual[0].name)}</th><th className="p-4 font-semibold text-primary">{t(annual[1].name)}</th></tr></thead><tbody>{comparison.map(row=><tr key={row[0]} className="border-t border-border"><td className="p-4 font-medium">{row[0]}</td>{row.slice(1).map((cell,i)=><td key={i} className="p-4 text-muted-foreground">{cell}</td>)}</tr>)}</tbody></table></div></div></section>

    <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-[0.9fr_1.1fr] lg:items-center"><div><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">05 / ROI</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em] sm:text-5xl">{t(c("Combien vaut un nouveau client pour vous ?", "What is one new customer worth to you?", "Một khách hàng mới đáng giá bao nhiêu với bạn?"))}</h2><p className="mt-5 text-muted-foreground">{t(c("Si un nouveau client vaut 2 000 € et que votre SEO génère 10 clients supplémentaires par mois, cela représente 20 000 € de chiffre d'affaires potentiel supplémentaire.", "If one customer is worth $2,000 and SEO generates 10 additional customers per month, that's $20,000 in potential additional monthly revenue.", "Nếu một khách hàng trị giá 2.000$ và SEO tạo thêm 10 khách hàng mỗi tháng, đó là 20.000$ doanh thu tiềm năng mỗi tháng."))}</p><div className="mt-7"><CTA>{t(c("Calculer mon potentiel SEO","Calculate my SEO potential","Tính tiềm năng SEO"))}</CTA></div></div><div className="rounded-3xl border border-primary/30 bg-primary/[0.055] p-8 sm:p-10"><div className="text-sm uppercase tracking-[0.14em] text-muted-foreground">{t(c("EXEMPLE","EXAMPLE","VÍ DỤ"))}</div><div className="mt-7 space-y-5"><div className="flex items-center justify-between"><span className="text-muted-foreground">{t(c("Valeur moyenne d'un client","Average customer value","Giá trị trung bình / khách"))}</span><strong className="text-xl">2 000 €</strong></div><div className="flex items-center justify-between"><span className="text-muted-foreground">{t(c("Nouveaux clients / mois","New customers / month","Khách mới / tháng"))}</span><strong className="text-xl">× 10</strong></div><div className="h-px bg-border" /><div className="flex items-center justify-between"><span>{t(c("Potentiel mensuel","Monthly potential","Tiềm năng hàng tháng"))}</span><strong className="text-3xl text-primary">20 000 €</strong></div></div></div></div></section>

    <section className="border-y border-border/70 bg-card/20 px-5 py-20 sm:px-8"><div className="mx-auto max-w-[1000px]"><div className="text-center"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">06 / PROCESS</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em]">{t(c("From invisible to unmissable.","From invisible to unmissable.","Từ invisible đến unmissable."))}</h2></div><div className="mt-12 grid gap-3 md:grid-cols-5">{[["01","AUDIT","Nous identifions ce qui bloque votre croissance."],["02","STRATEGY","Nous ciblons les recherches qui comptent."],["03","OPTIMISE","Nous réparons et renforçons les fondations."],["04","BUILD","Nous construisons contenu et autorité."],["05","DOMINATE","Nous mesurons, ajustons et poussons plus loin."]].map(([num,title,desc])=><div key={num} className="rounded-2xl border border-border bg-background/60 p-5"><span className="label-mono text-[9px] text-primary">{num}</span><h3 className="mt-4 text-sm font-semibold">{title}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{desc}</p></div>)}</div></div></section>

    <section className="px-5 py-20 sm:px-8 lg:py-28"><div className="mx-auto max-w-[900px]"><div className="text-center"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">07 / FAQ</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.04em]">{t(c("Les questions avant de commencer.","Questions before you start.","Những câu hỏi trước khi bắt đầu."))}</h2></div><div className="mt-10 divide-y divide-border rounded-2xl border border-border">{faq.map((q,i)=><div key={i}><button className="flex w-full items-center justify-between gap-6 p-5 text-left" onClick={()=>setOpenFaq(openFaq===i?null:i)}><span className="font-medium">{t(q)}</span><ChevronDown className={`h-4 w-4 shrink-0 transition-transform ${openFaq===i?"rotate-180 text-primary":""}`} /></button>{openFaq===i&&<div className="px-5 pb-5 text-sm leading-6 text-muted-foreground">{t(answers[i])}</div>}</div>)}</div></div></section>

    <section className="relative overflow-hidden border-t border-border px-5 py-24 text-center sm:px-8 lg:py-32"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(circle_at_50%_100%,hsl(var(--primary)/0.16),transparent_48%)]" /><div className="relative mx-auto max-w-4xl"><div className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">08 / START HERE</div><h2 className="mt-5 text-5xl font-semibold tracking-[-0.055em] sm:text-6xl">{t(c("Prêt à être trouvé ?","Ready to be found?","Sẵn sàng để được tìm thấy?"))}</h2><p className="mx-auto mt-5 max-w-2xl text-muted-foreground">{t(c("Découvrez exactement ce qui vous empêche de mieux vous positionner et ce qu'il faudrait pour dépasser vos concurrents.","Find out exactly what is holding your visibility back and what it would take to outrank your competitors.","Tìm hiểu chính xác điều gì đang cản trở visibility của bạn và cần gì để vượt qua đối thủ."))}</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><CTA>{t(c("Obtenir mon audit SEO gratuit","Get my free SEO audit","Nhận audit SEO miễn phí"))}</CTA><CTA secondary href="/#contact">{t(c("Parler à XRAGENCY","Talk to XRAGENCY","Nói chuyện với XRAGENCY"))}</CTA></div><div className="mt-6 text-[9px] uppercase tracking-[0.16em] text-muted-foreground">{t(c("Pas d'engagement · Pas de promesse artificielle · Une stratégie claire","No commitment · No artificial promises · A clear strategy","Không cam kết · Không lời hứa giả tạo · Chiến lược rõ ràng"))}</div></div></section>
  </main></div>;
}
