import { createFileRoute } from "@tanstack/react-router";
import { ArrowRight, Check, LifeBuoy, ShieldCheck, Sparkles, Wrench } from "lucide-react";
import { Nav } from "@/components/site/Nav";
import { Contact } from "@/components/site/Contact";

export const Route = createFileRoute("/services/webcare")({
  head: () => ({ meta: [{ title: "WebCare Maintenance — XR Agency" }, { name: "description", content: "Maintenance, corrections et évolutions courantes de votre site avec trois niveaux d'accompagnement." }] }),
  component: WebCarePage,
});

const plans = [
  { name: "Essentiel", price: 29, badge: "Pour rester à jour", features: ["5 petites modifications / mois", "Corrections de contenu et visuels", "2 interventions techniques / mois", "Sauvegarde mensuelle", "Délai de traitement standard"] },
  { name: "Business", price: 59, badge: "Pour faire évoluer le site", features: ["10 petites modifications / mois", "Corrections de contenu, visuels et sections", "4 interventions techniques / mois", "Sauvegardes mensuelles", "Priorité de traitement", "Conseils d'évolution courante"] },
  { name: "Unlimited", price: 99, badge: "Pour déléguer", features: ["Modifications illimitées dans le périmètre courant", "Corrections de contenu, visuels et sections", "Suivi technique prioritaire", "Sauvegardes et surveillance", "Petites évolutions incluses", "Refontes, fonctionnalités majeures et développements spécifiques sur devis"] },
];

function WebCarePage() {
  return <div className="min-h-screen overflow-x-hidden bg-background text-foreground"><Nav /><main className="pt-28"><section className="relative overflow-hidden border-b border-border/60 py-12 sm:py-16 lg:py-24" style={{ "--service-tint": "#7e93ad" } as React.CSSProperties}>
      <div aria-hidden className="absolute inset-0 -z-10" style={{ background: "radial-gradient(55% 55% at 70% 20%, color-mix(in srgb, var(--service-tint) 18%, transparent), transparent 72%)" }} />
      <div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">
        <div className="grid overflow-hidden rounded-[2rem] border border-primary/45 bg-card/60 shadow-2xl lg:grid-cols-[1.05fr_.95fr]">
          <div className="flex flex-col justify-end p-6 sm:p-10 lg:p-14">
            <span className="label-mono text-sm uppercase tracking-[0.2em] text-primary">XR AGENCY · 06 · WEBCARE</span>
            <h1 className="display-serif mt-5 max-w-4xl text-[clamp(3rem,7vw,6.8rem)] leading-[0.88]">Votre site évolue.<br /><em className="not-italic italic text-primary">Nous aussi.</em></h1>
            <p className="mt-7 max-w-2xl text-base leading-7 text-foreground/80 sm:text-lg">Un abonnement simple pour les modifications, corrections et évolutions courantes. Pas de ticket incompréhensible : vous savez ce qui est inclus et quand passer sur devis.</p>
            <div className="mt-7 grid gap-2 sm:grid-cols-3">{["5 petites modifications / mois", "10 petites modifications / mois", "Sauvegardes et surveillance"].map((proof) => <div key={proof} className="rounded-xl border border-border/70 bg-background/45 px-3 py-3 text-sm leading-5 backdrop-blur"><span className="mb-2 block h-px w-7 bg-primary" />{proof}</div>)}</div>
            <div className="mt-9 flex flex-wrap gap-3"><a href="/#quote" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-primary px-6 py-3.5 text-sm font-semibold uppercase tracking-[0.1em] text-primary-foreground shadow-lg shadow-primary/20 transition-all hover:-translate-y-0.5">Composer mon devis <ArrowRight className="h-4 w-4" /></a><a href="https://wa.me/33767566783" target="_blank" rel="noreferrer" className="inline-flex min-h-12 items-center gap-2 rounded-full border border-border bg-background/60 px-5 py-3.5 text-sm font-semibold transition-all hover:border-primary hover:text-primary">WhatsApp <ArrowRight className="h-4 w-4" /></a></div>
          </div>
          <div className="relative min-h-[360px] overflow-hidden border-t border-primary/25 lg:border-l lg:border-t-0"><img src="https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&w=1800&q=88" alt="WebCare maintenance" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-black/70 via-black/10 to-transparent" /><div className="absolute inset-4 rounded-[1.5rem] border border-white/20" /></div>
        </div>
      </div>
    </section>
    <section className="border-b border-border/60 py-14 sm:py-20"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="grid gap-3 md:grid-cols-3">{[[LifeBuoy,"Corrections","Petites modifications de contenu, visuels et sections."],[Wrench,"Évolutions","Ajustements courants pour que le site reste utile."],[ShieldCheck,"Suivi","Sauvegardes, interventions techniques et priorité selon le plan."]].map(([Icon,title,desc])=>{const I=Icon as typeof LifeBuoy;return <div key={String(title)} className="rounded-[1.5rem] border border-border bg-card/50 p-6 transition-all hover:-translate-y-1 hover:border-primary/40"><I className="h-5 w-5 text-primary"/><h2 className="display-serif mt-6 text-3xl">{title}</h2><p className="mt-3 text-sm leading-6 text-muted-foreground">{desc}</p></div>})}</div></div></section>
    <section id="plans" className="py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 lg:px-10"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><span className="label-mono text-xs uppercase tracking-[0.25em] text-primary">Les formules WebCare</span><h2 className="display-serif mt-4 text-4xl sm:text-6xl">Plus vous déléguez,<br/>plus votre site avance.</h2></div><p className="max-w-md text-sm leading-6 text-muted-foreground">Les petites demandes restent dans le cadre de l'abonnement. Les refontes et développements majeurs sont toujours traités séparément.</p></div><div className="mt-10 grid gap-4 lg:grid-cols-3">{plans.map((plan,index)=><article key={plan.name} className={`rounded-[1.75rem] border p-7 transition-all hover:-translate-y-1 hover:shadow-2xl sm:p-8 ${index===1?"border-primary/50 bg-primary/[0.05]":"border-border bg-card/60"}`}><div className="flex items-center justify-between"><span className="label-mono text-xs text-primary">0{index+1}</span>{index===1&&<span className="label-mono rounded-full border border-primary/30 bg-primary/10 px-3 py-1 text-xs text-primary">RECOMMANDÉ</span>}</div><h3 className="display-serif mt-7 text-3xl">{plan.name}</h3><p className="mt-2 text-xs text-muted-foreground">{plan.badge}</p><div className="mt-6 flex items-end gap-2 border-y border-border py-5"><span className="display-serif text-5xl text-primary">{plan.price} €</span><span className="label-mono mb-1 text-xs text-muted-foreground">/ mois</span></div><ul className="mt-6 space-y-3">{plan.features.map(feature=><li key={feature} className="flex gap-3 text-sm leading-5 text-muted-foreground"><Check className="mt-0.5 h-4 w-4 shrink-0 text-primary"/>{feature}</li>)}</ul><a href={`https://wa.me/33767566783?text=${encodeURIComponent(`Bonjour XR Agency, je souhaite parler du forfait WebCare « ${plan.name} » à ${plan.price} €/mois.`)}`} target="_blank" rel="noreferrer" className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary px-5 py-3.5 text-xs font-semibold uppercase tracking-wider text-primary-foreground">Parler à Alexandre <ArrowRight className="h-4 w-4"/></a></article>)}</div></div></section>
    <section className="border-t border-border/60 py-16"><div className="mx-auto max-w-3xl px-5 text-center"><Sparkles className="mx-auto h-5 w-5 text-primary"/><h2 className="display-serif mt-4 text-4xl sm:text-5xl">Pas besoin de refaire le site pour le faire progresser.</h2><p className="mt-5 text-sm leading-7 text-muted-foreground">WebCare transforme la maintenance en accompagnement continu : moins de friction, plus de réactivité, et un site qui reste aligné avec votre activité.</p></div></section>
  </main><Contact /></div>;
}
