import { ArrowUpRight, Check, Instagram, Linkedin, Music2, Facebook, Search, Globe2 } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { useLang } from "@/lib/i18n";
import { SERVICES } from "@/lib/content";
import { Parallax } from "./primitives";

const FEATURED_IDS = ["websites", "branding", "seo", "maps", "social", "maintenance"];
const DISPLAY_NUM: Record<string, string> = { websites: "01", branding: "02", seo: "03", maps: "04", social: "05", maintenance: "06" };
const DISPLAY_PRICE: Record<string, number | null> = { websites: 499, branding: null, seo: null, maps: null, social: 499, maintenance: null };
const SERVICE_IMG: Record<string, string> = {
  websites: "https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=90&w=2200",
  branding: "https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=90&w=2200",
  seo: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=90&w=2200",
  maps: "https://images.unsplash.com/photo-1524666041070-9e3c7be7b8e0?auto=format&fit=crop&q=90&w=2200",
  social: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&q=90&w=2200",
  maintenance: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=90&w=2200",
};
function ServiceMarks({ id }: { id: string }) {
  if (id === "social") return <div className="flex items-center gap-2 rounded-full border border-white/15 bg-black/30 px-3 py-2 backdrop-blur-md"><Instagram className="h-4 w-4" /><Facebook className="h-4 w-4" /><Music2 className="h-4 w-4" /><Linkedin className="h-4 w-4" /></div>;
  if (id === "seo") return <div className="flex items-center gap-2 rounded-full border border-white/15 bg-black/30 px-3 py-2 backdrop-blur-md"><span className="grid h-5 w-5 place-items-center rounded-full bg-white text-[11px] font-bold text-[#4285F4]">G</span><Search className="h-3.5 w-3.5" /><span className="text-[9px] font-semibold tracking-wide">ORGANIC VISIBILITY</span></div>;
  if (id === "websites") return <div className="flex items-center gap-2 rounded-full border border-white/15 bg-black/30 px-3 py-2 backdrop-blur-md"><Globe2 className="h-4 w-4" /><span className="text-[9px] font-semibold tracking-wide">WEB · UX · CONVERSION</span></div>;
  if (id === "maps") return <div className="rounded-full border border-white/15 bg-black/30 px-3 py-2 text-[9px] font-semibold tracking-wide backdrop-blur-md"><span className="mr-1.5 text-[#4285F4]">G</span> GOOGLE MAPS</div>;
  return null;
}

export function HomeServices() {
  const { t, price } = useLang();
  const featured = FEATURED_IDS.map((id) => SERVICES.find((service) => service.id === id)).filter(Boolean) as typeof SERVICES;
  const hrefFor = (id: string) => id === "maintenance" ? "/services/webcare" : `/services/${id}`;
  return <section id="homepage-services" aria-label="Les six expertises XR Agency" className="relative bg-background py-14 sm:py-20 lg:py-24"><div className="mx-auto max-w-[1500px] px-4 sm:px-8 lg:px-12">
    <Parallax speed={-0.04} className="mb-8 lg:mb-10"><div className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><span className="label-mono text-[9px] uppercase tracking-[0.3em] text-primary">XR AGENCY · 06 EXPERTISES</span><h2 className="display-serif mt-3 max-w-4xl text-5xl leading-[0.9] sm:text-7xl lg:text-[6.5rem]">Une expertise.<br/>Puis la suivante.</h2></div><div className="max-w-sm text-sm leading-6 text-muted-foreground">Création web, branding, SEO, Google Maps, Social Media et WebCare. Faites défiler horizontalement pour explorer l'ensemble du studio.</div></div></Parallax>
    <div className="-mx-4 overflow-x-auto px-4 pb-5 sm:-mx-8 sm:px-8 lg:-mx-12 lg:px-12" style={{ scrollbarWidth: "none" }}><div className="flex snap-x snap-mandatory gap-4 pr-10 sm:gap-5 lg:gap-6">
      {featured.map((service, index) => { const startingPrice = DISPLAY_PRICE[service.id]; return <article key={service.id} className="group relative h-[min(70svh,680px)] min-h-[500px] w-[88vw] shrink-0 snap-start overflow-hidden rounded-[2rem] border border-white/10 bg-black shadow-[0_30px_90px_-45px_rgba(0,0,0,.8)] sm:w-[72vw] lg:w-[58vw] xl:w-[52vw]"><div className="absolute inset-[-7%] overflow-hidden"><Parallax speed={0.07} className="h-full w-full"><img src={SERVICE_IMG[service.id]} alt="" aria-hidden className="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105" /></Parallax></div><div className="absolute inset-0 bg-black/35"/><div className="absolute inset-0 bg-gradient-to-r from-black/90 via-black/50 to-transparent"/><div className="absolute inset-0 bg-gradient-to-t from-black/90 via-transparent to-black/5"/>
        <div className="relative z-10 flex h-full flex-col justify-between p-6 sm:p-9 lg:p-12"><div className="flex items-center justify-between"><div className="flex items-center gap-3 label-mono text-[9px] uppercase tracking-[0.22em] text-white/50"><span className="text-primary">{DISPLAY_NUM[service.id]}</span><span className="h-px w-8 bg-white/20"/><span>XR AGENCY</span></div><span className="rounded-full border border-white/15 bg-black/25 px-3 py-2 label-mono text-[9px] tracking-[0.14em] text-white/60 backdrop-blur">{String(index + 1).padStart(2, "0")} / 06</span></div><Parallax speed={-0.035} className="max-w-3xl"><div><div className="mb-3 flex flex-wrap items-center gap-3"><p className="label-mono text-[9px] uppercase tracking-[0.2em] text-white/60">{t(service.short)}</p>{(service.id === "social" || service.id === "seo" || service.id === "websites" || service.id === "maps") && <ServiceMarks id={service.id} />}{service.id === "maps" && <span className="rounded-full border border-white/20 bg-white/10 px-3 py-1.5 text-[9px] font-semibold tracking-[0.12em] text-white">TOP 3 LOCAL</span>}</div><h3 className="display-serif max-w-3xl text-5xl leading-[0.86] text-white sm:text-7xl lg:text-[6.5rem]">{t(service.title)}</h3><p className="mt-5 max-w-2xl text-sm leading-6 text-white/65 sm:text-base">{t(service.description)}</p><div className="mt-6 flex flex-wrap items-center gap-3"><a href={hrefFor(service.id)} className="inline-flex items-center gap-3 rounded-full bg-white px-5 py-3 label-mono text-[9px] font-semibold uppercase tracking-[0.12em] text-black">Découvrir <ArrowUpRight className="h-4 w-4" /></a>{startingPrice && <span className="rounded-full border border-white/15 bg-white/5 px-4 py-3 label-mono text-[9px] tracking-[0.12em] text-white/65">À partir de {price(startingPrice)}{service.fromPeriod === "month" ? " / mois" : ""}</span>}{service.id === "websites" && <span className="flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-3 label-mono text-[9px] tracking-[0.1em] text-white/80"><Check className="h-3 w-3 text-primary"/> E-commerce & réservation intégrés</span>}</div></div></Parallax><div className="flex items-center justify-between border-t border-white/15 pt-4"><div className="flex gap-1.5">{featured.map((_, dot) => <span key={dot} className={`h-1 rounded-full ${dot === index ? "w-10 bg-white" : "w-2 bg-white/25"}`} />)}</div><div className="label-mono text-[9px] uppercase tracking-[0.15em] text-white/45">Glissez →</div></div></div></article>; })}
    </div></div></div></section>;
}
