import { ArrowUpRight, Plus } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { useLang } from "@/lib/i18n";
import { SERVICES } from "@/lib/content";
import { Reveal } from "./primitives";
const IDS=["websites","branding","seo","maps","social","maintenance"];
const IMG:Record<string,string>={websites:"https://images.unsplash.com/photo-1558655146-d09347e92766?auto=format&fit=crop&q=88&w=1600",branding:"https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=88&w=1600",seo:"https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=88&w=1600",maps:"https://images.unsplash.com/photo-1524666041070-9e3c7be7b8e0?auto=format&fit=crop&q=88&w=1600",social:"https://images.unsplash.com/photo-1611162618071-b39a2ec055fb?auto=format&fit=crop&q=88&w=1600",maintenance:"https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=88&w=1600"};
const PRICE:Record<string,string>={websites:"499 €",social:"499 €"};
const href=(id:string)=>id==="maintenance"?"/services/webcare":`/services/${id}`;
export function HomeServices(){const{t}=useLang();const items=IDS.map(id=>SERVICES.find(s=>s.id===id)).filter(Boolean) as typeof SERVICES;return <section id="homepage-services" className="relative border-b border-border/50 bg-background py-16 sm:py-20 lg:py-24"><div className="mx-auto max-w-[1500px] px-5 sm:px-8 lg:px-12"><Reveal><div className="mb-10 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="label-mono text-primary">XR / EXPERTISES</p><h2 className="display-serif mt-3 max-w-3xl text-4xl sm:text-5xl lg:text-6xl">Une expertise.<br/><em className="not-italic italic text-primary">Puis la suivante.</em></h2></div><p className="max-w-md text-base leading-6 text-muted-foreground">Chaque scène correspond à un levier concret. Explorez sans devoir deviner qu'il faut faire glisser l'écran.</p></div></Reveal><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{items.map((service,i)=><Reveal key={service.id} delay={i*45}><article className="group overflow-hidden rounded-[1.5rem] border border-border/80 bg-card/60 transition duration-500 hover:-translate-y-1 hover:border-primary/45 hover:shadow-[0_30px_70px_-45px_rgba(0,0,0,.9)]"><div className="relative aspect-[16/10] overflow-hidden bg-muted"><img src={IMG[service.id]} alt="" className="h-full w-full object-cover grayscale-[.12] transition duration-700 group-hover:scale-105"/><div className="absolute inset-0 bg-gradient-to-t from-black/75 via-black/10 to-transparent"/><div className="absolute left-4 top-4 rounded-full border border-white/20 bg-black/30 px-3 py-1.5 text-xs font-mono text-white/80 backdrop-blur">{String(i+1).padStart(2,"0")}</div><div className="absolute bottom-4 left-4 text-sm font-medium text-white">{PRICE[service.id]?`À partir de ${PRICE[service.id]}`:"Sur mesure"}</div></div><div className="p-5 sm:p-6"><h3 className="text-xl font-medium">{t(service.title)}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{t(service.short)}</p><div className="mt-5 flex items-center gap-2"><Link to={href(service.id)} className="inline-flex min-h-11 items-center gap-2 rounded-full bg-foreground px-4 py-2.5 text-sm text-background transition hover:-translate-y-0.5">Découvrir <ArrowUpRight className="h-4 w-4"/></Link><a href={`/?service=${service.id}#quote`} className="inline-flex min-h-11 items-center gap-1 rounded-full border border-border px-4 py-2.5 text-sm text-muted-foreground transition hover:border-primary/50 hover:text-primary"><Plus className="h-4 w-4"/> Composer</a></div></div></article></Reveal>)}</div></div></section>}
