import { useState } from "react";
import { ArrowRight, Check, Globe2, Search, Target, Wand2 } from "lucide-react";
import { Link } from "@tanstack/react-router";
import { useLang } from "@/lib/i18n";
import { Parallax, Reveal } from "./primitives";
import { XR_JOURNEY_PHOTO } from "@/lib/photography";

const OPTIONS=[
 {id:"start",icon:Wand2,label:{fr:"Je pars de zéro",en:"I'm starting from zero",vi:"Tôi bắt đầu từ số 0",ar:"أبدأ من الصفر",ru:"Начинаю с нуля"},text:{fr:"Créer un socle solide : identité, site et visibilité.",en:"Build the foundation: identity, website and visibility.",vi:"Xây nền tảng: nhận diện, website và khả năng hiển thị.",ar:"بناء الأساس: الهوية والموقع والظهور.",ru:"Основа: айдентика, сайт и видимость."},stack:["Branding","Site web","SEO"]},
 {id:"site",icon:Globe2,label:{fr:"Mon site ne me ressemble pas",en:"My website isn't right",vi:"Website chưa phù hợp",ar:"موقعي لا يعكسني",ru:"Сайт меня не отражает"},text:{fr:"Refondre l'expérience, le message et le parcours de conversion.",en:"Rework the experience, message and conversion journey.",vi:"Thiết kế lại trải nghiệm, thông điệp và chuyển đổi.",ar:"إعادة بناء التجربة والرسالة ومسار التحويل.",ru:"Пересобрать опыт, сообщение и конверсию."},stack:["Refonte","Conversion","WebCare"]},
 {id:"visibility",icon:Search,label:{fr:"Je manque de visibilité",en:"I lack visibility",vi:"Tôi thiếu khả năng hiển thị",ar:"أفتقد الظهور",ru:"Мне не хватает видимости"},text:{fr:"Faire remonter votre activité là où vos clients cherchent déjà.",en:"Show up where customers are already searching.",vi:"Xuất hiện nơi khách hàng đang tìm kiếm.",ar:"الظهور حيث يبحث العملاء.",ru:"Быть там, где клиенты уже ищут."},stack:["SEO","Google Maps","Ads"]},
 {id:"growth",icon:Target,label:{fr:"Je veux plus de clients",en:"I want more clients",vi:"Tôi muốn nhiều khách hơn",ar:"أريد المزيد من العملاء",ru:"Хочу больше клиентов"},text:{fr:"Construire le parcours : attirer → convaincre → convertir.",en:"Build the path: attract → convince → convert.",vi:"Xây hành trình: thu hút → thuyết phục → chuyển đổi.",ar:"بناء المسار: جذب ← إقناع ← تحويل.",ru:"Путь: привлечь → убедить → конвертировать."},stack:["Strategy","Conversion","Social"]},
];

export function ImmersiveJourney(){
 const {lang}=useLang(); const [active,setActive]=useState("start"); const option=OPTIONS.find(x=>x.id===active)??OPTIONS[0]; const Icon=option.icon; const label=option.label[lang as keyof typeof option.label]??option.label.fr; const copy=option.text[lang as keyof typeof option.text]??option.text.fr;
 return <section id="journey" className="xr-section-elevated xr-noise relative overflow-hidden border-b xr-line py-20 sm:py-28 lg:py-36">
  <div className="relative mx-auto max-w-[1560px] px-5 sm:px-8 lg:px-12">
   <Parallax speed={-0.025}><Reveal><div className="grid gap-8 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><span className="label-mono xr-accent text-[8px] tracking-[.28em]">XRAGENCY · COMMENCEZ ICI</span><h2 className="display-serif mt-5 max-w-5xl text-[clamp(3rem,5.5vw,6rem)] leading-[.84] tracking-[-.065em]">{lang==="fr"?"Votre projet commence par votre situation.":lang==="vi"?"Dự án bắt đầu từ tình hình hiện tại của bạn.":lang==="ar"?"مشروعك يبدأ من وضعك الحالي.":lang==="ru"?"Ваш проект начинается с вашей ситуации.":"Your project starts with your situation."}</h2></div><p className="max-w-xl text-sm leading-7 xr-muted sm:text-base">{lang==="fr"?"Pas besoin de connaître le marketing. Dites-nous simplement où vous en êtes : le parcours se construit autour de vous.":"Choose the situation that sounds most like you. The path is built around your needs."}</p></div></Reveal></Parallax>

   <div className="mt-10 grid gap-5 lg:grid-cols-[.72fr_1.28fr]">
    <Reveal><div className="xr-panel rounded-[2.2rem] p-3 sm:p-4"><div className="flex items-center justify-between px-3 py-3"><span className="label-mono text-[6px] tracking-[.2em] xr-muted-2">01 · POINT DE DÉPART</span><span className="label-mono text-[6px] xr-muted-2">CHOISIR</span></div><div className="grid gap-2">{OPTIONS.map((item,i)=>{const I=item.icon;const selected=item.id===active;return <button key={item.id} type="button" onClick={()=>setActive(item.id)} className={"group relative flex items-start gap-4 rounded-[1.4rem] border p-4 text-left transition duration-500 "+(selected?"xr-panel-strong translate-x-1":"border-transparent hover:border-[var(--xr-line)] hover:bg-[var(--xr-surface)]")}><span className={"grid h-11 w-11 shrink-0 place-items-center rounded-xl border "+(selected?"bg-[var(--xr-ink)] text-[var(--xr-bg)] border-transparent":"xr-line xr-muted")}><I className="h-4 w-4"/></span><span className="min-w-0 flex-1"><span className="label-mono text-[6px] xr-muted-2">0{i+1}</span><span className="mt-1 block text-sm font-semibold">{item.label[lang as keyof typeof item.label]??item.label.fr}</span><span className="mt-1 block text-[9px] leading-4 xr-muted">{item.text[lang as keyof typeof item.text]??item.text.fr}</span></span>{selected?<Check className="mt-1 h-4 w-4 opacity-70"/>:<ArrowRight className="mt-1 h-4 w-4 opacity-20 transition group-hover:translate-x-1 group-hover:opacity-60"/>}</button>})}</div></div></Reveal>

    <Reveal delay={90}><div className="xr-depth-card relative min-h-[520px] overflow-hidden rounded-[2.5rem] border xr-line bg-[var(--xr-bg)] p-3 shadow-[var(--xr-shadow)]">
      <Parallax speed={0.025} direction="y" className="absolute inset-[3%] overflow-hidden rounded-[2.1rem]"><img src={XR_JOURNEY_PHOTO} alt="" className="h-full w-full object-cover opacity-[.18] grayscale-[.15] dark:opacity-[.33]"/><div className="absolute inset-0 bg-gradient-to-tr from-[var(--xr-bg)] via-transparent to-[var(--xr-bg)]"/></Parallax>
      <div className="relative z-10 flex min-h-[494px] flex-col justify-between p-6 sm:p-9">
       <div className="flex items-center justify-between"><span className="label-mono text-[7px] tracking-[.22em] xr-muted-2">02 · VOTRE PARCOURS</span><span className="grid h-10 w-10 place-items-center rounded-full border xr-line xr-accent-bg"><Icon className="h-4 w-4 xr-accent"/></span></div>
       <div className="max-w-xl"><span className="label-mono text-[7px] tracking-[.2em] xr-muted-2">SITUATION / {active.toUpperCase()}</span><h3 className="display-serif mt-4 text-[clamp(2.7rem,5vw,5.5rem)] leading-[.86] tracking-[-.055em]">{label}</h3><p className="mt-5 max-w-lg text-sm leading-6 xr-muted">{copy}</p><div className="mt-7 flex flex-wrap gap-2">{option.stack.map((x,i)=><span key={x} className="rounded-full border xr-line bg-[var(--xr-surface)] px-3 py-2 label-mono text-[6px] backdrop-blur-xl"><span className="mr-2 xr-accent">0{i+1}</span>{x}</span>)}</div></div>
       <div className="flex flex-col gap-3 border-t xr-line pt-5 sm:flex-row sm:items-center sm:justify-between"><span className="label-mono text-[6px] tracking-[.18em] xr-muted-2">SITUATION → PRIORITÉ → DISPOSITIF</span><div className="flex gap-2"><Link to="/#quote" className="inline-flex items-center gap-2 rounded-full bg-[var(--xr-ink)] px-5 py-3.5 label-mono text-[8px] font-semibold text-[var(--xr-bg)]">Construire ce parcours <ArrowRight className="h-4 w-4"/></Link><a href="#homepage-services" className="inline-flex items-center gap-2 rounded-full border xr-line px-4 py-3.5 label-mono text-[7px] xr-muted">Explorer</a></div></div>
      </div>
    </div></Reveal>
   </div>
  </div>
 </section>;
}
