import { useEffect, useState, useCallback, useRef } from "react";
import { Link, useLocation } from "@tanstack/react-router";
import { ChevronDown, X, Sparkles } from "lucide-react";
import { cn } from "@/lib/utils";
import { LANGS, useLang } from "@/lib/i18n";
import { UI } from "@/lib/copy";
import { SERVICES } from "@/lib/content";
import { Logo, EmberButton } from "./primitives";
import { CartFloatingButton } from "./Cart";
import { ThemeSwitcher } from "@/components/theme/ThemeSwitcher";

export function Nav() {
  const { t, lang, setLang } = useLang(); const location = useLocation(); const isHome = location.pathname === "/";
  const [scrolled, setScrolled] = useState(false); const [open, setOpen] = useState(false); const [servicesDropdownOpen, setServicesDropdownOpen] = useState(false); const [progress, setProgress] = useState(0); const [activeSection, setActiveSection] = useState<string | null>(null); const dropdownTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const SERVICE_IDS = ["websites", "branding", "seo", "maps", "social", "maintenance"];
  const serviceHref = (id: string) => id === "maintenance" ? "/services/webcare" : `/services/${id}`;
  const onScroll = useCallback(() => { const scrollY = window.scrollY; setScrolled(scrollY > 30); const docHeight = document.documentElement.scrollHeight - window.innerHeight; if (docHeight > 0) setProgress(Math.min(scrollY / docHeight, 1)); if (isHome) { const sections = ["quote", "google-simulation", "homepage-services", "work", "faq", "contact"]; let current: string | null = null; for (const id of sections) { const el = document.getElementById(id); if (el && el.getBoundingClientRect().top <= 140) current = id; } setActiveSection(current); } else if (location.pathname.startsWith("/services")) setActiveSection("services"); else setActiveSection(null); }, [isHome, location.pathname]);
  useEffect(() => { onScroll(); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll); }, [onScroll]);
  const handleDropdownEnter = () => { if (dropdownTimeoutRef.current) clearTimeout(dropdownTimeoutRef.current); setServicesDropdownOpen(true); }; const handleDropdownLeave = () => { dropdownTimeoutRef.current = setTimeout(() => setServicesDropdownOpen(false), 160); };
  const goSection = (id: string) => { setOpen(false); if (isHome) document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); else window.location.href = `/#${id}`; };
  return <header className={cn("fixed inset-x-0 top-0 z-50 transition-all duration-500", scrolled ? "border-b border-border/70 bg-background/92 py-2 shadow-sm backdrop-blur-xl sm:py-3" : "border-b border-transparent bg-background/60 py-3 backdrop-blur-md sm:py-4.5")}><div aria-hidden className="absolute bottom-0 left-0 h-[1.5px] bg-gradient-to-r from-primary/80 via-primary to-primary/40 transition-[width] duration-150" style={{ width: `${(progress * 100).toFixed(1)}%` }} /><nav className="relative mx-auto flex w-full max-w-[1600px] items-center gap-3 px-4 lg:gap-5 lg:px-8"><Logo className="shrink-0" />
    <div className="hidden min-w-0 flex-1 items-center justify-center lg:flex"><div className="flex items-center gap-1.5 rounded-full border border-border/70 bg-card/70 p-1 shadow-sm backdrop-blur-xl"><div className="relative" onMouseEnter={handleDropdownEnter} onMouseLeave={handleDropdownLeave}><button type="button" aria-expanded={servicesDropdownOpen} onClick={() => setServicesDropdownOpen((v) => !v)} className={cn("inline-flex items-center gap-1.5 rounded-full px-4 py-2.5 text-[9px] font-semibold uppercase tracking-[0.14em] transition-all", activeSection === "services" ? "bg-primary text-primary-foreground" : "text-foreground hover:bg-accent/70")}>{t(UI.navServices)} <ChevronDown className={cn("h-3 w-3 transition-transform", servicesDropdownOpen && "rotate-180")} /></button>{servicesDropdownOpen && <div className="absolute left-1/2 top-full z-50 mt-2 w-[720px] -translate-x-1/2 rounded-2xl border border-border/80 bg-background/98 p-3 shadow-2xl backdrop-blur-2xl" onMouseEnter={handleDropdownEnter} onMouseLeave={handleDropdownLeave}><div className="mb-2 flex items-center justify-between px-2"><span className="label-mono text-[8px] uppercase tracking-[0.2em] text-muted-foreground">XR / 06 EXPERTISES</span><Link to="/services" onClick={() => setServicesDropdownOpen(false)} className="text-[9px] uppercase tracking-wider text-primary hover:underline">Voir le catalogue →</Link></div><div className="grid grid-cols-3 gap-2">{SERVICE_IDS.map((id) => { const service = SERVICES.find((s) => s.id === id); return service ? <a key={id} href={serviceHref(id)} onClick={() => setServicesDropdownOpen(false)} className="group rounded-xl border border-border/70 bg-card/50 p-3 transition-all hover:-translate-y-0.5 hover:border-primary/40 hover:bg-primary/[0.05]"><span className="label-mono text-[8px] text-primary">{service.num}</span><span className="mt-1 block text-xs font-medium group-hover:text-primary">{t(service.title)}</span><span className="mt-1 block text-[9px] leading-4 text-muted-foreground">{t(service.short)}</span></a> : null; })}</div></div>}</div><button type="button" onClick={() => goSection("quote")} className={cn("inline-flex items-center gap-2 rounded-full px-4 py-2.5 text-[9px] font-semibold uppercase tracking-[0.14em] transition-all", activeSection === "quote" ? "bg-primary text-primary-foreground shadow-lg" : "text-primary hover:bg-primary/10")}><Sparkles className="h-3 w-3" /> {t(UI.navIntelligence)}</button><button type="button" onClick={() => goSection("work")} className="rounded-full px-3 py-2.5 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted-foreground hover:bg-accent/70 hover:text-foreground">{t(UI.navWork)}</button><button type="button" onClick={() => goSection("faq")} className="rounded-full px-3 py-2.5 text-[9px] font-semibold uppercase tracking-[0.14em] text-muted-foreground hover:bg-accent/70 hover:text-foreground">{t(UI.navFaq)}</button></div></div>
    <div className="ml-auto flex shrink-0 items-center justify-end gap-1.5 sm:gap-2"><ThemeSwitcher className="h-9 w-9 shrink-0 rounded-full shadow-none" /><div className="hidden items-center gap-1 rounded-full border border-border bg-card/60 px-1 py-1 sm:flex">{LANGS.map((l) => <button key={l.code} onClick={() => setLang(l.code)} className={cn("label-mono cursor-pointer rounded-full px-2.5 py-0.5 text-xs transition-colors", lang === l.code ? "bg-primary text-primary-foreground shadow-sm" : "text-muted-foreground hover:text-foreground")}>{l.label}</button>)}</div><CartFloatingButton /><button aria-label="Menu" onClick={() => setOpen((v) => !v)} className="flex h-9 w-9 shrink-0 cursor-pointer items-center justify-center rounded-full border border-border bg-card/80 lg:hidden">{open ? <X className="h-4 w-4" /> : <span className="relative block h-[9px] w-4"><span className="absolute inset-x-0 top-0 h-px bg-foreground" /><span className="absolute inset-x-0 bottom-0 h-px bg-foreground" /></span>}</button><EmberButton href="/#contact" className="hidden text-xs md:inline-flex">{t(UI.bookCall)}</EmberButton></div></nav>
    {open && <div className="border-t border-border bg-background/98 px-5 py-5 backdrop-blur-2xl lg:hidden"><div className="mb-3 rounded-2xl border border-primary/30 bg-primary/5 p-4"><button type="button" onClick={() => goSection("quote")} className="flex w-full items-center justify-between text-left"><span><span className="label-mono block text-[9px] uppercase tracking-[0.18em] text-primary">XR Intelligence</span><span className="mt-1 block text-sm font-medium">Faire mon devis sur mesure</span></span><Sparkles className="h-4 w-4 text-primary" /></button></div><div className="grid grid-cols-2 gap-2">{SERVICE_IDS.map((id) => { const s = SERVICES.find((x) => x.id === id); return s ? <a key={id} href={serviceHref(id)} onClick={() => setOpen(false)} className="rounded-xl border border-border px-3 py-3"><span className="label-mono text-[8px] text-primary">{s.num}</span><span className="ml-2 text-xs">{t(s.title)}</span></a> : null; })}</div><div className="mt-4 flex items-center justify-between border-t border-border/60 pt-4"><span className="label-mono text-xs text-muted-foreground">Langue</span><div className="flex gap-1.5">{LANGS.map((l) => <button key={l.code} onClick={() => setLang(l.code)} className={cn("label-mono rounded-full border px-2.5 py-1 text-xs", lang === l.code ? "border-primary bg-primary text-primary-foreground" : "border-border text-muted-foreground")}>{l.label}</button>)}</div></div></div>}
  </header>;
}
