import { useState } from "react";
import { ArrowRight, Check, Instagram, MessageCircle, Play, Send, Sparkles, TrendingUp, Users } from "lucide-react";
import { useLang } from "@/lib/i18n";
import { CONTACT } from "@/lib/content";
import { cn } from "@/lib/utils";

const PLANS = [
  { price: 499, name: "Présence Essentielle", audience: "Être présent sans devoir tout gérer.", networks: 1, posts: 12, stories: 8, videos: 0, comments: "3 jours / semaine", dm: "Non inclus", reports: "1 / mois", features: ["Calendrier éditorial mensuel", "Direction artistique & ligne éditoriale", "12 publications / carrousels", "8 Stories", "Programmation & publication", "Commentaires gérés 3 jours / semaine", "1 reporting mensuel"] },
  { price: 799, name: "Croissance Active", audience: "Accélérer la présence et déléguer davantage.", networks: 2, posts: 16, stories: 8, videos: 2, comments: "5 jours / semaine", dm: "5 jours / semaine", reports: "2 / mois", features: ["Tout le niveau Essentiel", "16 publications / carrousels", "8 Stories", "2 vidéos courtes / mois", "Publication sur 2 réseaux", "Commentaires gérés 5 jours / semaine", "Messages privés gérés 5 jours / semaine", "2 reportings mensuels", "Ajustements éditoriaux mensuels"] },
  { price: 999, name: "Social Authority", audience: "Nous prenons en charge votre présence sociale.", networks: 3, posts: 20, stories: 15, videos: 4, comments: "6 jours / semaine", dm: "6 jours / semaine", reports: "Stratégique / mois", features: ["Tout le niveau Croissance Active", "20 publications / carrousels", "15 Stories", "4 vidéos courtes / mois", "Publication sur 3 réseaux", "Commentaires gérés 6 jours / semaine", "Messages privés gérés 6 jours / semaine", "Animation : sondages, questions, CTA", "Reporting stratégique & recommandations mensuelles"] },
] as const;

export function SocialManagementExperience() {
  const { lang } = useLang();
  const [selected, setSelected] = useState(1);
  const plan = PLANS[selected];
  const fr = lang === "fr";
  const wa = encodeURIComponent(`Bonjour XR Agency, je souhaite choisir le forfait Social « ${plan.name} » à ${plan.price} €/mois.`);
  const copy = fr ? { eyebrow: "SOCIAL MANAGEMENT", title: "Votre présence sociale devient un véritable système.", intro: "Pas une succession de posts. Une direction artistique, du contenu, de l'animation, de la communauté et du pilotage — avec un niveau de délégation clair.", content: "Un mois de contenu", included: "Inclus dans ce niveau", cta: "Choisir ce forfait", language: "1 langue incluse · +100 € / langue supplémentaire", note: "Shooting photo/vidéo, déplacement, mannequins, studio et production sur site sur devis. Publicité payante non incluse." } : { eyebrow: "SOCIAL MANAGEMENT", title: "Your social presence becomes a real operating system.", intro: "Not a sequence of posts. Art direction, content, publishing, community and reporting — with a clearly defined level of delegation.", content: "One month of content", included: "Included at this level", cta: "Choose this plan", language: "1 language included · +€100 / additional language", note: "Photo/video shoots, travel, models, studio and on-site production quoted separately. Paid advertising not included." };
  return <section id="plans" className="border-y border-border/60 bg-card/20 py-20 lg:py-28"><div className="mx-auto max-w-7xl px-5 sm:px-8 lg:px-10">
    <div className="grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-end"><div><p className="label-mono text-[10px] uppercase tracking-[0.24em] text-primary">{copy.eyebrow} · 05</p><h2 className="display-serif mt-4 max-w-5xl text-4xl leading-[.92] sm:text-6xl lg:text-7xl">{copy.title}</h2><p className="mt-6 max-w-3xl text-sm leading-7 text-muted-foreground sm:text-base">{copy.intro}</p></div><div className="relative hidden min-h-[190px] overflow-hidden rounded-[2rem] border border-border bg-background lg:block"><div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_20%,hsl(var(--primary)/.18),transparent_42%)]" /><div className="absolute left-8 top-8 flex items-center gap-3 rounded-2xl border border-border bg-card/80 px-4 py-3 shadow-xl backdrop-blur"><Instagram className="h-4 w-4 text-primary" /><span className="text-xs font-medium">XR / SOCIAL</span></div><div className="absolute bottom-8 right-8 flex items-center gap-3 rounded-2xl border border-border bg-card/80 px-4 py-3 shadow-xl backdrop-blur"><TrendingUp className="h-4 w-4 text-primary" /><span className="text-xs">+ présence · + cohérence · + conversion</span></div><div className="absolute left-1/2 top-1/2 h-20 w-20 -translate-x-1/2 -translate-y-1/2 rounded-full border border-primary/30 bg-primary/10" /></div></div>
    <div className="mt-14 grid gap-3 sm:grid-cols-3">{PLANS.map((item, index) => <button key={item.name} type="button" onClick={() => setSelected(index)} className={cn("group relative overflow-hidden rounded-[1.5rem] border p-5 text-left transition-all duration-300 sm:p-6", selected === index ? "border-primary bg-primary/[0.07] shadow-2xl -translate-y-1" : "border-border bg-background/60 hover:-translate-y-1 hover:border-primary/40")}><div className="absolute right-0 top-0 h-24 w-24 rounded-full bg-primary/10 blur-2xl opacity-0 transition-opacity group-hover:opacity-100" /><div className="relative flex items-center justify-between"><span className="label-mono text-[9px] text-primary">0{index + 1}</span>{index === 1 && <span className="label-mono rounded-full border border-primary/30 bg-primary/10 px-2.5 py-1 text-[8px] text-primary">RECOMMANDÉ</span>}</div><h3 className="display-serif mt-7 text-3xl sm:text-4xl">{item.name}</h3><p className="mt-3 min-h-10 text-xs leading-5 text-muted-foreground">{item.audience}</p><div className="mt-6 flex items-end gap-2"><span className="display-serif text-5xl text-primary">{item.price} €</span><span className="label-mono mb-1 text-[9px] text-muted-foreground">/ mois</span></div><div className="mt-5 flex flex-wrap gap-1.5"><span className="rounded-full border border-border px-2 py-1 text-[8px]">{item.networks} réseau{item.networks > 1 ? "x" : ""}</span><span className="rounded-full border border-border px-2 py-1 text-[8px]">{item.posts} publications</span><span className="rounded-full border border-border px-2 py-1 text-[8px]">{item.videos} vidéos</span></div></button>)}</div>
    <div className="mt-8 overflow-hidden rounded-[2rem] border border-border bg-background shadow-2xl"><div className="grid lg:grid-cols-[.7fr_1.3fr]"><div className="relative overflow-hidden border-b border-border bg-primary/[0.05] p-7 sm:p-10 lg:border-b-0 lg:border-r"><div className="absolute -right-16 -top-16 h-40 w-40 rounded-full bg-primary/10 blur-3xl" /><div className="relative"><div className="flex items-center justify-between"><span className="label-mono text-[9px] text-primary">0{selected + 1} / 03</span><Sparkles className="h-4 w-4 text-primary" /></div><h3 className="display-serif mt-7 text-4xl sm:text-5xl">{plan.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{plan.audience}</p><div className="mt-7 grid grid-cols-2 gap-2"><div className="rounded-2xl border border-border bg-background/70 p-4"><Users className="h-4 w-4 text-primary" /><strong className="mt-3 block text-2xl">{plan.networks}</strong><span className="label-mono text-[8px] text-muted-foreground">RÉSEAUX</span></div><div className="rounded-2xl border border-border bg-background/70 p-4"><Play className="h-4 w-4 text-primary" /><strong className="mt-3 block text-2xl">{plan.videos}</strong><span className="label-mono text-[8px] text-muted-foreground">VIDÉOS / MOIS</span></div></div><a href={`${CONTACT.whatsapp}?text=${wa}`} target="_blank" rel="noreferrer" className="mt-7 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary px-6 py-4 text-[10px] font-semibold uppercase tracking-[0.12em] text-primary-foreground">{copy.cta}<ArrowRight className="h-4 w-4" /></a></div></div>
      <div className="p-7 sm:p-10"><div className="flex items-center justify-between gap-4"><div><p className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">{copy.content}</p><p className="mt-1 text-xs text-muted-foreground">Une production visible, mesurable et structurée.</p></div><div className="hidden h-9 w-9 items-center justify-center rounded-full border border-primary/30 bg-primary/10 sm:flex"><Send className="h-4 w-4 text-primary" /></div></div><div className="mt-7 grid grid-cols-2 gap-2 sm:grid-cols-4">{[[plan.posts,"PUBLICATIONS"],[plan.stories,"STORIES"],[plan.videos,"VIDÉOS COURTES"],[plan.networks,"RÉSEAUX"]].map(([value,label]) => <div key={label} className="group rounded-2xl border border-border p-4 transition-colors hover:border-primary/40"><span className="display-serif text-3xl text-primary">{value}</span><span className="label-mono mt-1 block text-[8px] leading-4 text-muted-foreground">{label}</span></div>)}</div><div className="mt-8 grid gap-2 sm:grid-cols-3">{[["Commentaires",plan.comments],["Messages privés",plan.dm],["Reporting",plan.reports]].map(([label,value]) => <div key={label} className="rounded-2xl border border-border bg-card/40 p-4"><span className="label-mono text-[8px] uppercase text-primary">{label}</span><p className="mt-2 text-xs font-medium leading-5">{value}</p></div>)}</div><div className="mt-9"><p className="label-mono text-[9px] uppercase tracking-[0.2em] text-primary">{copy.included}</p><ul className="mt-4 grid gap-2 sm:grid-cols-2">{plan.features.map((feature) => <li key={feature} className="flex gap-2 rounded-xl border border-border/60 p-3 text-xs leading-5 text-muted-foreground"><Check className="mt-0.5 h-3.5 w-3.5 shrink-0 text-primary" />{feature}</li>)}</ul></div></div></div></div>
    <div className="mt-6 flex flex-col gap-2 text-[9px] leading-5 text-muted-foreground sm:flex-row sm:justify-between"><span>{copy.language}</span><span>{copy.note}</span></div>
  </div></section>;
}
