/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as MentionsLegalesRouteImport } from './routes/mentions-legales'
import { Route as NotreHistoireRouteImport } from './routes/notre-histoire'
import { Route as RealisationsRouteImport } from './routes/realisations'
import { Route as RecrutementRouteImport } from './routes/recrutement'
import { Route as RefonteSiteInternetRouteImport } from './routes/refonte-site-internet'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ApiAuditRouteImport } from './routes/api/audit'
import { Route as ApiCreateCheckoutRouteImport } from './routes/api/create-checkout'
import { Route as ApiSendQuoteRouteImport } from './routes/api/send-quote'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAuditsRouteImport } from './routes/dashboard/audits'
import { Route as DashboardLoginRouteImport } from './routes/dashboard/login'
import { Route as DashboardNewRouteImport } from './routes/dashboard/new'
import { Route as DashboardProspectsRouteImport } from './routes/dashboard/prospects'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesServiceIdRouteImport } from './routes/services/$serviceId'
import { Route as ServicesRobotiqueRouteImport } from './routes/services/robotique'
import { Route as ServicesSeoRouteImport } from './routes/services/seo'
import { Route as ServicesWebcareRouteImport } from './routes/services/webcare'
import { Route as DashboardAuditsAuditIdRouteImport } from './routes/dashboard/audits.$auditId'
import { Route as DashboardProspectsProspectIdRouteImport } from './routes/dashboard/prospects.$prospectId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MentionsLegalesRoute = MentionsLegalesRouteImport.update({
  id: '/mentions-legales',
  path: '/mentions-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreHistoireRoute = NotreHistoireRouteImport.update({
  id: '/notre-histoire',
  path: '/notre-histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const RealisationsRoute = RealisationsRouteImport.update({
  id: '/realisations',
  path: '/realisations',
  getParentRoute: () => rootRouteImport,
} as any)
const RecrutementRoute = RecrutementRouteImport.update({
  id: '/recrutement',
  path: '/recrutement',
  getParentRoute: () => rootRouteImport,
} as any)
const RefonteSiteInternetRoute = RefonteSiteInternetRouteImport.update({
  id: '/refonte-site-internet',
  path: '/refonte-site-internet',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuditRoute = ApiAuditRouteImport.update({
  id: '/api/audit',
  path: '/api/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateCheckoutRoute = ApiCreateCheckoutRouteImport.update({
  id: '/api/create-checkout',
  path: '/api/create-checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendQuoteRoute = ApiSendQuoteRouteImport.update({
  id: '/api/send-quote',
  path: '/api/send-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAuditsRoute = DashboardAuditsRouteImport.update({
  id: '/audits',
  path: '/audits',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLoginRoute = DashboardLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardNewRoute = DashboardNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProspectsRoute = DashboardProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => DashboardRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRobotiqueRoute = ServicesRobotiqueRouteImport.update({
  id: '/services/robotique',
  path: '/services/robotique',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSeoRoute = ServicesSeoRouteImport.update({
  id: '/services/seo',
  path: '/services/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWebcareRoute = ServicesWebcareRouteImport.update({
  id: '/services/webcare',
  path: '/services/webcare',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAuditsAuditIdRoute = DashboardAuditsAuditIdRouteImport.update({
  id: '/$auditId',
  path: '/$auditId',
  getParentRoute: () => DashboardAuditsRoute,
} as any)
const DashboardProspectsProspectIdRoute =
  DashboardProspectsProspectIdRouteImport.update({
    id: '/$prospectId',
    path: '/$prospectId',
    getParentRoute: () => DashboardProspectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/refonte-site-internet': typeof RefonteSiteInternetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/send-quote': typeof ApiSendQuoteRoute
  '/dashboard/audits': typeof DashboardAuditsRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/prospects': typeof DashboardProspectsRouteWithChildren
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/robotique': typeof ServicesRobotiqueRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/webcare': typeof ServicesWebcareRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/dashboard/audits/$auditId': typeof DashboardAuditsAuditIdRoute
  '/dashboard/prospects/$prospectId': typeof DashboardProspectsProspectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/refonte-site-internet': typeof RefonteSiteInternetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/send-quote': typeof ApiSendQuoteRoute
  '/dashboard/audits': typeof DashboardAuditsRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/prospects': typeof DashboardProspectsRouteWithChildren
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/robotique': typeof ServicesRobotiqueRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/webcare': typeof ServicesWebcareRoute
  '/dashboard': typeof DashboardIndexRoute
  '/services': typeof ServicesIndexRoute
  '/dashboard/audits/$auditId': typeof DashboardAuditsAuditIdRoute
  '/dashboard/prospects/$prospectId': typeof DashboardProspectsProspectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/faq': typeof FaqRoute
  '/mentions-legales': typeof MentionsLegalesRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/realisations': typeof RealisationsRoute
  '/recrutement': typeof RecrutementRoute
  '/refonte-site-internet': typeof RefonteSiteInternetRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/work': typeof WorkRoute
  '/api/audit': typeof ApiAuditRoute
  '/api/create-checkout': typeof ApiCreateCheckoutRoute
  '/api/send-quote': typeof ApiSendQuoteRoute
  '/dashboard/audits': typeof DashboardAuditsRouteWithChildren
  '/dashboard/login': typeof DashboardLoginRoute
  '/dashboard/new': typeof DashboardNewRoute
  '/dashboard/prospects': typeof DashboardProspectsRouteWithChildren
  '/services/$serviceId': typeof ServicesServiceIdRoute
  '/services/robotique': typeof ServicesRobotiqueRoute
  '/services/seo': typeof ServicesSeoRoute
  '/services/webcare': typeof ServicesWebcareRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/dashboard/audits/$auditId': typeof DashboardAuditsAuditIdRoute
  '/dashboard/prospects/$prospectId': typeof DashboardProspectsProspectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/faq'
    | '/mentions-legales'
    | '/notre-histoire'
    | '/realisations'
    | '/recrutement'
    | '/refonte-site-internet'
    | '/sitemap.xml'
    | '/work'
    | '/api/audit'
    | '/api/create-checkout'
    | '/api/send-quote'
    | '/dashboard/audits'
    | '/dashboard/login'
    | '/dashboard/new'
    | '/dashboard/prospects'
    | '/services/$serviceId'
    | '/services/robotique'
    | '/services/seo'
    | '/services/webcare'
    | '/dashboard/'
    | '/services/'
    | '/dashboard/audits/$auditId'
    | '/dashboard/prospects/$prospectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/faq'
    | '/mentions-legales'
    | '/notre-histoire'
    | '/realisations'
    | '/recrutement'
    | '/refonte-site-internet'
    | '/sitemap.xml'
    | '/work'
    | '/api/audit'
    | '/api/create-checkout'
    | '/api/send-quote'
    | '/dashboard/audits'
    | '/dashboard/login'
    | '/dashboard/new'
    | '/dashboard/prospects'
    | '/services/$serviceId'
    | '/services/robotique'
    | '/services/seo'
    | '/services/webcare'
    | '/dashboard'
    | '/services'
    | '/dashboard/audits/$auditId'
    | '/dashboard/prospects/$prospectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/faq'
    | '/mentions-legales'
    | '/notre-histoire'
    | '/realisations'
    | '/recrutement'
    | '/refonte-site-internet'
    | '/sitemap.xml'
    | '/work'
    | '/api/audit'
    | '/api/create-checkout'
    | '/api/send-quote'
    | '/dashboard/audits'
    | '/dashboard/login'
    | '/dashboard/new'
    | '/dashboard/prospects'
    | '/services/$serviceId'
    | '/services/robotique'
    | '/services/seo'
    | '/services/webcare'
    | '/dashboard/'
    | '/services/'
    | '/dashboard/audits/$auditId'
    | '/dashboard/prospects/$prospectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  FaqRoute: typeof FaqRoute
  MentionsLegalesRoute: typeof MentionsLegalesRoute
  NotreHistoireRoute: typeof NotreHistoireRoute
  RealisationsRoute: typeof RealisationsRoute
  RecrutementRoute: typeof RecrutementRoute
  RefonteSiteInternetRoute: typeof RefonteSiteInternetRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkRoute: typeof WorkRoute
  ApiAuditRoute: typeof ApiAuditRoute
  ApiCreateCheckoutRoute: typeof ApiCreateCheckoutRoute
  ApiSendQuoteRoute: typeof ApiSendQuoteRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRoute
  ServicesRobotiqueRoute: typeof ServicesRobotiqueRoute
  ServicesSeoRoute: typeof ServicesSeoRoute
  ServicesWebcareRoute: typeof ServicesWebcareRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentions-legales': {
      id: '/mentions-legales'
      path: '/mentions-legales'
      fullPath: '/mentions-legales'
      preLoaderRoute: typeof MentionsLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-histoire': {
      id: '/notre-histoire'
      path: '/notre-histoire'
      fullPath: '/notre-histoire'
      preLoaderRoute: typeof NotreHistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/realisations': {
      id: '/realisations'
      path: '/realisations'
      fullPath: '/realisations'
      preLoaderRoute: typeof RealisationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recrutement': {
      id: '/recrutement'
      path: '/recrutement'
      fullPath: '/recrutement'
      preLoaderRoute: typeof RecrutementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refonte-site-internet': {
      id: '/refonte-site-internet'
      path: '/refonte-site-internet'
      fullPath: '/refonte-site-internet'
      preLoaderRoute: typeof RefonteSiteInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/audit': {
      id: '/api/audit'
      path: '/api/audit'
      fullPath: '/api/audit'
      preLoaderRoute: typeof ApiAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-checkout': {
      id: '/api/create-checkout'
      path: '/api/create-checkout'
      fullPath: '/api/create-checkout'
      preLoaderRoute: typeof ApiCreateCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-quote': {
      id: '/api/send-quote'
      path: '/api/send-quote'
      fullPath: '/api/send-quote'
      preLoaderRoute: typeof ApiSendQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/audits': {
      id: '/dashboard/audits'
      path: '/audits'
      fullPath: '/dashboard/audits'
      preLoaderRoute: typeof DashboardAuditsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/login': {
      id: '/dashboard/login'
      path: '/login'
      fullPath: '/dashboard/login'
      preLoaderRoute: typeof DashboardLoginRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/new': {
      id: '/dashboard/new'
      path: '/new'
      fullPath: '/dashboard/new'
      preLoaderRoute: typeof DashboardNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/prospects': {
      id: '/dashboard/prospects'
      path: '/prospects'
      fullPath: '/dashboard/prospects'
      preLoaderRoute: typeof DashboardProspectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/robotique': {
      id: '/services/robotique'
      path: '/services/robotique'
      fullPath: '/services/robotique'
      preLoaderRoute: typeof ServicesRobotiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/seo': {
      id: '/services/seo'
      path: '/services/seo'
      fullPath: '/services/seo'
      preLoaderRoute: typeof ServicesSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/webcare': {
      id: '/services/webcare'
      path: '/services/webcare'
      fullPath: '/services/webcare'
      preLoaderRoute: typeof ServicesWebcareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/audits/$auditId': {
      id: '/dashboard/audits/$auditId'
      path: '/$auditId'
      fullPath: '/dashboard/audits/$auditId'
      preLoaderRoute: typeof DashboardAuditsAuditIdRouteImport
      parentRoute: typeof DashboardAuditsRoute
    }
    '/dashboard/prospects/$prospectId': {
      id: '/dashboard/prospects/$prospectId'
      path: '/$prospectId'
      fullPath: '/dashboard/prospects/$prospectId'
      preLoaderRoute: typeof DashboardProspectsProspectIdRouteImport
      parentRoute: typeof DashboardProspectsRoute
    }
  }
}

interface DashboardAuditsRouteChildren {
  DashboardAuditsAuditIdRoute: typeof DashboardAuditsAuditIdRoute
}

const DashboardAuditsRouteChildren: DashboardAuditsRouteChildren = {
  DashboardAuditsAuditIdRoute: DashboardAuditsAuditIdRoute,
}

const DashboardAuditsRouteWithChildren = DashboardAuditsRoute._addFileChildren(
  DashboardAuditsRouteChildren,
)

interface DashboardProspectsRouteChildren {
  DashboardProspectsProspectIdRoute: typeof DashboardProspectsProspectIdRoute
}

const DashboardProspectsRouteChildren: DashboardProspectsRouteChildren = {
  DashboardProspectsProspectIdRoute: DashboardProspectsProspectIdRoute,
}

const DashboardProspectsRouteWithChildren =
  DashboardProspectsRoute._addFileChildren(DashboardProspectsRouteChildren)

interface DashboardRouteChildren {
  DashboardAuditsRoute: typeof DashboardAuditsRouteWithChildren
  DashboardLoginRoute: typeof DashboardLoginRoute
  DashboardNewRoute: typeof DashboardNewRoute
  DashboardProspectsRoute: typeof DashboardProspectsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAuditsRoute: DashboardAuditsRouteWithChildren,
  DashboardLoginRoute: DashboardLoginRoute,
  DashboardNewRoute: DashboardNewRoute,
  DashboardProspectsRoute: DashboardProspectsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  FaqRoute: FaqRoute,
  MentionsLegalesRoute: MentionsLegalesRoute,
  NotreHistoireRoute: NotreHistoireRoute,
  RealisationsRoute: RealisationsRoute,
  RecrutementRoute: RecrutementRoute,
  RefonteSiteInternetRoute: RefonteSiteInternetRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkRoute: WorkRoute,
  ApiAuditRoute: ApiAuditRoute,
  ApiCreateCheckoutRoute: ApiCreateCheckoutRoute,
  ApiSendQuoteRoute: ApiSendQuoteRoute,
  ServicesServiceIdRoute: ServicesServiceIdRoute,
  ServicesRobotiqueRoute: ServicesRobotiqueRoute,
  ServicesSeoRoute: ServicesSeoRoute,
  ServicesWebcareRoute: ServicesWebcareRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
